### ISSUE TITLE
hard-coded relation for apt update ( manage_repo not counted ) on Debian

### ISSUE THREAD

**Issue by olevole** [elastic/puppet-elasticsearch#1000]
* Module version: 6.3.3
* Puppet version:  5.3.6
* OS and version: Debian GNU/Linux 9.5 (stretch)

## Bug description

elasticsearch::package does not take into account manage_repo settings; hard-coded relation for apt update

## Feature Description

elasticsearch::manage_repo:false 

leads to an error:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Could not find resource 'Class[Apt::Update]' for relationship on 'Package[elasticsearch]'`

due to package.pp has:

```
   if ($facts['os']['family'] == 'Debian') {
        Class['apt::update'] -> Package['elasticsearch']
      }
```

it (and maybe other places for other platforms) requires additional processing for **manage_repo** settings, something like

```
if ($elasticsearch::manage_repo) {
     Class['apt::update'] -> Package['elasticsearch']
} else {
     Package['elasticsearch']
}
```

**Comment by tylerjl** [comment]
Thank you for the report @olevole, merged a fix in #1001
