### ISSUE TITLE
undefined method `mask' for Service[elasticsearch]

### ISSUE THREAD

**Issue by TuningYourCode** [elastic/puppet-elasticsearch#1007]
* Module version: 6.3.3
* Puppet version: 4.8.2
* OS and version: Debian Jessie

## Bug description
`==> default: Error: Could not set 'mask' on enable: undefined method `mask' for Service[elasticsearch](provider=debian):Puppet::Type::Service::ProviderDebian at /tmp/vagrant-puppet/modules-606a154db90df0d3020b82f9d898947a/elasticsearch/manifests/config.pp:105
==> default: Error: Could not set 'mask' on enable: undefined method `mask' for Service[elasticsearch](provider=debian):Puppet::Type::Service::ProviderDebian at /tmp/vagrant-puppet/modules-606a154db90df0d3020b82f9d898947a/elasticsearch/manifests/config.pp:105
==> default: Wrapped exception:
==> default: undefined method `mask' for Service[elasticsearch](provider=debian):Puppet::Type::Service::ProviderDebian
==> default: Error: /Stage[main]/Elasticsearch::Config/Service[elasticsearch]/enable: change from false to mask failed: Could not set 'mask' on enable: undefined method `mask' for Service[elasticsearch](provider=debian):Puppet::Type::Service::ProviderDebian at /tmp/vagrant-puppet/modules-606a154db90df0d3020b82f9d898947a/elasticsearch/manifests/config.pp:105`

**Comment by tylerjl** [comment]
Resolved with #1008
