### ISSUE TITLE
Instance scripts catalog's not being populated

### ISSUE THREAD

**Issue by Jakski** [elastic/puppet-elasticsearch#1014]
* Module version: 6.3.3
* Puppet version: 5.5.10
* OS and version: CentOS Linux release 7.6.1810 (Core)

## Example manifest

```
include ::java

class { 'elastic_stack::repo':
  version => 5,
}

elasticsearch::script { 'addtag.groovy':
  source => '/mnt/code/puppet-elasticsearch/manifests/addtag.groovy'
}

class { 'elasticsearch':
  version => '5.6.12-1',
}

elasticsearch::instance { 'es01': }
```

## Bug description

Puppet ElasticSearch module doesn't copy scripts from `configdir` to instance scripts catalog. It puts scripts in directories:

- `/usr/share/elasticsearch/scripts`
- `/etc/elasticsearch/scripts`

but leaves `/etc/elasticsearch/es01/scripts` empty. I suppose it's related to this: https://github.com/elastic/puppet-elasticsearch/blob/dca7e5d3840ff597279e25351a511e23e22bd638/manifests/instance.pp#L369 Changing `recurselimit` to `2` made Puppet copy contents of `/etc/elasticsearch/scripts` to `/etc/elasticsearch/es01/scripts` and allowed ElasticSearch to load them.

Can you please explain why `recurselimit` is below 2? I forked this module and changed `recurselimit` to 2(https://github.com/Jakski/puppet-elasticsearch/commit/73c38d0a1d7330a4f62436a5ea83d188b577b23c) - it passes tests and lets ElasticSearch load scripts as expected.

**Comment by tylerjl** [comment]
@Jakski I suspect that recurselimit may have been erroneously set to `1` when it should have been `2` - if the tests continue to pass, that's probably good enough to be a safe change. I can put together a PR when I get a chance (there are some underlying test bugs that I'm looking at now) or someone can feel free to submit a PR if they get a chance.
