### ISSUE TITLE
RFC: Remove support for instances

### ISSUE THREAD

**Issue by tylerjl** [elastic/puppet-elasticsearch#1025]
I thought I had created a ticket for this previously, but: multi-instance support is essentially the root cause for nearly every bug this module has, and there have been more people than not expressing they'd like to use the module without the feature present.

As a user and developer of this module, I'd really like to refactor it with the next major release to drop support for managing > 1 instance of elasticsearch, essentially removing the need to define any `elasticsearch::instance` resources. It means that running, say, a separate client and data node on the same host is no longer possible, but the practice itself can be problematic to begin with, and I think that running Docker containers to encapsulate distinct daemons instead of system-level services is preferable in that scenario.

I'd like to solicit feedback if there are concerns for/against this plan from any community members.

EDIT: /cc @jethr0null

**Comment by wangqinghuan** [comment]
Hi, some issues  which are caused by multiple-instances have precluded users from using puppet. Hope to see the next release as soon as possible.

**Comment by lukasertl** [comment]
I'd second that - but how would the transistion look like if I'm currently using the module?  (I'm only running one instance, but still...)

**Comment by tylerjl** [comment]
@lukasertl I haven't written any changes yet, but my hope is that since you can always configure custom data directories, taking explicit steps won't be necessary to move or migrate existing installations, just making small changes to data directories and so on. I'm not 100% sure it'll be that clean, but it seems to make sense in theory.

**Comment by Lord-Y** [comment]
Too bad actually to removed it but if that can help the quality of next releases, I'm sure people will be okay with that.

**Comment by tylerjl** [comment]
@TJM yeah, that's what I'd like to do, ideally. Now that there's been an Elasticsearch 7.x release, there's an opportunity to make some breaking changes in a 7.x release of this module, which should be preceded by some deprecation notices in the next 6.x release here.

**Comment by albgus** [comment]
What about running Elasticsearch on large (physical) machines? I was under the impression that it was considered good practice running multiple smaller instances rather than one huge instance on larger machines. Say for instance running 4x instances with 16GB heap and maybe 250 shards rather than one big with 64GB heap and 1000 shards.

**Comment by TJM** [comment]
From what I understand, you do want to keep your HEAP just under 32GB, due to some java garbage collection issues. Do people still use physical machines? :p

This is definitely an argument for keeping the *capability* to manage instances, but I still think the module should be simplified to just manage the "default" instance in most cases.

**Comment by tylerjl** [comment]
In cases which multiple instances of ES _must_ be run on a single host, invoking those instances using a different mechanism will end up being much more maintainable by leveraging runtimes like Docker containers. Invoking >1 Elasticsearch container is a fine method; the techniques that this module uses in order to support >1 Elasticsearch daemon is really, really hacky and breaks constantly when upstream configuration files change. This has seemed fine from the Puppet side for a long time just because I've scrambled to make quick fixes to keep things stable, but I just can't do it any more. I went with the "try to make it work" option to keep things the same, but at this point the experiment is pretty conclusive that the design just doesn't work well. I've tried really hard - I know making the change is going to cause problems for some people, but its in the best interest of having a good, stable module in the long run.

On the topic of multiple instances in general, although I do think that using Docker containers is a good alternative, running more than one Elasticsearch daemon is probably bound to cause some very subtle and/or unexpected behavior in the long term, so (where you can) scaling Elasticsearch horizontally instead of vertically will probably always end up with better results. 2 or 3 running Elasticsearch daemons on one host won't necessarily be aware of each other and introduces CPU/filesystem cache/IO contention across those instances that Elasticsearch can't predict.

**Comment by TJM** [comment]
Also, for what it's worth, I see no reason that the puppet module version has to match the product version. It just occurred to me that another project was trying to do this and based on the comments above, that was probably the same here. In my opinion, the puppet module should have a list of supported "product" versions vs module versions. We should not try to release a new puppet module version for each product version, as it may not be necessary, and frequently a minor release can add support for a new version without breaking backward compatibility. Obviously changing the "instance" functionality is a major release ;).

**Comment by tylerjl** [comment]
@TJM my anecdotal experience thus far - which has been to not sync up the module with Elasticsearch releases; i.e., 5.x worked okay with 6.x, and so on - is that everybody gets confused. Starting to follow the upstream release versions more closely was a reaction on my part to try and cut down on the support I've had to do in answering questions for people about whether version `x.y` supports Elasticsearch version `a.b`. The supported versions are always noted in the README but it appears that, unfortunately, people don't read it most of the time :grimacing:

**Comment by TJM** [comment]
Understood ;)

**Comment by Lord-Y** [comment]
Any progress on this topic? Refactoring or not refactoring?

**Comment by tylerjl** [comment]
I think the answer is that it will be refactored, but bottlenecked on myself finding time to get into the code (I'm not opposed to reviewing PRs if others want to take a shot, but I understand it's a big change that touches many pieces)

**Comment by vartan-j2** [comment]
I'd love to see a new version of this module with to option to not use instances,  Im still using version 0.3.2 of the deprecated module.

**Comment by varman87** [comment]
I'd love to see a new version of this module with to option to not use instances, Im still using version 0.3.2 of the deprecated module.

**Comment by fatmcgav** [comment]
We've just released version `7.0.0` of this module which removes the support for running multiple instances on a single node.
