### ISSUE TITLE
Can't create elasticsearch.yml at default location

### ISSUE THREAD

**Issue by alechiko** [elastic/puppet-elasticsearch#1029]
* Module version: 6.3.3
* Puppet version: 5.5.10
* OS and version: Centos 7.3.1611

## Bug description

I hope that I am opening this issue in the right place.

I wanted to understand the reasoning behind the decision to disable the default location of the elasticsearch.yml file from `/etc/elasticsearch/elasticsearch.yml`.

I am referring to the following code

[config.pp](https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/config.pp#L71)

To the best of my knowledge, when installing elasticsearch according to their official documentation, a Yum based install will create the file at that location.

If I only want to run one instance of elastic on a server, why do I then need to provide an instance name where by it will create `/etc/elasticsearch/my-instance/elasticsearch.yml`.

I am assuming this is an intended feature and not a bug because when I ran the following:

```
class { 'elasticsearch':
    version => '6.2.4',
    status => 'disabled',
    datadir_instance_directories => false,
    config => {
      'cluster' => {
        'network.host'     => '_site_',
        'node.name'        => $facts['hostname'],
      }
    }
  }
}
```

It installs elasticsearch and then removes all of the default files. 

```
Notice: /Stage[main]/Elasticsearch::Package/Package[elasticsearch]/ensure: created
Info: /Stage[main]/Elasticsearch::Package/Package[elasticsearch]: Scheduling refresh of Exec[remove_plugin_dir]
Notice: /Stage[main]/Elasticsearch::Package/Exec[remove_plugin_dir]: Triggered 'refresh' from 1 event
Notice: /Stage[main]/Elasticsearch::Config/File[/usr/share/elasticsearch/plugins]/ensure: created
Notice: /Stage[main]/Elasticsearch::Config/File[/etc/elasticsearch/scripts]/ensure: created
Info: Computing checksum on file /etc/elasticsearch/elasticsearch.yml
Info: /Stage[main]/Elasticsearch::Config/File[/etc/elasticsearch/elasticsearch.yml]: Filebucketed /etc/elasticsearch/elasticsearch.yml to puppet with sum 3aa77775c113d3828a9e8e87637eb286
Notice: /Stage[main]/Elasticsearch::Config/File[/etc/elasticsearch/elasticsearch.yml]/ensure: removed
Info: Computing checksum on file /etc/elasticsearch/jvm.options
Info: /Stage[main]/Elasticsearch::Config/File[/etc/elasticsearch/jvm.options]: Filebucketed /etc/elasticsearch/jvm.options to puppet with sum 775a7b047687f7389149bff042a0e04d
Notice: /Stage[main]/Elasticsearch::Config/File[/etc/elasticsearch/jvm.options]/ensure: removed
Info: Computing checksum on file /etc/elasticsearch/log4j2.properties
Info: /Stage[main]/Elasticsearch::Config/File[/etc/elasticsearch/log4j2.properties]: Filebucketed /etc/elasticsearch/log4j2.properties to puppet with sum b3030447ca9e02e0e19b2c3d38bea137
Notice: /Stage[main]/Elasticsearch::Config/File[/etc/elasticsearch/log4j2.properties]/ensure: removed
```

If I understand this feature correctly, you can't create the config file at the default location. It needs to exist under the name of an instance that you specify.

Is this a sensible default?

Thanks,

**Comment by specdevops** [comment]
What was the solution to this? I have the same question.

Can anyone clarify?
