### ISSUE TITLE
Travis-CI tests appear to be broken.

### ISSUE THREAD

**Issue by pillarsdotnet** [elastic/puppet-elasticsearch#1046]
See for example https://github.com/elastic/puppet-elasticsearch/pull/1044

**Comment by tylerjl** [comment]
As of 8e0779863341 the master branch should have stable tests - testing for 7.x is off for now, as that'll require some significant changes (and likely a major release to make the changes to support it) but we should be unblocked to make miscellaneous fixes. Those snapshot tests can be re-enabled when 7.x support is formally added.
