### ISSUE TITLE
ES_PATH_CONF must be set to the configuration path

### ISSUE THREAD

**Issue by spawnzao** [elastic/puppet-elasticsearch#1051]
* Module version: v6.3.4
* Puppet version: 4.10.12
* OS and version: CentOS 7 3.10.0-957.27.2.el7.x86_64 

## Bug description

When I try to run:
`bin/elasticsearch-users list`

Return the error:
`ES_PATH_CONF must be set to the configuration path`

I add the ES_PATH_CONF parameter to the /etc/sysconfig/elasticsearch file, but when puppet executes it removes the parameter:

```
Notice: Augeas[/etc/sysconfig/elasticsearch](provider=augeas):
--- /etc/sysconfig/elasticsearch        2019-08-19 13:22:44.591354576 -0300
+++ /etc/sysconfig/elasticsearch.augnew 2019-08-19 13:23:08.301081824 -0300
@@ -21,8 +21,6 @@
 ################################
 # Elasticsearch service
 ################################
-ES_PATH_CONF=/etc/elasticsearch
-
```

**Comment by tylerjl** [comment]
This is removed by Puppet for a reason in order to make multi-instance support work - when that support get dropped as part of #1025, this will start working as expected.
