### ISSUE TITLE
Centos/RHEL 8 support

### ISSUE THREAD

**Issue by gokuatkai** [elastic/puppet-elasticsearch#1100]
Hello, is there a plan to support centos/rhel version 8 for this module?

**Comment by fatmcgav** [comment]
Hey @gokuatkai

We've just released version `7.0.0` of this module which includes support for CentOS 7 and Elasticsearch 7.x.

Please note that this release has some breaking changes, so please review the readme and changelog if you're an existing user of the module.

Thanks
