### ISSUE TITLE
elasticsearch::init does not respect service_name other than 'elasticsearch'

### ISSUE THREAD

**Issue by sysadmin1139** [elastic/puppet-elasticsearch#1110]
* Module version: 7.0.0
* Puppet version: 5.5.22
* OS and version: Ubuntu 18.04

## Bug description

When setting `service_name` as part of class setup, we get errors about `Could not find resource 'Service[elasticsearch]' `

```
  class { 'elasticsearch':
    service_name => 'not-elasticsearch';
  }
```
In `manifests/config.pp` there are three of places where a dependency is set using the static value of `Service['elasticsearch']`. These should be updated to use the variable defined as part of init.
* https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/config.pp#L72
* https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/config.pp#L80
* https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/config.pp#L222

**Comment by shamil** [comment]
This is by design, read about the reason here: https://github.com/elastic/puppet-elasticsearch/pull/1107
