### ISSUE TITLE
In some cases /etc/elasticsearch dir doesn't exists

### ISSUE THREAD

**Issue by electrical** [elastic/puppet-elasticsearch#13]
Reported on IRC

err: /Stage[main]/Elasticsearch::Config/File[/etc/elasticsearch/elasticsearch.yml]/ensure: change from absent to file failed: Could not set 'file on ensure: No such file or－
directory - /etc/elasticsearch/elasticsearch.yml.puppettmp_6029 at /etc/puppet/modules/elasticsearch/manifests/config.pp:42

Solution: Make sure we manage the existence of that directory just in case.

**Comment by unavailabl3** [comment]
If your Elasticsearch can't find hunspell dictionaries because there is no /etc/elasticsearch folder - just create folder with your hands sudo mkdir -p /etc/elasticsearch/hunspell
I don't know why, but ES is looking for hunspell only in /etc/elasticsearch
