### ISSUE TITLE
ruby-augeas depdency missing

### ISSUE THREAD

**Issue by jezdez** [elastic/puppet-elasticsearch#143]
In the official Vagrant Ubuntu 12.04 box this leads to this hard to debug error:

```
err: Could not find a suitable provider for augeas
```

Adding this to our manifest fixed it but this should better be in this module instead:

```
package { "ruby-augeas":
    ensure   => installed,
    provider => gem,
}
```

**Comment by ge-fa** [comment]
@erikvanoosten Still helpful as of today! Thanks!
