### ISSUE TITLE
$datadir should default to somewhere on /var instead of /usr

### ISSUE THREAD

**Issue by mfournier** [elastic/puppet-elasticsearch#185]
When using `elasticsearch::instance`, I noticed ES stores it's data in `/usr/share/elasticsearch/data`, which is a bit unexpected.

https://github.com/elasticsearch/puppet-elasticsearch/blob/master/manifests/params.pp#L104 was changed in 72c4c76c7bcd9. Was this maybe unintended as this commit seems to just refactor tests ?

**Comment by ctrlaltdel** [comment]
+1

BTW, it will also cause troubles to folks upgrading from previous versions of this module.

**Comment by electrical** [comment]
The version that had this change has been out so long i doubt it will cause any more issues.
I think it will cause more hurt if i would change it again.
Closing it for now, can always revisit in the future.
