### ISSUE TITLE
augeas requirement not listed in puppet forge

### ISSUE THREAD

**Issue by chad-upton** [elastic/puppet-elasticsearch#212]
Hey guys, pretty self explanatory but:

In init.pp and systemd.pp it has augeas methods but augeas isn't listed as a dependency and I see no provider for it.

Easy enough to resolve, but wanted to make sure it wasn't over looked.

Thanks for the outstanding module!

**Comment by electrical** [comment]
@chad-upton sorry you are running into this issue.
When using the puppetlabs repo's ( which most people do in prod environments ) augeas is automatically installed indeed.
I'm not sure if there is a nice way to manage the dependency.

**Comment by electrical** [comment]
Hi,

Augeas is now reported under the requirements at https://github.com/elastic/puppet-elasticsearch#requirements

Closing
