### ISSUE TITLE
Whups, is it possible to uninstall / rollback ?

### ISSUE THREAD

**Issue by SteveDevOps** [elastic/puppet-elasticsearch#227]
In my test env, I have run a manifest for a specific node. In my manifest I'm running the main elasticsearch class - to ge tthe core install -- but specifying repo_version, a single instance with associated config, and 3 plugins. I tried to downgrade the repo from 1.4 to 1.1.1. This failed with errors, and I ended up putting it back to 1.4, and re-running agent to fix the install. I'm testing on centos 7.

So then I have to ask, is it at all possible to rollback everything using ensure => 'absent' or ensure => 'purged' ? And if not, would it be doable as a feature request to have a built-in uninstall function? Being a puppet newb, I've done some reading on modules to discover that this typically doesn't happen or has to be built-in to the module.

I can forsee a situation where we might have a unforseen compatibility problem with one repo version and want to either downgrade or uninstall. Or where I'm at now.. realizing I put the latest version on a test system, when I really needed an older version to match what's currently in production. Thoughts?

**Comment by electrical** [comment]
Hi,

Downgrading packages is not easy because the package managers them selves don't always allow it.
You can however uninstall the whole software by setting ensure => 'absent' in the main class.
The only downside of that is that we might also delete all your data ( not 100% sure about this one )

**Comment by SteveDevOps** [comment]
I can report this worked for me If i unwind it backwards..
set plugins to absent,
set instance to absent, 
and then main class to absent. 

That removed everything successfully on centos7.. just left emply folders and subfolders.

**Comment by electrical** [comment]
Ah, you are completely right indeed.

https://github.com/elasticsearch/puppet-elasticsearch/blob/master/manifests/config.pp#L120

At the moment i don't delete much unless its specified in other parts ( like the instances stuff or plugins )
I should add removal of everything in there so you only need to set the main class to remove everything.
I'll put it on my todo list to make it remove more so we leave it cleaner when setting it to absent.

**Comment by electrical** [comment]
Following up via #305
