### ISSUE TITLE
Plugin installations and upgrades

### ISSUE THREAD

**Issue by electrical** [elastic/puppet-elasticsearch#269]
Trying to collect all the different plugin related issues into a single issue so we can have a single place of thought on the subject.

Related issues/PR's:

https://github.com/elasticsearch/puppet-elasticsearch/issues/203
https://github.com/elasticsearch/puppet-elasticsearch/issues/180
https://github.com/elasticsearch/puppet-elasticsearch/pull/101
https://github.com/elasticsearch/puppet-elasticsearch/pull/213

The current plugin define has some big issues that need to be solved before going to the 1.0 release.

- `module_dir` config option is not very clear.
- upgrading a plugin is not easy

The `module_dir` option was made to let the exec function decide if the plugin should be installed or not by validating if the directory exists or not.
This was required since the resource name of the plugin define is completely different then the eventual directory name.
Because of my own fault its documented in a bad way which causes confusion.

Upgrading a plugin has never been easy since I've never supported it.
The action for this means that the plugin needs to be removed and installed.
The main issue with this functionality is the version checking.
Since not every plugin may have its version number exposed it gets harder to validate it.

We could use a file containing the resource name that was used which may have the version number that was used as described in PR #213 but feels very hacky.

Any idea's and thoughts on this are welcome.

**Comment by ranguard** [comment]
Hi, I just got stuck on `java.lang.NoClassDefFoundError: Lorg/elasticsearch/indices/InternalIndicesService` eventually worked out that marvel needed upgrading.

This was after I upgraded from ES 1.4.4 to ES 1.5.0

I wonder if one option is to have a flag allowing reinstall of  all plugins when ES is upgraded as this seems likely to be the point that there may be issues.

Just an idea - thanks for a great module otherwise

**Comment by electrical** [comment]
@ranguard that will be an extremely hard thing to do.
Especially if plugins are pinned to a certain version, which i assume people do since specific versions of the plugins work with certain ES versions.
I'll keep it in mind though if a solution comes to mind.

**Comment by jlintz** [comment]
Yea I just got bit by the lack of being able to upgrade a plugin.  It would be great if it detected a version that it could remove and re-install and if there's no version maybe just throw an error?

**Comment by electrical** [comment]
Plugin upgrades has been implemented.
Not automated like @ranguard hoped it would but atleast you can change the version number and will upgrade it automatically.

In #343 I filed a solution to get rid of the module_dir hack.

**Comment by electrical** [comment]
#213 was merged to support upgrades
#232 was merged to get rid of the module_dir hack.

Automatic upgrading based on the ES version is not supported and is fairly impossible so far.
Perhaps at some point we can revisit that but at the moment there is no system in place that will allow us doing that.

**Comment by ranguard** [comment]
@electrical Thanks for your work on this
