### ISSUE TITLE
travis fails

### ISSUE THREAD

**Issue by cristi1979** [elastic/puppet-elasticsearch#270]
In order to make travis pass for ruby 1.8.7, you need to change the rspec dependency to version 2:

from:
    gem 'rspec-puppet', :git => 'https://github.com/electrical/rspec-puppet.git', :branch => 'rspec3'
to:
    gem 'rspec-puppet', '~> 2.0'

Or give up on testing on ruby 1.8.7

**Comment by electrical** [comment]
Yeah. I noticed it was failing the other day.
I think i'll give up on Travis completely since i run all our tests via our Jenkins setup anyway as well ( including PR testing )
See http://build-eu-00.elasticsearch.org/view/Puppet/ for more details.

**Comment by halfninja** [comment]
Looks like you can include badges from Jenkins, if you wanted to replace the Travis one in the readme.

http://build-eu-00.elasticsearch.org/view/Puppet/job/Puppet_Elasticsearch_Acceptance_Extra/badge/icon

![puppet-elasticsearch Acceptance Extra](http://build-eu-00.elasticsearch.org/view/Puppet/job/Puppet_Elasticsearch_Acceptance_Extra/badge/icon)

**Comment by electrical** [comment]
Following up via #306
