### ISSUE TITLE
Create a connection validator resource

### ISSUE THREAD

**Issue by Spredzy** [elastic/puppet-elasticsearch#275]
Some Puppet modules (mongodb[1], puppetdb[2]) do provide a X_conn_validator resource, where X is the name of the service to check. This make it possible to "suspend" (while validating) the puppet run, until the service is actually up and running.

Elasticsearch bootstrap is not instantaneous, hence currently, it is possible to apply resources that depends on the Elasticsearch instance to be up and running, but that is not (even with ordering).
## Proposed solution
- First patchset : create an `es_instance_conn_validator` resource that would check that port P is listening on host H, applying the same pattern as mongodb and puppetdb.

``` puppet
es_instance_conn_validator { 'myinstance' :
  server  => 'foo.bar',
  port    => '9200',
  timeout => 60,
}
```
- Second patchset : create a `$validate_instance` parameter for `elasticsearch::instance`, that if enabled will integrate the `es_instance_conn_validator_resource` in the catalog for that instance.

[1] https://github.com/puppetlabs/puppetlabs-mongodb/blob/master/lib/puppet/type/mongodb_conn_validator.rb
[2] https://github.com/puppetlabs/puppetlabs-puppetdb/blob/master/lib/puppet/type/puppetdb_conn_validator.rb

**Comment by electrical** [comment]
The first patchset hasb een merged.
Feel free to send a PR for the second one.
Cheers.

**Comment by electrical** [comment]
Hiya, will you be having time to work on this further? Worst case i'll leave this open for some one else to implement or when i have time.

**Comment by Spredzy** [comment]
Heya @electrical, sorry for the lack of activity on this one. Unfortunately I won't have time in the near future to work on that issue, I agree on leaving it open if anyone wants to take it.
