### ISSUE TITLE
elasticsearch::instance / ensure => absent will fail in second puppetrun.

### ISSUE THREAD

**Issue by derjohn** [elastic/puppet-elasticsearch#277]
If you set a  elasticsearch::instance to ensure => absent, it will remove it correctly but will in the second puppet run complain, that it cannot remove it because it is not there :-/

rgds,
j.

**Comment by electrical** [comment]
Hi,

Thank you very much for reporting it.
Would you be able to pastebin/gist the output of the second run so i can see which parts of it fail?
Thanks!

**Comment by electrical** [comment]
Hi,

I've done several tests with the latest release and didnt see this issue.
Could you verify?

**Comment by electrical** [comment]
Closing due to lack of response. Please open a new issue if this is still a problem. Thank you.
