### ISSUE TITLE
Manage log directory location

### ISSUE THREAD

**Issue by mattyindustries** [elastic/puppet-elasticsearch#278]
I've recently upgraded from version 0.4.0 to version 0.9.1.

One of the changes in this upgrade is the file resource for the Elasticsearch log directory /var/log/elasticsearch.

In my implementation I change my log directory to be /app/elasticsearch/log in the elasticsearch config file and seperately to this module I change /var/log/elasticsearch to symlink to /app/elasticsearch/log.

There isn't a mechanism to change the parameter $elasticsearch::params::logdir.

I'm going to raise a Pull Request to add this functionality but before I do so can someone explain why the log directory is set to recurse and why a number of the directory modes are 0644?

Puppet is smart enough to recognize it is a directory but it doesn't read clearly when reviewing the Puppet manifest.

Cheers

Mathew Archibald

**Comment by electrical** [comment]
I did review the PR you sent https://github.com/elastic/puppet-elasticsearch/pull/288 but no reply was sent after initial review.
Will close that PR and put on my todo list to add this feature.

**Comment by daks** [comment]
+1

**Comment by electrical** [comment]
Hi, sorry it took a while but it wasn't high on the priority list.
I've implemented this feature via https://github.com/elastic/puppet-elasticsearch/pull/566
Planning to do a release next monday ( Feb 1 )
