### ISSUE TITLE
Path settings issue

### ISSUE THREAD

**Issue by AlBlanc** [elastic/puppet-elasticsearch#280]
Hello,

I am facing issues with this puppet module. I want to specify some path into the configuration but none of these are followed. A default elasticsearch configuration file is generated (at /etc/elasticsearch/elasticsearch.yml)  and another one following my rules at (/etc/elasticsearch/01/elasticsearch.yml). But it looks like elasticsearch is using only the default one.

The agent is running ubuntu 14.04. Here is a snippet of my puppet configuration:

```
class { 'elasticsearch':
     package_url => 'https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.\
4.4.deb',
     config => {
       'cluster.name' => 'xxxx',
       'path' => {
         'data' => '/data/elasticsearch/data',
         'logs' => '/data/elasticsearch/logs',
         'plugins' => '/data/elasticsearch/plugins',
       },
       'http.cors' => {
	 'enabled' => true,
	 'allow-origin'	=> 'http://kibana.xxxx.co'
       },
    },
    datadir => '/data/elasticsearch/xxxx',
    java_install => true  # Require puppetlabs/java
   }

  elasticsearch::instance { '01':
  }
```

**Comment by AlBlanc** [comment]
It looks like init.d script is overriding the configuration file.

https://github.com/elasticsearch/puppet-elasticsearch/blob/master/templates/etc/init.d/elasticsearch.Debian.erb

**Comment by AlBlanc** [comment]
Works fine after moving /etc/elasticsearch/01/elasticsearch.yml to /etc/elasticsearch/elasticsearch.yml and removing default parameters into init.d script.

But i can't use this module. Hope this will be fixed soon

**Comment by electrical** [comment]
Hi,

the /etc/elasticsearch/elasticsearch.yml file is not used at all any more since we support multiple instances.
All relevant config files should be in the /etc/elasticsearch/01 directory in your case.
Also the correct ini script is elasticsearch-01 then.

**Comment by electrical** [comment]
Closing due to lack of feedback.
