### ISSUE TITLE
upgrading module from 0.4.0 to 0.9.1 causes cycle dependency error

### ISSUE THREAD

**Issue by daks** [elastic/puppet-elasticsearch#282]
Hello,

I tried to upgrade this module from version 0.4.0 to 0.9.1. It causes a cycle dependency error

    (Exec[download_package_elasticsearch] => Class[Elasticsearch::Package] => Class[Elasticsearch::Config] => File[/opt/elasticsearch] => File[/opt/elasticsearch/swdl] => Exec[download_package_elasticsearch])

My associated code didn't change.
It is composed of a common 'profile' definition *(more Puppet code is in there, like java version, collectd plugins and /etc/security/limits.conf management)*

    class { 'elasticsearch': 
        package_url     => 'https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.4.deb',
        datadir         => '/opt/elasticsearch',
    }

and a node definition like

    include profiles::elasticsearch::base
    elasticsearch::instance { 'clustername':
        init_defaults   => { 'ES_HEAP_SIZE' => '6g' },
        config          => { 
                            'cluster.name'              => 'clustername',
                            'node.name'                 => 'nodename',
                            'node.master'               => false,
                            'bootstrap.mlockall'        => true,
                            },
    }

The error message looks like:

    Could not apply complete catalog: Found 1 dependency cycle:
    (Exec[download_package_elasticsearch] => Class[Elasticsearch::Package] => Class[Elasticsearch::Config] => File[/opt/elasticsearch] => File[/opt/elasticsearch/swdl] => Exec[download_package_elasticsearch])

The associated cycles graph is https://i.imgur.com/mQPbG8r.png

**Comment by electrical** [comment]
I do have a system test that installs the package via the package_url and never seen this dependency cycle.
Can you confirm the upgrade of the module is successful?

**Comment by electrical** [comment]
Ah wait, i think i see the issue. you have selected `/opt/elasticsearch` for the data directory but we manage `/opt/elasticsearch/swdl` separately but `/opt/elasticsearch` is automatically selected as a dependency causing the dependency cycle.

Must admit i have never tested for this use case.
You could try to set the `package_dir` to something else then `/opt/elasticsearch/swdl` or change the datadir.

**Comment by daks** [comment]
in fact, changing package_dir to be outside datadir solved my problem. Strange edge case :)

**Comment by electrical** [comment]
Must admit i haven't thought about this situation.
Perhaps i need to move the default pkg dir to something else, or find an other solution for this.
Any idea's are welcome :-)

**Comment by electrical** [comment]
Hi

Just to give an update on this.
I haven't been able to come up with a solution for this so far.
I think this is such an edge case we can ignore it for now unless it comes up again.
What are your thoughts about it?

**Comment by electrical** [comment]
Closing as no alternative solution could be thought up, considering this as an edge case.
Might review in the future.
