### ISSUE TITLE
Add syslog logger support

### ISSUE THREAD

**Issue by jkroepke** [elastic/puppet-elasticsearch#283]
Hi,

I want to use syslog with elasticsearch. syslog can be configure like here:
https://github.com/elasticsearch/elasticsearch/issues/527#issuecomment-553427

Best Regards
Jan

**Comment by electrical** [comment]
Hi,

You can supply your own logging.yml file to the module to manage those kind of things.

**Comment by electrical** [comment]
Closing as no feedback has been given for 3 weeks.
