### ISSUE TITLE
There's no way to set LimitMEMLOCK when use systemd as service provider

### ISSUE THREAD

**Issue by psychonaut** [elastic/puppet-elasticsearch#285]
... or at least it's not documented.

With commented #LimitMEMLOCK=infinity entry there is default setting for memory lock limits (on centos7 it is 65536 bytes.

**Comment by electrical** [comment]
Ah, very good one. I'll have a better look at this issue next week and see if i can implement a solution.
Any idea's are most welcome.

**Comment by psychonaut** [comment]
I just did quick&dirty change in template. But I think it could be done by using augeas with systemd lens:
http://augeas.net/docs/references/lenses/files/systemd-aug.html

**Comment by electrical** [comment]
Ah cool. will take a look at that augeas lens and see how i can implement a best solution.
Thanks!

**Comment by electrical** [comment]
I'll be bringing out a release today without a fix for this as i would like to fix this correctly with a bit more time.
But i'll make sure this gets fixed in the next release ( hopefully next week )

**Comment by electrical** [comment]
Sorry for the delay.
https://github.com/elastic/puppet-elasticsearch/pull/313 implemented a feature so you can set the 2 options you mentioned.
Hope this is enough for your use case?

**Comment by psychonaut** [comment]
Looks like it. Do you know when it will be released?

**Comment by electrical** [comment]
I'm planning to do a release this week. Doing some cleaning up and getting things into shape for the release.

**Comment by psychonaut** [comment]
W dni wto 26 maj, 2015 o 15∶13 użytkownik Richard Pijnenburg 
<notifications@github.com> napisał:
> I'm planning to do a release this week. Doing some cleaning up and 
> getting things into shape for the release.
> 
> —
> Reply to this email directly or view it on GitHub.
> 


Thnx.

  eloy

**Comment by electrical** [comment]
Release is done. https://twitter.com/Richardp82/status/603849063524671488

**Comment by lf-** [comment]
Hi! Sorry to resurrect this, just want this to be out here: It's actually a systemd or selinux policy problem. If you set selinux to permissive it will work without the fix. See my redhat bug: https://bugzilla.redhat.com/show_bug.cgi?id=1415045
