### ISSUE TITLE
Specifying JAVA_HOME in init defaults is not exported in init.d script

### ISSUE THREAD

**Issue by dforste** [elastic/puppet-elasticsearch#286]
Specifying JAVA_HOME in init defaults is not exported in RedHat init.d script. 
Add a line to check for definition of JAVA_HOME and export it after sourcing the defaults file.

**Comment by dforste** [comment]
I suggest the following fix. 
````
checkJava() {
    if [ -x "$JAVA_HOME/bin/java" ]; then
        JAVA="$JAVA_HOME/bin/java"
+        export JAVA_HOME
    else
        JAVA=`which java`
    fi

    if [ ! -x "$JAVA" ]; then
        echo "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME"
        exit 1
    fi
}
````
This ensures JAVA_HOME is already defined.

**Comment by dforste** [comment]
Fixed in Pull Request #287

**Comment by electrical** [comment]
Hi,

Is there anything that requires this? Haven't had any issues so far without this. ( just trying to understand it )

**Comment by dforste** [comment]
There is no issue when a system java is available in $PATH. The issue occurs when java is not installed in $PATH and the which java command returns a JAVA version. If you try setting up JAVA_HOME without java in the path the init script fails to export JAVA_HOME for use in the elasticsearch user environment. This leaves elasticsearch lost as to where either JAVA_HOME or JAVA is.  Sorry for the delayed response.

**Comment by flopex** [comment]
I can reproduce this same issue under CentOS 6.6 x64. Both PATH and JAVA_HOME are being ignored by use in "/sbin/service elasticsearch-instance start", however, it works fine with the use of "/etc/init.d/elasticsearch-instance start". This is due to the fact that service ignores all environment variables except for PATH, TERM and LANG. check_java should use PATH if the method of managing the service is going to be through "Service" and not init.d

**Comment by electrical** [comment]
Hi guys,

Thank you very much for the details.
I think this is something that should be solved upstream then just only in the puppet module.
Would one of you mind sending a PR to the elasticsearch repo as well so we do solve this permanently?

For the time being i'll merge the PR in the puppet module.

Thanks!

**Comment by dforste** [comment]
I created a PR to the upstream. https://github.com/elastic/elasticsearch/pull/11166 Do I need to duplicate this issue upstream? Or can it simply be merged?

**Comment by electrical** [comment]
lost track of this issue. Its been solved upstream and in the module as well a while ago.
