### ISSUE TITLE
Add the ability to create and populate the config/scripts directory

### ISSUE THREAD

**Issue by afx114** [elastic/puppet-elasticsearch#300]
Now that dynamic scripting has been disabled as of ES v1.4.3, many people (including myself) are probably migrating their scripts to be disk-based.  This requires the placement of `.groovy` files into the `config/scripts` directory on *every single data node* in a cluster.  There doesn't seem to be a way to automate this using this puppet module, but it would be nice to be able to manage these scripts similar to the way we can manage templates.  Perhaps something like:

```javascript
elasticsearch::script {
    'my_script_name':
        file => 'puppet:///path/to/my_script.groovy
}
```

This would install the `my_script.groovy` file into `config/scripts/my_script.groovy`, making it available to be used in queries.

**Comment by electrical** [comment]
Thank you very much for the feature request.
you've raised a very valid point and I'll try to make a solution for this with the next release.

**Comment by electrical** [comment]
Hi,

I just started working on this feature by scoping the feature and design.
Since the module supports multi instance we would need to have the scripts on all the instances per server.
Would it make sense ( if possible ) to have the scripts in a single directory that is available for all the instances on that server?
Also do you know how to register these scripts or how to call them in a query ?

**Comment by afx114** [comment]
The scripts need to be in a specific directory: `config/scripts` so I suppose if there is one `config` dir for each instance, then the scripts would need to be in each `config/scripts` for each instance.

I imagine this would work exactly the way templates do now.  In fact, I was thinking you could basically just copy the template code and rename a few things and it would work for scripts out of the box.

The scripts are picked up by the watcher every 60 seconds, and you refer to the script name in your queries.

**Comment by electrical** [comment]
Thanks for the info.
Did have a chat with the ES guys as well and at the moment it can't be changed indeed so i created https://github.com/elastic/elasticsearch/issues/10369 to get it changed ( hopefully )

As a temp solution i could let the main class create a scripts directory and let each instance define create a symlink from its own scripts dir to the central one.

What do you think?

**Comment by electrical** [comment]
Seems https://github.com/elastic/elasticsearch/issues/6766 already exists for this change :-)

**Comment by afx114** [comment]
I think the symlink workaround is a fine temp solution.

**Comment by electrical** [comment]
@afx114 I've created https://github.com/elastic/puppet-elasticsearch/pull/309 for it.
Could you have a look when you have the time?

Cheers.

**Comment by afx114** [comment]
I think that looks pretty good (added comment to the PR).  I will try and run some tests this or next week to see how it all works.
