### ISSUE TITLE
Restart on upgrade

### ISSUE THREAD

**Issue by coreone** [elastic/puppet-elasticsearch#301]
I have been using this module for a while, and it's great!  The one thing I did notice, however, is that if you set the package to autoupgrade, it will upgrade just fine, but the service won't restart as a part of that upgrade.  I think there needs to be a notify inside the package.pp, probably something along the lines of:

```
package { $elasticsearch::package_name:
  ensure   => $package_ensure,
  source   => $pkg_source,
  provider => $pkg_provider,
  notify => Class['elasticsearch::service']
}
```
Normally I would do a pull request for something like this, but I am not in a spot where I can do that currently.

Thanks!

**Comment by electrical** [comment]
Hi,

In most cases people will want to do a controlled restart of the cluster to ensure that shards don't reallocate for example.
That's the main reason why i haven't implemented a notify to the service.
We potentially could make it optional.

**Comment by electrical** [comment]
Due to the operational nature of ES i've decided against restarting the service with package upgrade.
