### ISSUE TITLE
Pinning elasticsearch package

### ISSUE THREAD

**Issue by electrical** [elastic/puppet-elasticsearch#315]
Pinning the package to a certain version ( optional ) allows to add more security when someone by accident or purposely does an apt-get upgrade / yum update.
This ensures that Elasticsearch package is not upgraded to a newer version and only is done when we really want that.

Any feedback is welcome.

**Comment by joshuar** [comment]
What's the difference between adding code for pinning or removing the ability to specify `ensure => latest` and the autoupgrade functionality?

**Comment by electrical** [comment]
@joshuar Pinning a package allows us to secure the version on the system. If someone decides to manually run a package upgrade ( apt-get upgrade / yum update ) we are sure that Elasticsearch does not get upgraded by accident.
This only works when we specify a version.

Auto upgrade and ensure latest are different ways of upgrading a package, even if we removed those someone with shell access could still upgrade the package.

**Comment by electrical** [comment]
#331 implemented Package pinning for most distro's. Still need to add it for OpenSuse/Sles

**Comment by electrical** [comment]
OpenSuse/SLES will be solved in next version.
