### ISSUE TITLE
Installation broken for puppetlabs-apt 2.0.0

### ISSUE THREAD

**Issue by claussni** [elastic/puppet-elasticsearch#322]
The repo installation doesn't work with the recent `puppetlabs-apt 2.0.0`. The error is:
```
Error: Invalid parameter key_source on Apt::Source[elasticsearch] at /etc/puppet/modules/elasticsearch/manifests/repo.pp:46
```
Here is the module list:
```
/etc/puppet/modules
├── elasticsearch-elasticsearch (v0.9.5)
├── puppetlabs-apt (v2.0.0)
├── puppetlabs-java (v1.3.0)
└── puppetlabs-stdlib (v4.6.0)
```
It works again by forcing version 1.8.0 of `puppetlabs-apt`.

[This commit](https://github.com/puppetlabs/puppetlabs-apt/commit/0f3bdcdf5a44315197ded803401b52dfcce38ebe) in puppetlabs-apt seems to break it.

**Comment by electrical** [comment]
I noticed the same issue today with the spec tests indeed.
Next release will force to be below 2.0 so it won't break it for the time being.

**Comment by alejandrobednarik-olx** [comment]
I already made a pull request to fix this issue.

**Comment by claussni** [comment]
For the sake of documentation: https://github.com/elastic/puppet-elasticsearch/pull/326

**Comment by electrical** [comment]
I've done a documentation update stating apt < 2.0 is required.
Closing this issue.

**Comment by madAndroid** [comment]
This should be resolved with the latest release of the `puppetlabs-apt` module - see https://github.com/puppetlabs/puppetlabs-apt/blob/master/CHANGELOG.md#summary
