### ISSUE TITLE
Why I can't use custom facts?

### ISSUE THREAD

**Issue by ladshada** [elastic/puppet-elasticsearch#325]
Hi!

In this document I have read about custom facts.
https://www.elastic.co/blog/elasticsearch-puppet-module-0-9-0-released
>>We also added different custom facts to expose interesting information about the running Elasticsearch instances.

But I don't see any of this facts in my facter.

facter -p | grep elasticsearch
elasticsearch_ports => 9200

How can I see elasticsearch_9200_cluster_name and other facts?

**Comment by philipwigg** [comment]
Can you show us your Puppet manifest?

**Comment by ladshada** [comment]
Sure.

node 'test' { 
class { 'elasticsearch':
	manage_repo		=>	true,
	repo_version	=>	'1.5',
	version			=>	'1.5.1-1',
	datadir			=> '/opt/elasticsearch/data',
	config	=>	{
		'discovery.zen.ping.multicast.enabled'			=> 'false',
		'index.number_of_shards'						=> '16',
		'index.number_of_replicas'						=> '1',
		'bootstrap.mlockall'							=> 'true',
		'threadpool.bulk.type'							=> 'fixed',
		'threadpool.bulk.size'							=> '16',
		'threadpool.bulk.queue_size'					=> '3000',
		'index.refresh_interval'						=> '40s',
		'index.translog.flush_threshold_ops'			=> '50000',
		'threadpool.search.type'						=> 'fixed',
		'threadpool.search.size'						=> '20',
		'threadpool.search.queue_size'					=> '100',
		'threadpool.index.type'							=> 'fixed',
		'threadpool.index.size'							=> '20',
		'threadpool.index.queue_size'					=> '100',
		'indices.memory.index_buffer_size'				=> '30%',
		'indices.memory.min_shard_index_buffer_size'	=> '12mb',
		'indices.memory.min_index_buffer_size'			=> '96mb',
		'indices.fielddata.cache.size'					=> '15%',
		'indices.fielddata.cache.expire'				=> '6h',
		'indices.cache.filter.size'						=> '15%',
		'indices.cache.filter.expire'					=> '6',
		'index.refresh_interval'						=> '30s',
		'index.translog.flush_threshold_ops'			=> '50000',
		'index.translog.flush_threshold_size'			=> '100mb',
		'index.cache.field.max_size'					=> '50000',
		'index.cache.field.expire'						=> '10m',
		'index.cache.field.type'						=> 'soft',
		'shield.audit.enabled'							=> 'true',
		'marvel.agent.enabled'							=> 'true',
		'discovery.zen.ping.timeout'					=> '30s',
		'shield.ssl.hostname_verification.resolve_name'	=> 'false',
		'http.max_content_length'						=> '512m',
	}, 
	init_defaults => {
		'ES_HEAP_SIZE'								=> '30g',
		'WORK_DIR'									=> '/tmp/elasticsearch',
		'MAX_LOCKED_MEMORY'							=> 'unlimited',
		'ES_JAVA_OPTS'								=> '-Des.path.conf=/etc/elasticsearch',
		'ES_USER'									=> 'elasticsearch',
		'ES_GROUP'									=> 'elasticsearch',
	},
}

elasticsearch::instance {"$hostname":
	ensure	=>	present,
	config	=>	{
		'cluster.name'									=> 'CLUSTER',
		'node.name'										=> "$hostname",
		'node.master'									=> 'true',
		'node.data'										=> 'true',
		'discovery.zen.ping.unicast.hosts'				=> '["ip"]',
		'marvel.agent.exporter.es.hosts'				=> '["http://user:passwd@ip:9200","http://user:passwd@ip2:9200"]',
}}

elasticsearch::template { '1_template':
  content => '{"template":"1*","settings":{"number_of_shards": 16, "number_of_replicas":1}}'
}
}

**Comment by philipwigg** [comment]
Hmmm.. that is strange.

If I apply your manifest to a Vagrant machine running Ubuntu I get the following output (I had to change the version since it couldn't find 1.5.1 in the apt repo for some reason):-

```
root@localhost:/# facter -p | grep elas
elasticsearch_9200_cluster_name => CLUSTER
elasticsearch_9200_mlockall => true
elasticsearch_9200_name => localhost
elasticsearch_9200_node_id => t3lMFGKJS0ConPNYX9egag
elasticsearch_9200_plugins =>
elasticsearch_9200_version => 1.5.0
elasticsearch_ports => 9200
```

Have you restarted your Puppet master after you've upgraded the module? This is necessary to pick up new custom facts.

If you've done that, is it possible to search for es_facts.rb on the host itself and check it matches the version in ```puppet-elasticsearch/lib/facter/es_facts.rb``` in Github?

**Comment by ladshada** [comment]
Yes, I have restarted puppet master and the content of my es_facts.rb is the same to puppet-elasticsearch/lib/facter/es_facts.rb in Github.

I checked out that this issue I can see only in CentOS 7.1. On my servers with CentOS 7.0 custom facts work.

CentOS 7.1
ruby --version
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]

CentOS 7.0
ruby --version
ruby 2.0.0p353 (2013-11-22) [x86_64-linux]

Is this a reason?

**Comment by philipwigg** [comment]
Actually...upon closer inspection. Do you have the Shield plug in enforcing basic auth on your Elasticsearch endpoints? 

The custom fact relies on being able make an HTTP request to localhost on the ES port to get all of the information in the facts (except the port fact, which you do see).

**Comment by ladshada** [comment]
Yes, I have Shield plugin with basic auth.
So, with Shield this custom facts don't work?

**Comment by philipwigg** [comment]
From looking at the code, it seems like this would be the case I'm afraid.

I will see if I can think of a workaround.

Maybe  @electrical can help too?

**Comment by philipwigg** [comment]
@ladshada - out of interest, is Shield a difference between your 7.0 and 7.1 nodes?

**Comment by ladshada** [comment]
Yes. Nodes on the 7.1 are test nodes, and on the 7.0 are production nodes.

**Comment by electrical** [comment]
Hi guys,

This is indeed a problem when shield is installed since the custom facts do a curl request to the http port without auth.
I'm thinking of adding support for a auth file where a simple user/pass string is added and use that for the authentication.

**Comment by electrical** [comment]
As addition the template insert action won't work either since we don't provide a username / password for that either.
So i'm thinking of adding a http_user and http_pass option to the module and let the rest use those values for any http related actions.

**Comment by philipwigg** [comment]
Do you mean you would put a file on the filesystem and let the custom fact read that? That would work, I'm not sure about the security implications.

Or you could just insist that they configure Shield to allow anonymous users to have access to whatever the fact needs?

http://www.elastic.co/guide/en/shield/current/authentication.html#anonymous-access

I'm not very knowledgable about Shield I'm afraid.

**Comment by electrical** [comment]
@philipwigg yeah, its not a great solution.
Anonymous access is something i can take a look at

**Comment by philipwigg** [comment]
@electrical It's not an easy one...

PD. see you at DoxLon tonight!

**Comment by electrical** [comment]
@philipwigg ah cool. nice to finally meet you :-)

**Comment by ladshada** [comment]
I think, I can write my own facts, that can parse elasticsearch.yaml and take information about cluster from there. I am experienced in bash :)

**Comment by electrical** [comment]
Current solution i'm thinking about is not the most clean one but should work.

1. Place a file ( yaml ) in /etc/puppet ( or other correct dir depending on puppet version ) with username / password for the custom facts. Make sure only the puppet user can read it.
2. Let the custom fact read that file for the authentication when using shield.
3. The same values can be used in other http actions like the template installation.

This would mean that http_user and http_pass options will be added.
Security wise i would advise to use eyaml with hiera to store the password encrypted.

Reasoning for this, is that anonymous access is not that advisable ( after talking to the shield dev's )

**Comment by electrical** [comment]
So, here's an other idea i discussed yesterday on puppet irc channel.
We could write out the custom facts from a template and place it in the facts.d directory which contains the username / password combo.
It will still be plain text but at least its not a separate file.

I know its still stored somewhere plain text but can't think of any other solution besides just failing entirely when using shield ( which is something i don't like to do )

**Comment by daks** [comment]
Hello,
i'm running module 0.9.1 and if I look at a client (Puppet 3.4.2 on Debian Wheezy) I have no elasticsearch facts too.
And my master has been restarted since.

**Comment by electrical** [comment]
@daks do you have the shield plugin installed by any chance?

**Comment by daks** [comment]
oups sorry I forgot this information, no Shield is not installed. I only use kopf plugin on ES 1.4.4

**Comment by electrical** [comment]
Okay, could you supply the config you pass on to the instance? My best guess is that you bound it to a specific IP while the custom facts only bind to localhost directly.

**Comment by daks** [comment]
This is the configuration (simplified) for my ES data node:

    class { 'elasticsearch': 
        package_url     => 'https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.4.deb',
        package_dir     => '/opt/elasticsearch-download',
        datadir         => '/opt/elasticsearch',
    }

    elasticsearch::instance { 'logs':
        init_defaults   => { 'ES_HEAP_SIZE' => '8g' },
        config          => { 
                            'cluster.name'              => 'logs',
                            'node.name'                 => 'x',
                            'node.master'               => false,
                            'bootstrap.mlockall'        => true,
                            'http.cors.enabled'         => true,
                            'http.cors.allow-origin'    => '/http?:\/\/.*\.mydomain\.tld/',
                            },
    }

Which generates the following ES configuration:

    ### MANAGED BY PUPPET ###
    ---
    bootstrap: 
      mlockall: true
    cluster: 
      name: logs
    http: 
      cors: 
        allow-origin: /http?:\/\/.*\.mydomain\.tld/
        enabled: true
    node: 
      master: false
      name: x
    path: 
      data: /opt/elasticsearch/logs

ES instance is not bound to a specific IP, netstat gives me:

    # netstat -tupln
    tcp6       0      0 :::9200                 :::*                    LISTEN      16480/java      
    tcp6       0      0 :::9300                 :::*                    LISTEN      16480/java   
    udp6       0      0 :::54328                :::*                                16480/java

**Comment by electrical** [comment]
hi, i think in this case the cors setting blocks it since we do a curl call to localhost.

**Comment by daks** [comment]
oh, okay, so adding localhost to my cors domain could solve the problem? not sure about the format but i'll try.

**Comment by electrical** [comment]
I'm not sure about the format either but that should solve it yeah.

**Comment by tylerjl** [comment]
Closing after inactivity.
