### ISSUE TITLE
Unable to launch ES service

### ISSUE THREAD

**Issue by rthijssen** [elastic/puppet-elasticsearch#327]
The module works great until it tries to launch the elasticsearch instance that has been defined in the puppet file.

My puppet config:
```
class { 'elasticsearch':
	manage_repo  => true,
	repo_version => '1.5',
	autoupgrade => true,
	status => 'running'
}

elasticsearch::instance { 'es-01': }
```

When trying to run this on a fresh Debian (8 Jessie) machine - but also happened on Debian 7 machines - I get the following error:
```
Error: Could not start Service[elasticsearch-instance-es-01]: Execution of '/usr/sbin/service elasticsearch-es-01 start' returned 6: Failed to start elasticsearch-es-01.service: Unit elasticsearch-es-01.service failed to load: No such file or directory.
```

I'm using puppet in a Vagrant box so the message might be slightly different for someone who is using puppet directly.

**Comment by electrical** [comment]
Hi,

Support for debian 8 is coming. Debian 7 should work fine as my own tests are running nicely with it so that's weird.
In Debian 7 we still use the old init script, in debian 8 we are moving to systemd.

**Comment by rthijssen** [comment]
Cool got it.

I must have missed something. Service just launched fine on Debian 7. Apologies.

**Comment by electrical** [comment]
No worries, can happen :-)
