### ISSUE TITLE
elasticsearch module not compatible with new puppetlabs/apt module

### ISSUE THREAD

**Issue by TravellingGuy** [elastic/puppet-elasticsearch#333]
The latest puppetlabs/apt module (v. 2.0.0) has had a major refactor.

When the elasticsearch module is configured to manage the repo (manage_repo => true), puppet agent fails with an error:
> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter key_source

**Comment by philipwigg** [comment]
Hi, this is a duplicate of #322.

Basically you need to use the apt module < 2.0 and the next release will enforce that.

The module can't support apt 2.0 yet because it breaks compatibility with older PE versions.

**Comment by TravellingGuy** [comment]
Thanks. I can live with the incompatibility for the time being.

Incidentally, I did do a search for the problem before posting my new issue, but I neglected to search Closed issues. Doh.
