### ISSUE TITLE
restart_on_change should have a different default

### ISSUE THREAD

**Issue by faxm0dem** [elastic/puppet-elasticsearch#336]
I think `elasticsearch::restart_on_change = false` should be the default value, as long as there is no [elasticsearch rolling restart API call](/elastic/elasticsearch/issues/9046). Indeed, using puppet to manage multiple cluster nodes could have catastrophic consequences with this parameter set to `true`.

**Comment by electrical** [comment]
I tend to agree with this since automatic restarts on config changes is something we wouldn't want.
Feel free to send a PR otherwise i'll make the change my self.

**Comment by tylerjl** [comment]
Changed all default restart_* parameters to `false` in #655, changes will be part of the next release (1.0.0).
