### ISSUE TITLE
Automatic plugin name abstraction

### ISSUE THREAD

**Issue by electrical** [elastic/puppet-elasticsearch#343]
With the current implementation we find out if a plugin is installed or not by passing the directory where it is installed.
Right now that directory name has to be passed on manually to the define which causes a lot of confusion and its just very ugly.

Since the naming is fairly consistent we should be able to write a parser that takes the full plugin name as value and do some magic to extract the resulting directory name of it.

**Comment by philipwigg** [comment]
Could maybe have a custom function that duplicates the code here?

https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/plugins/PluginManager.java#L622

**Comment by electrical** [comment]
That part does the the opposite of what i want to do and i need mine to be more generic i think.
From any plugin naming convention i have to extract the most likely plugin dir name.
as an example:

`elasticsearch/elasticsearch-cloud-aws/1.4.3` would have directory `cloud-aws`
`lmenezes/elasticsearch-kopf` into `kopf`

And there are most likely more different options.
So at the moment i'm thinking of splitting at `/` take the middle part if there are 3 ( org/name/version )
or the last bit if its only 2 ( org/name )
And then extract the first name + `-` and assume the rest to be the directory.
I'll have to write some tests with loads of different plugins to ensure I'm doing the right thing :-)

**Comment by philipwigg** [comment]
Ah my reading of that ```parse``` method was that it was taking a plugin full name like ```elasticsearch/elasticsearch-cloud-aws/1.4.3``` and returning a PluginHandle object with ```name``` set to what you're looking for, i.e. ```cloud-aws```.

**Comment by electrical** [comment]
@philipwigg I've been reading the code wrong you were completely right.
I copied over the same logic and works like a charm :-)

**Comment by philipwigg** [comment]
Ah good to hear :+1:

**Comment by philipwigg** [comment]
Will it cope with plugins that are just fetched via a URL?

**Comment by electrical** [comment]
that's a whole different beast that i will have to think about :-)
Still thinking what to do with that one.

**Comment by philipwigg** [comment]
Yeah not easy :-) The plugin manager must deal with the same problem in some way too I guess.

**Comment by electrical** [comment]
It actually doesn't, it relies on the user giving the right name and uses that for the resulting directory :-)

**Comment by electrical** [comment]
So i could use the resource name for the resulting directory name, or do some very cool logic based on the file name they download?

**Comment by philipwigg** [comment]
I guess resource name seems easiest since you would want them to be able to supply that as a parameter anyway?

Does it deal with '_site' plugins? Seems like that's a thing too.

**Comment by electrical** [comment]
yeah indeed, could leave that up to the user.
site plugins is something the plugin manager handles it self, i don't have to take that in account.

**Comment by philipwigg** [comment]
Ah cool, good stuff.

**Comment by electrical** [comment]
Could you take a look at https://github.com/elastic/puppet-elasticsearch/pull/346 ?
