### ISSUE TITLE
0.9.6 on Debian 8 results in /var/run/elasticsearch/ being 0555

### ISSUE THREAD

**Issue by zobelhelas** [elastic/puppet-elasticsearch#349]
> Info: Caching catalog for stockhausen.debian.org
> Info: Applying configuration version '8cd033a'
> Notice: /Stage[main]/Elasticsearch::Config/File[/var/run/elasticsearch]/mode: mode changed '0755' to > '0555'
> Notice: /Stage[main]/Elasticsearch::Config/File[/var/run/elasticsearch/elasticsearch-es-01.pid]/mode: > mode changed '0644' to '0444'
> Notice: Finished catalog run in 14.41 seconds

Next time elasticsearch tries to start it tries to write it's pidfile to /var/run/elasticsearch/ it fails due to 'Permission denied'.

> root@stockhausen:/var/log/elasticsearch/es-01# journalctl -xn
> -- Logs begin at Mon 2015-04-27 00:25:42 UTC, end at Sat 2015-05-30 18:17:17 UTC. --
> May 30 18:16:59 stockhausen elasticsearch[30091]: {1.0.3}: pid Failed ...
> May 30 18:16:59 stockhausen elasticsearch[30091]: - 
FileNotFoundException[/var/run/elasticsearch/elasticsearch-es-01.pid (Permission denied)]
> May 30 18:16:59 stockhausen systemd[1]: elasticsearch-es-01.service never wrote its PID file. Failing.
> May 30 18:16:59 stockhausen systemd[1]: Failed to start Starts and stops a single elasticsearch instance on this system.
> -- Subject: Unit elasticsearch-es-01.service has failed
> -- Defined-By: systemd

**Comment by electrical** [comment]
Must admit i haven't seen this error in my acceptance testing before.
Could you copy the puppet code you used so I can try an recreate this ?

sent from my phone

**Comment by zobelhelas** [comment]
```
class roles::listsearch {

  class { 'elasticsearch':
    autoupgrade => false,
    config => { 'cluster.name' => 'listsearch' }
  }

  elasticsearch::instance { 'es-01':
    config => { 'node.name' => 'stockhausen' },
    init_defaults => { }, # Init defaults hash
    datadir => [ '/srv/listsearch.debian.org/es-data-es01' ],       # Data directory
  }
}
```

**Comment by AAlvz** [comment]
I haven't found the main issue but here is a quick [vagrant test environment](https://github.com/AAlvz/vagrants/tree/349-pe-es_pidfile/elasticsearch) I made in case someone finds the time to dig into this. =) 
I find strange that the `elasticsearch-es-01` service disappears after reboot... 

Here's another error I found that probably mess something up:
> systemd[1]: [/lib/systemd/system/elasticsearch-es-01.service:16] Failed to parse resource value,...oring:

The template comes from `elasticsearch/templates/etc/init.d/elasticsearch.systemd.erb`

**Comment by electrical** [comment]
This should be fixed now with https://github.com/elastic/puppet-elasticsearch/pull/378 i hope :-)

**Comment by electrical** [comment]
@AAlvz the issue you found should be solved with https://github.com/elastic/puppet-elasticsearch/pull/366

**Comment by AAlvz** [comment]
@electrical I made the necessary tests with the recent changes and there is no issue anymore. I think issue #349 is ready to be closed =)... If more testing is needed before closing this ticket let me know.

**Comment by electrical** [comment]
@zobelhelas can you confirm that with the latest release this issue is solved?
Cheers.

**Comment by electrical** [comment]
Closing issue due no response.
