### ISSUE TITLE
missing dependency from yum module

### ISSUE THREAD

**Issue by psychonaut** [elastic/puppet-elasticsearch#351]
With 0.9.6 update module no longer works:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type yum::versionlock at /etc/puppet/environments/qa/modules/elasticsearch/manifests/repo.pp:98 on node
```

I probably have to add yum module for dependency but it's not mentioned which one should be used. After short investigation [https://forge.puppetlabs.com/ceritsc/yum] is probably missing one but this should be mentioned at least in README file.

**Comment by electrical** [comment]
Hi,

I completely forgot about adding that one. my fault. Will make sure its added in the next release.
