### ISSUE TITLE
puppetlabs-apt 2.0.0 replaced apt::source's "key_source" parameter

### ISSUE THREAD

**Issue by amosshapira** [elastic/puppet-elasticsearch#358]
As of puppetlabs-apt 2.0.0, the "key_source" parameter to apt::source was deprecated in favour of "key => { source => ... }"

ref: https://github.com/puppetlabs/puppetlabs-apt/blame/master/CHANGELOG.md#L70

**Comment by amosshapira** [comment]
I see the metadata.json have been updated with the correct dependency three days ago, but Modulefile haven't and it seems that puppet-librarian (which is what I use to import external modules) reads it instead of metadata.json.

Perhaps it's time to either drop Modulefile completely or update it with the right version dependency?

**Comment by electrical** [comment]
@amosshapira thank you for the heads up, I should remove it indeed. Does puppet-librarian also read the metadata.json file if the Modulefile is not there?

**Comment by amosshapira** [comment]
The docs says it does (http://librarian-puppet.com/), but I'm not sure how to test it with a local change.

**Comment by electrical** [comment]
Ah cool. Will remove the Modulefile and keep the metadata.json file for the next release.

For the apt 2.0 support i'm not planning to support it for now due  to different reasons.
There are some closed issues / PR's already about it :-)

**Comment by amosshapira** [comment]
Thanks. I don't mind about sticking to the latest and greatest apt module version but I foresee dependency problems in a few months if this won't be addressed by then.

For now I just set the dependency explicitly in my Puppetfile (librarian-puppet's configuration file) so there is a trivial work-around.
