### ISSUE TITLE
split out restart_on_change into more granular options

### ISSUE THREAD

**Issue by electrical** [elastic/puppet-elasticsearch#363]
restart_on_change is to generic and should be expanded.
The basis of these options will also be that we choose the most safest possible defaults since ES is very sensitive to random restarts.

Currently thinking of the following options:

## Module generic options

- restart_on_change ( Default: false )
Master control for all other options.

- restart_package_change ( Default: false )
This set to true would restart the service if we upgrade the package.

- restart_config_change ( Default: false )
This set to true would restart the service if we change the configuration.

- restart_service_change ( Default: false )
Controls if we restart or not on any changes related to the services ( Defaults file / init / systemd )

## Es module specifics

- restart_plugin_change ( Default: false )
Set to true would restart the service when a plugin is installed. this is required for any java based plugins.

## Related to

#336

**Comment by bastelfreak** [comment]
Sounds good so far, restart_service_change will only restart the service if something in the servicefile itself changes and restart_config_change for every other configuration file? I'm not sure if it is needed to have two seperate params for these. 

I can't imagine a scenario where I change something in the config file and want to restart ES, but after that change something in the service file and don't want to restart.

**Comment by electrical** [comment]
Very good point.
restart_config and restart_package only then and we should be good?

**Comment by bastelfreak** [comment]
Yes, this should be sufficient.

**Comment by tylerjl** [comment]
Completed as of #655, will be part of the 1.0.0 release.
