### ISSUE TITLE
Centos 6.6 package pinning failed : Invalid resource type yum::versionlock

### ISSUE THREAD

**Issue by rfwekker** [elastic/puppet-elasticsearch#364]
Centos 6.6
Puppet v3.7.3 (Puppet Enterprise 3.7.1)
yum-plugin-versionlock is installed on the puppet server and puppet client

node "epclient5.connexys.nl" {
  class { 'elasticsearch':
     version => '1.4.4',
     repo_version => '1.4',
     manage_repo  => true,
}
}

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: 
Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type yum::versionlock 
at /etc/puppetlabs/puppet/environments/ontwikkeling/modules/elasticsearch/manifests/repo.pp:98 on 
node epclient5.connexys.nl

I have to use  package_pin => false

yum info yum-plugin-versionlock
Installed Packages
Name        : yum-plugin-versionlock
Arch        : noarch
Version     : 1.1.30
Release     : 30.el6
Size        : 43 k
Repo        : installed
From repo   : rdam
Summary     : Yum plugin to lock specified packages from being updated
URL         : http://yum.baseurl.org/download/yum-utils/
License     : GPLv2+
Description : This plugin takes a set of name/versions for packages and excludes all other
            : versions of those packages (including optionally following obsoletes). This
            : allows you to protect packages from being updated by newer versions,
            : for example.

**Comment by electrical** [comment]
Hi,
This is my fault. sorry. It requires a module that handles the version locking and i forgot to include it as a default required dependency.
https://github.com/elastic/puppet-elasticsearch/pull/357 solved it by adding it to the metadata.json file.
If you download the module ( ceritsc/yum ) it should be solved.

**Comment by rfwekker** [comment]
installed ceritsc-yum on puppet server
puppet module install  ceritsc-yum 
set pinning value
package_pin => true

Install still failed

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Package name must be formated as 'EPOCH:NAME-VERSION-RELEASE.ARCH' at /etc/puppetlabs/puppet/environments/ontwikkeling/modules/yum/manifests/versionlock.pp:30 on node epclient5.connexys.nl

**Comment by rfwekker** [comment]
installed ceritsc-yum on puppet server
puppet module install ceritsc-yum
set pinning value
package_pin => true

Install still failed

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Package name must be formated as 'EPOCH:NAME-VERSION-RELEASE.ARCH' at /etc/puppetlabs/puppet/environments/ontwikkeling/modules/yum/manifests/versionlock.pp:30 on node epclient5.connexys.nl

**Comment by rfwekker** [comment]
Fix repo.pp line 97 for Centos/RedHat package pinning
yum::versionlock { "0:elasticsearch-${elasticsearch::version}.noarch":
I
nsert -RELEASE as -*  
yum::versionlock { "0:elasticsearch-${elasticsearch::version}-*.noarch":

**Comment by electrical** [comment]
Ah, will try to do that. Currently i supply the version as x.y.z-1 for example.

**Comment by electrical** [comment]
having the release as * doesn't seem to work at all. just wants to install the latest version now instead of the required version.

**Comment by electrical** [comment]
I could make the release default to -1 ?

**Comment by rfwekker** [comment]
Install succeeded with version 1.4.4 release 1 ; Failed to update to version 1.4.4, got version 1.4.4-1 instead

After one successful install a few moments ago, in a second trial failed

Elastico deleted elasticsearch-1.4.4-1.noarch.rpm
Execution of '/usr/bin/yum -d 0 -e 0 -y list elasticsearch' returned 1: Error: No matching Packages to list
Error: /Stage[main]/Elasticsearch::Package/Package[elasticsearch]/ensure: change from absent to 1.4.4 failed:


If Elastic not use the RELEASE field consistently in then packagenaming, maybe you need both lines??
yum::versionlock { "0:elasticsearch-${elasticsearch::version}.noarch":
and
yum::versionlock { "0:elasticsearch-${elasticsearch::version}-*.noarch":

**Comment by electrical** [comment]
I see it yeah. so in any case for specifying a version of the package for centos/redhat the release version is always required.
To make it work adding the release version to the version string would be needed.
Perhaps i could add something to auto append that release number to the version number if it's not there and then assume '-1' as release version. if some one uses their own repo and has other release versions for example they could specify that in the version option. what do you think?

**Comment by electrical** [comment]
Working on a better solution which should solve the issue completely.

**Comment by electrical** [comment]
Hi, https://github.com/elastic/puppet-elasticsearch/pull/367 should solve the issue. can you check it out?
