### ISSUE TITLE
Can't install plugin with elasticsearch 1.6.0

### ISSUE THREAD

**Issue by s12v** [elastic/puppet-elasticsearch#368]
```
==> default: Notice: /Stage[main]/Main/Elasticsearch::Plugin[***]/Exec[install_plugin_***]/returns: /usr/share/elasticsearch/bin/plugin: 55: .: Can't open //etc/default/elasticsearch
==> default: Error: /usr/share/elasticsearch/bin/plugin -install *** -url http://*** returned 2 instead of one of [0,1]
==> default: Error: /Stage[main]/Main/Elasticsearch::Plugin[***]/Exec[install_plugin_***]/returns: change from notrun to 0 1 failed: /usr/share/elasticsearch/bin/plugin -install *** -url http://*** returned 2 instead of one of [0,1]
```

Seems to be related with this change:  https://github.com/elastic/elasticsearch/commit/862cec5634686ac70f358d0c81f6f79181a1208a - it tries to load the file from the default location, but I have `/etc/default/elasticsearch-esearch-dev-fp` (created by `elasticsearch::instance`, I guess)

**Comment by electrical** [comment]
Uhg. will find out how to solve this. sorry for the issue :-(

**Comment by s12v** [comment]
@electrical, maybe something like this: pass file location to the plugin https://github.com/s12v/puppet-elasticsearch/commit/6c48b28bba4764d5ebb045d65679e16614a12b12, also support on the tool side: https://github.com/s12v/elasticsearch/commit/1a210fc89257daa3b9573050c0fe5adb47a56235 ?

But so far no idea how to deal with multiple `$instances` and `$init_defaults_file`

**Comment by driegel** [comment]
I linked the config file of my first and only instance and so I could run plugin by hand.
```
ln -s /etc/sysconfig/elasticsearch-inst01 /etc/sysconfig/elasticsearch
```

Maybe you could change '/etc/puppet/modules/elasticsearch/manifests/config.pp'
```
file { '/etc/elasticsearch/elasticsearch.yml':
      ensure => 'absent',
}
```

to something like this:
```
file {'/etc/sysconfig/elasticsearch':
       ensure => link,
       target => "/etc/sysconfig/elasticsearch-inst01",
}
```

**Comment by electrical** [comment]
@driegel since we never know what the instance name will be, its gonna be a bit hard to do that :-)
I'll come up with some kind of a solution for this.

**Comment by driegel** [comment]
I just looked into it again. It seems that it is sufficient to set 'ES_INCLUDE' when the 'plugin' command is running:

```
export ES_INCLUDE=/etc/sysconfig/elasticsearch-inst01
```

I assume that setting this environment variable should not kill Elasticsearch < 1.6.0 plugin command.
For now I will work with this workaround since I use only one instance per host. Also, since 'plugin.pp' already knows about ES instances it might not be that difficult to fix the issue.

**Comment by electrical** [comment]
@driegel yeah, i came to the same conclusion.
the only thing that will cause issues is plugins that write config files.
But since there are not many around anyway it doesn't matter much.
I'll try to find a good solution for single and multiple instances as well.

**Comment by electrical** [comment]
Hi guys. #382 should solve the issue. Done some local tests and works. If any of you have the time to do some testing as well would be appreciated.

**Comment by driegel** [comment]
@electrical I tested it on one of my nodes in the ES cluster and it worked. Thanks.

**Comment by electrical** [comment]
@driegel thank you very much for the quick feedback, Will do some more testing on my side and merge it in. Planning to do a release today or tomorrow.

**Comment by electrical** [comment]
fix is merged and will be in next release. I'm currently aiming at tomorrow morning, want to make sure things are correct so letting CI bake it for a while.

**Comment by electrical** [comment]
CI seems to be happy and also integration testing with 1.6.0 and 1.6 snapshot branch seems to work fine.

http://build-eu-00.elastic.co/view/Puppet/view/Elasticsearch/job/Puppet_Elasticsearch_Integration_1x/

Will be doing a release this morning.

**Comment by s12v** [comment]
@electrical, works for me too, thanks!

**Comment by electrical** [comment]
@s12v thank you very much for the confirmation :-)
