### ISSUE TITLE
Repository management paths (new download url)

### ISSUE THREAD

**Issue by driegel** [elastic/puppet-elasticsearch#370]
When I turn on repo management, I get the following error:
```
Error: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install elasticsearch' returned 1: No Presto metadata available for elasticsearch

Error downloading packages:
  elasticsearch-1.6.0-1.noarch: [Errno 256] No more mirrors to try.
Wrapped exception:
Execution of '/usr/bin/yum -d 0 -e 0 -y install elasticsearch' returned 1: No Presto metadata available for elasticsearch
```

I believe, that the download site has changed, somehow this would need to be adjusted in 'repo.pp'
(https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html)

```
[elasticsearch-1.6]
name=Elasticsearch repository for 1.6.x packages
baseurl=http://packages.elastic.co/elasticsearch/1.6/centos
gpgcheck=1
gpgkey=http://packages.elastic.co/GPG-KEY-elasticsearch
enabled=1
```

**Comment by electrical** [comment]
That's weird since the old stuff still works for me and in my acceptance tests.
That said i do need to update it in the repo file :-)
Thanks for reminding me.

**Comment by driegel** [comment]
I believe that 'yum repolist' works.
I believe that 'yum install elasticsearch' doesn't work.

Of course, there is the same problem with the logstash 1.5 repo.

**Comment by electrical** [comment]
@driegel i do use the repo's as install source so its very weird its not working for you.
In any case i'm changing it now so should be working soon in the master branch.

**Comment by jaguth** [comment]
I just downloaded the puppet module this morning.  I get the exact same error when running within vagrant (vagrant provision):
==> default: Wrapped exception:
==> default: Execution of '/usr/bin/yum -d 0 -e 0 -y install elasticsearch-1.6.0-1' returned 1: Error Downloading Packages:
==> default:   elasticsearch-1.6.0-1.noarch: failure: elasticsearch-1.6.0.noarch.rpm from elasticsearch: [Errno 256] No more mirrors to try.

When I enter the vagrant box (vagrant ssh) and search for it in yum, it exists:  
[vagrant@hydrabox ~]$ sudo yum list | grep elasticsearch
elasticsearch.noarch                    1.6.0-1                     elasticsearch

The only way to install it is to install without a version:
sudo yum install elasticsearch

So this issue still exists.
