### ISSUE TITLE
Add proxy support for package download

### ISSUE THREAD

**Issue by hskwirblies** [elastic/puppet-elasticsearch#371]
We use some machines that connect to the internet via proxy servers. For these machines I figured out a working solution:
https://github.com/motortalk/puppet-elasticsearch/tree/add-download-proxy-parameter

Setting the proxy via exec{: environment => [] } using shell environment variables works on linux and darwin kernels, i.e. works with wget and curl.

For me it also looks feasible to use the same proxy parameters for elasticsearch::package and elasticsearch::plugin (which already has an appropriate parameter). That should be discussed.

**Comment by electrical** [comment]
Hi,

I agree that it would be a very nice feature and should be implemented indeed.
Feel free to send a PR with the required changes.
I also agree that the plugin install should utilize the same proxy.

Could you change it to however to proxy_host and proxy_port?
That way we have a generic setting and can use that anywhere that is needed and also provide that to the package + plugin parts.

Thanks!

**Comment by hskwirblies** [comment]
I could live with proxy_protocol, proxy_host and proxy_port parameters, but I would prefer a single proxy_url option.

My reasons:
# I already have a proxy_url setting in hiera, using proxy_host/proxy_port would add duplicate data
# proxy_url works seamless if https is used for the client->proxy connection just by using https://
# representation for proxies is also used by yum/apt repos and setting a shells proxy environment
# proxy_url is only one parameter in hiera not two (or up to five if the proxy uses basic authentication)

I would keep $proxy_host and $proxy_port for backwards compatibility in elasticsearch::plugin

**Comment by electrical** [comment]
@hskwirblies i completely understand that. I also prefer a single option.
My thought about it is because the plugin script requires some java parameters for setting the proxy parts.
If the plugin part can work with a single option then I'm more then happy to move to that.

**Comment by hskwirblies** [comment]
Perfect. I'll look into that later today.

**Comment by electrical** [comment]
This has now been merged and will be in the next release.
Thank!
