### ISSUE TITLE
Puppet 4 comparison operators work differently.

### ISSUE THREAD

**Issue by philipwigg** [elastic/puppet-elasticsearch#374]
We've recently upgraded to Puppet 4 and I've noticed some issues caused by the changes.

I thought I'd raise an issue now so you can take a look and see what I mean.

Take ```plugins.pp```:-

```
 if ($url == undef) {
    $install_cmd = "${elasticsearch::plugintool}${proxy} -install ${name}"
    $exec_rets = [0,]
  } else {
    validate_string($url)
    $install_cmd = "${elasticsearch::plugintool}${proxy} -install ${name} -url ${url}"
    $exec_rets = [0,1]
  }
```

For me, this always tries to install from a URL even though I haven't set ```$url```.

Changing the code to this fixed it in Puppet 4, I'm not sure if it then breaks Puppet 3:-

```
  unless $url {
    $install_cmd = "${elasticsearch::plugintool}${proxy} -install ${name}"
    $exec_rets = [0,]
  } else {
    validate_string($url)
    $install_cmd = "${elasticsearch::plugintool}${proxy} -install ${name} -url ${url}"
    $exec_rets = [0,1]
  }
```

I'm guess this has something to do with these changes:-

https://docs.puppetlabs.com/puppet/latest/reference/experiments_future.html#check-your-comparisons

**Comment by electrical** [comment]
Puppet 4 is something i wanted to address with 2.0 of the module, i didn't expect that people would be upgrading so quick :-)
If Puppet 4 is really something important then it might be useful to at least handle some of the things. 2.0 will only support Puppet 4 then.

**Comment by philipwigg** [comment]
Yeah we are living on the bleeding edge here... :-)

I think some people will be upgrading too... I'm not sure what issues there will be except for the ```($var == undef)``` test?

**Comment by electrical** [comment]
I'll see if i can replicate the issue with puppet-rspec and puppet4. If so i'll try to solve those issues. with one of the next releases.

**Comment by electrical** [comment]
I ran puppet-rspec with puppet 4 and didn't see this happening. weird stuff.

**Comment by electrical** [comment]
ran acceptance testing with puppet 4.0/4.1/4.2 and no issues that i've seen.

**Comment by MarkSummers** [comment]
I just found the same issue with Puppet 4.2.2

I output the value of $install_cmd and observed that it ended with "-url ".  The use case was as follows:

```
    elasticsearch::plugin{ 'elasticsearch/marvel/latest':
        module_dir => 'marvel',
        instances => [ 'es-01' ]
    }
```

**Comment by electrical** [comment]
Is this still an issue with the latest puppet module version?

**Comment by MarkSummers** [comment]
I believe so:

```
# puppet module list | grep elasticsearch
├── elasticsearch-elasticsearch (v0.9.6)
├── elasticsearch-logstash (v0.5.1)
├── elasticsearch-logstashforwarder (v0.1.1)
├── lhelasticsearch (???)
```

**Comment by electrical** [comment]
0.9.6 is fairly old. 0.9.9 is out :-)

**Comment by MarkSummers** [comment]
Thanks.  That also seems to have fixed another issue :)

**Comment by electrical** [comment]
hehe cool! If this issue is solved i think we can close it?

**Comment by MarkSummers** [comment]
Working here.
