### ISSUE TITLE
yum fails to find elasticsearch

### ISSUE THREAD

**Issue by mcandre** [elastic/puppet-elasticsearch#386]
This module claims to support CentOS, but when I try to install elasticsearch via this puppet module in CentOS (Docker's layerworx/puppet image), yum complains that it cannot find elasticsearch.

For RedHat-based distributions, could this puppet module please add the appropriate yum repositories / RPMs to the OS prior to attempting to install elasticsearch?

See https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html for relevant documentation.

**Comment by electrical** [comment]
Hi please see th readme for repo management since its already included :-)
