### ISSUE TITLE
Dependency Cycle when installing Plugin

### ISSUE THREAD

**Issue by traviscollins** [elastic/puppet-elasticsearch#393]
I'm attempting to install the marvel plugin on our elastic search cluster. Adding the elasticsearch::plugin causes a dependency cycle.  Below is my puppet config and the error

	class { 'elasticsearch' :
		manage_repo  => true,
		repo_version => '1.6',

	}->

	elasticsearch::instance { "elasticsearch":
	  config => {
	  		'node.name' => $hostname,
	  		'cluster.name' => "elasticsearch.${domain}",
	  		'node.data' => 'true',
	  		'node.master' => 'true',
	  		'discovery.type' => 'zen',
	  		'discovery.zen.ping.multicast.enabled' => 'false',
	  		'discovery.zen.ping.unicast.hosts' => 'elasticsearch1.dev1. company.com,elasticsearch2.dev1.company.com',
        	'script.disable_dynamic' => 'false'
	  		},
	  	datadir => $elasticSearchDataDirectories,
	  	init_defaults => {
			'ES_HEAP_SIZE' => '12g'
		}
	}->
	#elasticsearch::plugin{'elasticsearch/marvel/1.3.1':
  	#	instances  => 'elasticsearch',
  	#	module_dir => 'marvel'
	# }->

Jun 25 13:25:07 ip-172-30-0-60 puppet-agent[3181]: Could not apply complete catalog: Found 1 dependency cycle:
Jun 25 13:25:07 ip-172-30-0-60 puppet-agent[3181]: (Augeas[defaults_ elasticsearch] => Elasticsearch::Service::Init[elasticsearch] => Elasticsearch::Service[elasticsearch] => Elasticsearch::Instance[elasticsearch] => Elasticsearch::Plugin[elasticsearch/marvel/1.3.1] => Exec[install_plugin_elasticsearch/marvel/1.3.1] => Elasticsearch::Service[elasticsearch] => Elasticsearch::Service::Init[elasticsearch] => Augeas[defaults_ elasticsearch])

**Comment by electrical** [comment]
Hi,

You can remove the `->` parts since the whole module already takes care of dependencies and sequences out of the box.

**Comment by traviscollins** [comment]
That worked. Thanks.
