### ISSUE TITLE
Yum: No more mirrors to try.

### ISSUE THREAD

**Issue by jaguth** [elastic/puppet-elasticsearch#394]
I just downloaded the puppet module this morning. I get this error when running within vagrant (vagrant provision):
==> default: Wrapped exception:
==> default: Execution of '/usr/bin/yum -d 0 -e 0 -y install elasticsearch-1.6.0-1' returned 1: Error Downloading Packages:
==> default: elasticsearch-1.6.0-1.noarch: failure: elasticsearch-1.6.0.noarch.rpm from elasticsearch: [Errno 256] No more mirrors to try.

When I enter the vagrant box (vagrant ssh) and search for it in yum, it exists:
[vagrant@hydrabox ~]$ sudo yum list | grep elasticsearch
elasticsearch.noarch 1.6.0-1 elasticsearch

The only way to install it is to install without a version:
sudo yum install elasticsearch

Here is my puppet config for elasticsearch:
class { 'elasticsearch':
version => '1.6.0',
repo_version => '1.6',
manage_repo => true
}

I'm running centos6

**Comment by jaguth** [comment]
i discovered that it was yum that would download 99% and then the download would slowly go below 1k/sec, and then yum would error out because it wasn't downloading faster than 1k/sec for 30 seconds.  I updated to using centos7 and the issue has disappeared.  i will close this bug.

**Comment by electrical** [comment]
Thanks for the report and your findings. I'm afraid its very hard to differentiate between those errors indeed.
