### ISSUE TITLE
Plugin installation issues with ES 1.6.0

### ISSUE THREAD

**Issue by RJ3000** [elastic/puppet-elasticsearch#400]
Having issues installing plugins with the latest version of ES (currently 1.6.0-1) 
 
Error:
```
/usr/share/elasticsearch/bin/plugin -install elasticsearch/marvel/latest returned 1 instead of one of [0]
```

When run manually, it returns: 

```
/usr/share/elasticsearch/bin/plugin: line 55: //etc/sysconfig/elasticsearch: No such file or directory
```

It appears that there has been changes made to the plugin installation script in the latest version.
It now sets default variables which don't match filenames set by this module.

```
  CONF_FILE="/etc/elasticsearch/elasticsearch.yml"
  ES_ENV_FILE="/etc/sysconfig/elasticsearch"
```

**Comment by electrical** [comment]
Hi,

thank you for your report.
Which version of the module are you using?

Cheers.

**Comment by RJ3000** [comment]
Look to be using version 0.9.6
``` 
 "name": "elasticsearch-elasticsearch",
  "version": "0.9.6",
  "source": "https://github.com/elastic/puppet-elasticsearch",
```

**Comment by electrical** [comment]
Hi, version 0.9.7 has the fix for the issue you are having. 0.9.8 is out as well. Best thing is to upgrade :-)
