### ISSUE TITLE
Kibana4 won't start alongside Elasticsearch

### ISSUE THREAD

**Issue by darkefreet** [elastic/puppet-elasticsearch#402]
I've installed Ubuntu 14.04 on my VMware, with elasticsearch 1.5.0, OpenJDK 1.7.0_79,  and kibana4. 
I've installed both kibana4 and elasticsearch as services and every time elasticsearch is running, kibana4 won't start. When I stop elasticsearch and start kibana4, kibana4 just runs fine. Then I start elasticsearch again and kibana4 just stop by itself. When I use $sudo service kibana4 start, it gives me an [OK], but when I checked with $sudo service kibana4 status, the terminal tells me that kibana4 is not running.

This is the tutorial that I followed to install elasticsearch, https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-on-an-ubuntu-vps. 

With elasticsearch 0.90.7 which I first used when I followed the guide above, both kibana and elasticsearch services ran fine. Then I upgraded my JDK from 1.6 to 1.7 and my elasticsearch to 1.5, and this problem popped out.

**Comment by darkefreet** [comment]
Just downgraded my elasticsearch from version 1.5.0 to 1.4.4. It is odd that it is running fine now.

**Comment by electrical** [comment]
Hi,

Please use our discussion forum for these kind of questions. You can find it at https://discuss.elastic.co/
