### ISSUE TITLE
Possibility to edit/create logging.yml

### ISSUE THREAD

**Issue by psychonaut** [elastic/puppet-elasticsearch#409]
It would be Nice To Have possibility to generate/edit logging.yml file. For example we'd like to add syslog appender but with current flow it's not really possible.

**Comment by electrical** [comment]
Hi,

You can supply a custom logging file / template via the following options:

https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/init.pp#L142-L146

Cheers.

**Comment by psychonaut** [comment]
oh, great! thank you!
