### ISSUE TITLE
Plugins fail to install with Elasticsearch 1.7

### ISSUE THREAD

**Issue by bashtoni** [elastic/puppet-elasticsearch#413]
Plugins fail to install with Elasticsearch 1.7 under CentOS 7

Doing some digging, this seems to be because the plugin script tries to source `/etc/sysconfig/elasticsearch`, but it should be sourcing `/etc/sysconfig/elasticsearch-${instancename}`.

Setting the ES_INCLUDE environment variable will get the plugin script to use the correct file - I ran `ES_INCLUDE=/etc/sysconfig/elasticsearch-es /usr/share/elasticsearch/bin/plugin -i cloud-aws -u http://download.elasticsearch.org/elasticsearch/elasticsearch-cloud-aws/elasticsearch-cloud-aws-2.7.0.zip` from the config to install.

**Comment by electrical** [comment]
Hi,

which version of the module are you using?

**Comment by bashtoni** [comment]
`elasticsearch-elasticsearch (0.9.5)`

**Comment by electrical** [comment]
Ah okay. in 0.9.7 i fixed that bug. ( latest release is 0.9.8 )
If you upgrade it should be solved.

**Comment by bashtoni** [comment]
Awesome, thanks :)
