### ISSUE TITLE
Centos 7 Invalid resource type yum::versionlock 

### ISSUE THREAD

**Issue by ladshada** [elastic/puppet-elasticsearch#415]
I have updated module puppet-elasticsearch for the last version and when I tried to install watcher plugin I've got the next error

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type yum::versionlock at ../modules/elasticsearch/manifests/repo.pp:98 on node tmp

I found issue #364, that describes my problem, I thought it was solved. But not for me. :(

puppet 3.7.5
CentOS Linux release 7.1.1503 (Core)
puppet-elasticsearch module ##0.9.8 ( Jul 07, 2015 )

**Comment by electrical** [comment]
Hi,

Did you install the module `ceritsc-yum` ?
As far as i can see from the error that should solve it.

**Comment by ladshada** [comment]
Thanks!
It solved the issue.

**Comment by electrical** [comment]
great to hear :-)
