### ISSUE TITLE
Wrong version of elasticsearch?

### ISSUE THREAD

**Issue by BurningTheSky** [elastic/puppet-elasticsearch#421]
Hi,
I have deployed using the command below but had previously used repo 1.4. I have changed it to 1.7 now but I still seem to be getting the old version? Have I done something wrong? I am new to puppet so if I have done something obvious please forgive me.

       class { 'elasticsearch':
          manage_repo => true,
          repo_version => '1.7',
          autoupgrade => true,
        }
          elasticsearch::instance { 'es-01': }

 curl localhost:9200
{
  "status" : 200,
  "name" : "app1-es-01",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.5",
    "build_hash" : "2aaf797f2a571dcb779a3b61180afe8390ab61f9",
    "build_timestamp" : "2015-04-27T08:06:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

**Comment by bastelfreak** [comment]
Have you restarted elasticsearch after the upgrade? I think the module doesn't do it by itself.

**Comment by electrical** [comment]
Hi,

Only when setting the version number it will process the upgrade correctly.
because with the auto upgrade it sets it to latest but never changes the ensure value. Due this it doesn't notify the service.

**Comment by BurningTheSky** [comment]
Ok, I have changed the config to below, how to I force the update? I tried to stop the service but says it can't find it? Sorry, like I said, new to puppet and ES

      class { 'elasticsearch':
          manage_repo => true,
          repo_version => '1.7',
          version => '1.7.1',
        }
          elasticsearch::instance { 'es-01': }

**Comment by electrical** [comment]
Hi,

The service would be called 'elasticsearch-es-01'

**Comment by BurningTheSky** [comment]
Perfect! Thanks for your help!
