### ISSUE TITLE
ES_HEAP_SIZE needs to be parameterised

### ISSUE THREAD

**Issue by aman-ttc** [elastic/puppet-elasticsearch#422]
Currently, the class provides no way to set `ES_HEAP_SIZE` value.

At the same time, [ES documentation on heap size] (https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html) states:

> The default installation of Elasticsearch is configured with a 1 GB heap. For just about every deployment, this number is far too small. If you are using the default heap values, your cluster is probably configured incorrectly.

I can provide a PR if you confirm that this should be fixed.

**Comment by electrical** [comment]
Hi you can use the init_defaults setting for that.

**Comment by aman-ttc** [comment]
Ah, right, thanks
