### ISSUE TITLE
Yum dependency not mentioned in README

### ISSUE THREAD

**Issue by jantman** [elastic/puppet-elasticsearch#439]
The Readme file has a [section](https://github.com/elastic/puppet-elasticsearch#repository-management) specific to "Repository management" requirements, but this doesn't include ceritsc/yum which is required for the ``yum::versionlock`` define. This is triggered when ``elasticsearch::package_pin`` is true, which is the _default_.

This dependency should be listed in the README.

**Comment by electrical** [comment]
thank you for reporting this.
I'll add it before doing a release.

In the master branch btw the module is a required dependency so gets pulled in automatically.

**Comment by jantman** [comment]
cool, thanks.

That only works for people who are modern and using ``pmt`` or something else that includes dependency resolution (i.e. not people who are building a Puppetfile by hand, or maintaing a git repo of modules).

**Comment by electrical** [comment]
Ah very good point. Will include it.

**Comment by electrical** [comment]
its included in the 0.9.9 release, hope its better now?

**Comment by jantman** [comment]
Yes, thanks!
