### ISSUE TITLE
OpenSuse fails package removal

### ISSUE THREAD

**Issue by electrical** [elastic/puppet-elasticsearch#444]
Error: Parameter ensure failed on Package[elasticsearch]: Provider must have features 'purgeable' to set 'ensure' to 'purged' at /etc/puppet/modules/elasticsearch/manifests/package.pp:184

**Comment by tylerjl** [comment]
Closed in 3dd631455 - unfortunately, can't purge on OpenSuse due to no providers exposing that feature.
