### ISSUE TITLE
Add ability to install entire scripts directory

### ISSUE THREAD

**Issue by jsnod** [elastic/puppet-elasticsearch#449]
I have about 30+ groovy scripts I need to install, and it would be nice to be able to install an entire directory of scripts all at once instead of individually 1-by-1 using `elasticsearch::script`.  It's a maintenance/readability nightmare maintaining them all individually.  Here is how I'm currently doing it outside of the scope of puppet-elasticsearch:

```
file {
  'myScripts':
    ensure  => directory,
    mode    => '0644',
    owner   => elasticsearch,
    group   => elasticsearch,
    path    => '/etc/elasticsearch/scripts',
    # ignore all 'dot' files, eg: .swp
    ignore  => '.*',
    recurse => true,
    source  => 'puppet:///path/to/my/scripts_directory',
    require => [
        Package['elasticsearch'],
        User['elasticsearch']
    ];
}
```

Ideally we could do something like this in puppet-elasticsearch:

```
elasticsearch::script { 'myScripts':
  ensure => 'directory',
  source => 'puppet:///path/to/my/scripts_directory'
}
```

I took a look at `script.pp` and it looks like we could add `directory` as a valid parameter value, and then add the `recurse => true` attribute to the `file` type to make this work.  I'll try to work on a PR if I get some time, but wanted to file this in the meantime in case someone else has some bandwidth to take this on.

**Comment by electrical** [comment]
Hi,

This defo makes sense indeed.
I can make some time for it this week. Will ping you here when i got a PR up.

**Comment by bflad** [comment]
Sort of related - we currently bundle our 100+ scripts into an artifact release (tgz/zip) then deploy them that way since it'd obviously be quite difficult to manage them all in Puppet individually. It'd be awesome if we could point the scripts at an archive URL, much like how plugin operates, although I do understand this might fall outside the "normal" utility for this module.

**Comment by electrical** [comment]
@bflad i will certainly look at the different options how we can deploy them in the best way.

**Comment by electrical** [comment]
Just a heads up.
I'm planning to add the directory option as a source.
having a tar file as source is a step to far at the moment @bflad i'm afraid you'll have to insert your own logic for that.
