### ISSUE TITLE
Puppet Module Build Failing

### ISSUE THREAD

**Issue by bobstrecansky** [elastic/puppet-elasticsearch#451]
Just wanted to open up an issue saying that this puppet module build is failing according to:
https://forge.puppetlabs.com/elasticsearch/elasticsearch

**Comment by electrical** [comment]
Hi, thank you for informing me. I am aware of that yeah. I still need to remove the travis-ci build badge since i don't use it any more.
We are using our own CI infrastructure at http://build-eu-00.elastic.co/view/Puppet/view/Elasticsearch%20New/
