### ISSUE TITLE
main config and instance config are not deep merged

### ISSUE THREAD

**Issue by electrical** [elastic/puppet-elasticsearch#456]
See https://github.com/azhurbilo/puppet-elasticsearch/commit/d2be8b55a9dbd643b9bbf27e6c577391970ba929 for details.

**Comment by bflad** [comment]
This would help DRY up our configurations across various clusters. :+1:

**Comment by electrical** [comment]
Been looking into this further and it breaks current behaviour.
Not sure if I just should break it or have a flag for normal or deep merge the config hash?
Any idea's?

**Comment by tylerjl** [comment]
Should be functional as of #656.
