### ISSUE TITLE
Don't force puppet:// resource only

### ISSUE THREAD

**Issue by electrical** [elastic/puppet-elasticsearch#462]
I haven't heard any complaints yet but should double check we don't force any resources to `puppet:///` only.

**Comment by philipwigg** [comment]
I think it's still okay to use `puppet:///` URLs using a masterless setup?

https://github.com/jordansissel/puppet-examples/tree/master/masterless

**Comment by electrical** [comment]
This issue came from https://discuss.elastic.co/t/use-files-in-source-for-logstash-puppet-submodule/32145 & https://github.com/elastic/puppet-logstash/pull/205

So i'm not 100% sure anymore :-)

**Comment by philipwigg** [comment]
That first link just redirects back to https://discuss.elastic.co/ for me.

The second one is talking about a ```file://``` resources though, not ```puppet:///``` which I guess is a bit different?

**Comment by electrical** [comment]
@philipwigg in the case of the PR, i check if the resource given starts with `puppet://` and don't allow anything else like `file://` which is a bad thing it seems :-)
Perhaps i should reword the title :p

**Comment by philipwigg** [comment]
It might be that has the wrong end of the stick but I think https://github.com/elastic/puppet-logstash/pull/205 is based on a misunderstanding.

AFAIK, ```puppet:///``` URLs work fine using a masterless setup. The puppet agent gets the files from the local copy of the module if you're running ```puppet apply``` instead of fetching it from the master.

**Comment by electrical** [comment]
Most likely yeah. I think its good not to force puppet only resources anyway and allow for local file resources.

**Comment by philipwigg** [comment]
Sorry I see what you mean now.

This is for retrieving files that live outside of modules.

Yes, in that case, you should allow a ```file://``` URL which is valid.

**Comment by electrical** [comment]
Closing since https://github.com/elastic/puppet-elasticsearch/pull/470 is merged.
