### ISSUE TITLE
Better example for init defaults file

### ISSUE THREAD

**Issue by electrical** [elastic/puppet-elasticsearch#466]
https://github.com/elastic/puppet-elasticsearch#defaults-file

Use ES_HEAP_SIZE as example instead of the ES_USER/ES_GROUP options.

**Comment by bastelfreak** [comment]
In my opinion, all three options are heavily used so they all should be mentioned in the docs as examples.

**Comment by electrical** [comment]
@bastelfreak the user/group part is handled via other variables which in turn sets the correct ES_USER/ES_GROUP options.
This makes it a bit confusing to leave it in for this specific example.
I should add an other example how to run it as an other user i guess.
