### ISSUE TITLE
How can we adjust ES_HEAP_SIZE?

### ISSUE THREAD

**Issue by stwomack** [elastic/puppet-elasticsearch#469]
We would like to up the default ES_HEAP_SIZE, but the template doesn't account for changing it. Is there another way we can configure it using this module? We're getting the defaults, which are not working well for us:

/usr/bin/java -Xms256m -Xmx1g

**Comment by electrical** [comment]
Hi,

You can use the init_defaults hash like this:

```puppet
class { 'elasticsearch':
  init_defaults => { 'ES_HEAP_SIZE' => '4g' }
}
```

**Comment by stwomack** [comment]
Ahh, I missed that. Thank you; it worked great!
