### ISSUE TITLE
Elasticsearch 2 support

### ISSUE THREAD

**Issue by devopsprosiva** [elastic/puppet-elasticsearch#471]
Hi,

Is this module tested with elastic search 2 and kibana 4?

Siva

**Comment by electrical** [comment]
Hi,

about 95% of the features work with ES 2.0 yeah.
Only plugin installation via an url doesn't work at the moment and looking for a solution on that.

**Comment by electrical** [comment]
FYI, i also do integration testing against the 2.0 snapshot packages at http://puppet.ci.elastic.co/view/Elasticsearch/job/puppet-elasticsearch-integration-2x/

If you have any questions around the testing I do don't hesitate to open an issue.

**Comment by igalic** [comment]
https://github.com/elastic/puppet-elasticsearch/pull/477

**Comment by electrical** [comment]
#477 has been merged and will be doing a release this week.
