### ISSUE TITLE
ES 2.0: es.default.config is no longer supported

### ISSUE THREAD

**Issue by jecnua** [elastic/puppet-elasticsearch#472]
Connected to this issue: https://github.com/elastic/elasticsearch/issues/14347

I am getting the following entry in the log:
[2015-10-29 11:03:04,921][INFO ][bootstrap                ] es.default.config is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed.

Puppet is run with by this module:
-Des.default.config=/my/path/elasticsearch.yml

I am using version 0.9.9.

**Comment by electrical** [comment]
hi,

Yeah this will be fixed in the next version ( 0.9.10 ) which will be compat with ES 2.0
I'm trying to do a release either today or tomorrow, or early next week.

**Comment by jecnua** [comment]
Thank you! :)

**Comment by igalic** [comment]
ping @electrical

**Comment by ltutar** [comment]
nice

**Comment by igalic** [comment]
https://github.com/elastic/puppet-elasticsearch/pull/477

**Comment by fennnec** [comment]
+1

**Comment by electrical** [comment]
I'm working with @igalic on #477 to get it in a good state to get it merged and can do a release.

**Comment by electrical** [comment]
#477 has been merged, doing a release this week.

**Comment by tbarbugli** [comment]
@electrical was a patch released?

**Comment by electrical** [comment]
@tbarbugli I'm afraid not yet. There were several other issues that needed to be solved like #507 for 2.x
I'm working hard to do a release today.

**Comment by electrical** [comment]
@tbarbugli just released 0.10.0 with the patch.
