### ISSUE TITLE
By default localhost:9200 should be used as host but it is not the case

### ISSUE THREAD

**Issue by ltutar** [elastic/puppet-elasticsearch#473]
According to README.MD:
Host
By default it uses localhost:9200 as host. you can change this with the host and port variables

But when I install elasticsearch with the following yaml:
elasticsearch::java_install: false
elasticsearch::package_url: 'file:/vagrant/salt/states/puppetmaster/files/elk-external-resources/elasticsearch-1.7.3.noarch.rpm'
elasticsearch::instances:
  'es-01':
    'config':
      'node.name': ${HOSTNAME}

I can reach elasticsearch from an another machine through its IP address.

[root@puppetmaster ~]# wget http://192.168.234.73:9200/
--2015-10-29 19:55:43--  http://192.168.234.73:9200/
Connecting to 192.168.234.73:9200... connected.
HTTP request sent, awaiting response... 200 OK
Length: 336 [application/json]
Saving to: ‘index.html’

100%[============================================================================================================================================================================================>] 336         --.-K/s   in 0s      

2015-10-29 19:55:43 (74.5 MB/s) - ‘index.html’ saved [336/336]

[root@puppetmaster ~]# cat index.html 
{
  "status" : 200,
  "name" : "elkagent",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.3",
    "build_hash" : "05d4530971ef0ea46d0f4fa6ee64dbc8df659682",
    "build_timestamp" : "2015-10-15T09:14:17Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
[root@puppetmaster ~]# 

Is this a bug?

**Comment by ltutar** [comment]
this is part of kibana.yml

[root@elkagent config]# cat kibana.yml 
# Kibana is served by a back end server. This controls which port to use.
port: 5601

# The host to bind the server to.
host: "0.0.0.0"

# The Elasticsearch instance to use for all your queries.
elasticsearch_url: "http://localhost:9200"

# preserve_elasticsearch_host true will send the hostname specified in `elasticsearch`. If you set it to false,
# then the host you use to connect to *this* Kibana instance will be sent.
elasticsearch_preserve_host: true

# Kibana uses an index in Elasticsearch to store saved searches, visualizations
# and dashboards. It will create a new index if it doesn't already exist.
kibana_index: ".kibana"

**Comment by electrical** [comment]
Hi,

In all the examples i use localhost indeed but the module doesn't change what the defaults are for Elasticsearch it self.
By default for the 1.x releases is bounds to 0.0.0.0
Starting with ES 2.0 its bound to localhost by default.

Hope this clarifies it a bit.

**Comment by ltutar** [comment]
Definitely. Thank you very much for the explanation.
