### ISSUE TITLE
ES 2.0 CentOS repo is 2.x not 2.0

### ISSUE THREAD

**Issue by packplusplus** [elastic/puppet-elasticsearch#475]
Documented [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html)

0.9.9 defaults to the latest 1.7. If you want to use ES2, you have to have different settings for the repo_version. I dunno if to file this as a bug, or just have it here as note to anyone trying to 2.0 working with 0.9.9 on centos. The config that got me there...

```
class { 'elasticsearch':
  java_install  => true,
  manage_repo   => true,
  repo_version  => '2.x',
  autoupgrade   => true,
}
```

Could be fixed in 0.9.10

**Comment by electrical** [comment]
Hi,

The 2.x instead of 2.0 naming is caused by the new repo structure.
The Auto upgrade is something i try to avoid. If you do want to have it upgrade to the latest 2.x version then i usually set something like `version => '2.0.0'` which will pin it to that specific version and if you are running a lower version it will do the upgrade.

With autoupgrade it will do an upgrade whenever a new release is done, which in general is a bad practice.

**Comment by packplusplus** [comment]
I tried pinning the version before opening the issue. Wasn't working
because
http://packages.elastic.co/elasticsearch/2.0/centos/repodata/repomd.xml
wasn't responding. Looks like they must have added an alias, because that
url now works, and auto upgrade brings you to 2.0.

Autoupgrade for the dev cluster that tests out puppet / builds. In prod, I
agree, really bad idea.

On Mon, Nov 2, 2015 at 8:00 AM, Richard Pijnenburg <notifications@github.com
> wrote:

> Hi,
>
> The 2.x instead of 2.0 naming is caused by the new repo structure.
> The Auto upgrade is something i try to avoid. If you do want to have it
> upgrade to the latest 2.x version then i usually set something like version
> => '2.0.0' which will pin it to that specific version and if you are
> running a lower version it will do the upgrade.
>
> With autoupgrade it will do an upgrade whenever a new release is done,
> which in general is a bad practice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/puppet-elasticsearch/issues/475#issuecomment-153010180>
> .
>



-- 
* Patrick **Flaherty  *|
* w:*      *e:* patrick.flaherty@weather.com

**Comment by electrical** [comment]
Hm, if you set repo_version to 2.x and version to 2.0.0 it should upgrade fine.
Can you validate if that works or not?

**Comment by packplusplus** [comment]
That def works. You can get away with repo_version 2.0 now because the
mirrors respond on that pathing as well.

On Mon, Nov 2, 2015 at 11:05 AM, Richard Pijnenburg <
notifications@github.com> wrote:

> Hm, if you set repo_version to 2.x and version to 2.0.0 it should upgrade
> fine.
> Can you validate if that works or not?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/puppet-elasticsearch/issues/475#issuecomment-153063266>
> .
>



-- 
* Patrick **Flaherty  *|
* w:*      *e:* patrick.flaherty@weather.com

**Comment by packplusplus** [comment]
I'm going to close this, it was an issue with how ES had the repo setup, but now that 2.0 works, there's no real reason to fix / tweak anything.

**Comment by electrical** [comment]
Hi,

Just a note about this.. the 2.0 folder shouldn't be used as its not being updated and will be removed. Unsure why this was ever created.
You should use the 2.x url.
Sorry for the confusion.
