### ISSUE TITLE
Inheriting config from class causes duplicate hostname. 

### ISSUE THREAD

**Issue by packplusplus** [elastic/puppet-elasticsearch#478]
Inheriting config from class causes duplicate hostname. 

```
class { 'elasticsearch':
    config        => {
      'node.name'                          => 'hosta',
      'cluster.name'                       => 'test',
}

elasticsearch::instance { 'hosta': }
```
results in an es yaml with `node.name: hosta-hosta`
```
class { 'elasticsearch':
    config        => {
      'cluster.name'                       => 'test',
}

elasticsearch::instance { $hostname:
  config        => {'node.name' => $hostname }
}
```
results in an es yaml with `node.name: hosta`

**Comment by electrical** [comment]
Hi,

I'll have to dig deeper if this is an actual bug or not.
But for the `node.name` parts:
1. When no `node.name` is specifiedin the instance config we take the following: `hostname-instancename` as the resulting `node.name` part.
2. If a `node.name` is specified in the instance config we use that.

The `node.name` at the class level is ignored so there is no accidental node name conflict.

**Comment by electrical** [comment]
Did some more digging and its expected behaviour so far.
If no `node.name` is given on the instance config level we automatically default to `$::hostname-$instance_name`
Because of that you get the duplicate name.

**Comment by packplusplus** [comment]
:+1: 

Maybe the original purpose make have been to "prefix" or "suffix" all the node names in the cluster. That makes some sense. Thank you!
