### ISSUE TITLE
debian repo key too short

### ISSUE THREAD

**Issue by richardrasu** [elastic/puppet-elasticsearch#480]
Hi,

We see the following message in our puppet logs: Add key: D88E42B4 from Apt::Source elasticsearch]) The id should be a full fingerprint (40 characters), see README.

In the case of elasticsearch, the full fingerprint should be: 46095ACC8548582C1A2699A9D27D666CD88E42B4

Would it be possible for you to update the manifest (repo.pp), or do you require us to fork & PR?

Cheers

Richard

**Comment by electrical** [comment]
Hi,

This is a known issue but because I'm still supporting Puppet Enterprise 3.7.x which runs with an older pl-apt version i'm unable to update it to use the longer fingerprint.

**Comment by richardrasu** [comment]
OK, thanks for the quick response. I understand your predicament :(
Cheers,

R.
