### ISSUE TITLE
new issue - never had before -- centos 6.7 - init.d service not created (using 0.9.8)

### ISSUE THREAD

**Issue by SteveDevOps** [elastic/puppet-elasticsearch#482]
I have a new problem going on I've never experienced before. Stood up some new VMs to create a new cluster using this module. Everything is getting created accept the init.d instance service. 

I'm using 0.9.8 module
PE 2015.2
ES 1.4.2
CentOS 6.7 64bit

no /etc/init.d/elasticsearch-[instance name] is getting created.. everything goes fine with puppet run, no visible errors. I've had mirrored setup without issues. 

So to try and bypass puppet altogether I tried to copy the service script from another box that works, edited it to match new instance name, and installed it as a new service under chkconfig. And when I tried to run it.. I get invalid runuser option --pidfile. Is this a sign that I am missing some update? Yum says I have none.

Here's  a copy of most recent run... you can see where it deletes the default init.d -- which is expected, but never creates the new init.d script with instance name:

http://pastebin.com/L3J1vqAi

**Comment by SteveDevOps** [comment]
I tried a brief test upgrading to 0.9.9.. no change.

**Comment by SteveDevOps** [comment]
Ok found the prob.. I had copied over a manifest from another environment and repurposed it. I had left in status => 'unmanaged' in the main ES class -- probably because I was testing something at one point in that other environment. So to those who are unfamiliar, this means don't generate an init.d service! ARGH!!!! Lost a day to that stupid line. Derp!

**Comment by electrical** [comment]
@SteveDevOps thanks for the issue and great you found it.
I guess the result was unexpected.
Would it be better if the init file did get created but the service would not be enabled & started?

**Comment by SteveDevOps** [comment]
My suggestion would be to leave it be but provide a heads up. What about providing reminders / unmanaged state warnings ?  Especially if new install is occurring?

**Comment by electrical** [comment]
I'll certainly add some documentation around it yeah. Will have to think about any warnings though.
