### ISSUE TITLE
es_facts.rb timeout

### ISSUE THREAD

**Issue by swizzley** [elastic/puppet-elasticsearch#487]
I had 1 of 10 nodes configured with this module, using the RPM package on EL6.4, where facter -p failed. Stopping the Elasticsearch instance service allowed the fact to finish. I suspect the bug is when the service is running but cannot connect to a master. I'm running the HQ plugin, on ver 1.7.1

/usr/lib/ruby/1.8/timeout.rb:64:in `rbuf_fill': execution expired (Timeout::Error)
	from /usr/lib/ruby/1.8/net/protocol.rb:134:in `rbuf_fill'
	from /usr/lib/ruby/1.8/net/protocol.rb:116:in `readuntil'
	from /usr/lib/ruby/1.8/net/protocol.rb:126:in `readline'
	from /usr/lib/ruby/1.8/net/http.rb:2028:in `read_status_line'
	from /usr/lib/ruby/1.8/net/http.rb:2017:in `read_new'
	from /usr/lib/ruby/1.8/net/http.rb:1051:in `request'
	from /usr/lib/ruby/1.8/net/http.rb:1037:in `request'
	from /usr/lib/ruby/1.8/net/http.rb:543:in `start'
	from /usr/lib/ruby/1.8/net/http.rb:1035:in `request'
	from /usr/lib/ruby/1.8/net/http.rb:772:in `get'
	from /var/lib/puppet/lib/facter/es_facts.rb:51:in `run'
	from /var/lib/puppet/lib/facter/es_facts.rb:44:in `each'
	from /var/lib/puppet/lib/facter/es_facts.rb:44:in `run'
	from /var/lib/puppet/lib/facter/es_facts.rb:99
	from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:130:in `load'
	from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:130:in `kernel_load'
	from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:115:in `load_file'
	from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:49:in `load_all'
	from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:47:in `each'
	from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:47:in `load_all'
	from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:45:in `each'
	from /usr/lib/ruby/site_ruby/1.8/facter/util/loader.rb:45:in `load_all'
	from /usr/lib/ruby/site_ruby/1.8/facter/util/collection.rb:104:in `load_all'
	from /usr/lib/ruby/site_ruby/1.8/facter.rb:126:in `to_hash'
	from /usr/lib/ruby/site_ruby/1.8/facter/application.rb:46:in `run'
	from /usr/bin/facter:20

**Comment by electrical** [comment]
Oh, interesting I'll have a look at this asap.

**Comment by tylerjl** [comment]
Tried to reproduce this on CentOS 6 but couldn't get it to stall - if this is still acting up, please do attach steps to reproduce and I'll be happy to take a look and try to resolve it. Otherwise I think the timeout settings in the GET should be working.
