### ISSUE TITLE
ES 2.0 plugin does not use --url to install

### ISSUE THREAD

**Issue by thenom** [elastic/puppet-elasticsearch#492]
```
Error: /usr/share/elasticsearch/bin/plugin install elasticsearch/shield/latest --url file:///tmp/shield-2.0.0.zip returned 64 instead of one of [0,1]
Error: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[elasticsearch/shield/latest]/Exec[install_plugin_elasticsearch/shield/latest]/returns: change from notrun to 0 1 failed: /usr/share/elasticsearch/bin/plugin install elasticsearch/shield/latest --url file:///tmp/shield-2.0.0.zip returned 64 instead of one of [0,1]
```

Manually running the command:

```
[root@pup-esnode01 ~]# /usr/share/elasticsearch/bin/plugin install elasticsearch/shield/latest --url file:///tmp/shield-2.0.0.zip
ERROR: Unrecognized option: --url
```

**Comment by electrical** [comment]
Hi,

I'm working on making the module work with ES 2.x :-)
The initial try to make it work lacked some logic to handle ES 1.x and 2.x so working on a better implementation.

Hopefully i'll have this solved soon.

**Comment by thenom** [comment]
Brilliant!  Looking forward to trying it out :)

**Comment by ntent-ashton** [comment]
Came here to open a ticket on this - glad to see it's been raised already.  I've modified the module for now, and I'll subscribe to this issue for resolution.

**Comment by eperdeme** [comment]
It's also worth noting on V2 plugins you can not specify the version for official plugins.

So in the readme the following is invalid.

https://github.com/elastic/puppet-elasticsearch#plugin-name-could-be
elasticsearch/plugin/version for official elasticsearch plugins (download from download.elasticsearch.org)

**Comment by electrical** [comment]
PR https://github.com/elastic/puppet-elasticsearch/pull/507 should solve the plugin installation issues.
Documentation i'll fix via an other PR.

**Comment by Oyabi** [comment]
Hi,
Have you a release date for the module compatible with elasticsearch 2?
Thank you.

**Comment by electrical** [comment]
@Oyabi hoping to do the release today or tomorrow.

**Comment by Oyabi** [comment]
Ok cool ^^
Thank you.

**Comment by xaniasd** [comment]
+1

**Comment by kjelle** [comment]
+1

**Comment by anderssynstad** [comment]
+1

**Comment by walterheck** [comment]
@electrical is that still "today or tomorrow"? Could very much use a working module for 2.x

**Comment by electrical** [comment]
Sorry for the delay. had some issues with the plugin code which i finally solved. I'm targeting for today if i get everything merged and updated.

**Comment by electrical** [comment]
0.10.0 is released with a fix for this. Enjoy!

**Comment by Oyabi** [comment]
Thank you ;)
