### ISSUE TITLE
Error installing marvel plugin when java is installed in /usr/local/sbin

### ISSUE THREAD

**Issue by ryreitsma** [elastic/puppet-elasticsearch#493]
I am trying to install the latest marvel plugin:

```puppet
elasticsearch::plugin{'elasticsearch/marvel/latest':
    instances  => $instances,
    url        => 'https://download.elasticsearch.org/elasticsearch/marvel/marvel-latest.zip',
  }
```
and I am getting the error "Error: which: no java in (/bin:/usr/bin:/usr/local/bin)" when running this module. It seems that the puppet module used to install an Oracle java SDK (https://github.com/tylerwalts/puppet-jdk_oracle) creates a link to java in /usr/local/sbin and the plugin code does not include this directory:

```puppet
Exec {
    path      => [ '/bin', '/usr/bin', '/usr/local/bin' ],
    cwd       => '/',
    user      => $elasticsearch::elasticsearch_user,
    tries     => 6,
    try_sleep => 10,
    timeout   => 600,
  }
```

Is it an option to add '/usr/sbin' and '/usr/local/sbin' to the path definition as well? I think those directories are valid for these cases. I would be happy to do a pull request for this.

**Comment by electrical** [comment]
Hi,

If adding that path solves your issue i'm happy to receive a PR for that :-)

Cheers.
