### ISSUE TITLE
Failing dependency to datacat

### ISSUE THREAD

**Issue by sloba88** [elastic/puppet-elasticsearch#498]
I am using this repo together with Vagrant provisioning to generate environment and it was working until I did update couple of days ago.

The problem I get now is 
``` Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type datacat at /tmp/vagrant-puppet/modules-3b4d52a2bc511f3d244fe82c3cf92a80/elasticsearch/manifests/instance.pp:287 ```

Which means that datacat library is missing.

Since I am new with puppet I am wondering should it pull this library automatically or should I do it? I tried putting it to Vagrant modules manually but it doesn't load it.

Where should I put this library in order for install script to find it? Any ideas?

**Comment by sloba88** [comment]
Ok I get that this has to do with Vagrant provision loading order probably, this is not correct place to ask.

**Comment by philipwigg** [comment]
The Elasticsearch Puppet module requires the datacat module as you say.

You can find a list of the module dependencies in the ```metadata.json``` file in the root directory.

The dependent modules need to be placed in your 'modules' directory (same the Elasticsearch module does).
