### ISSUE TITLE
when using 'unmanaged' for service, the init script is not installed

### ISSUE THREAD

**Issue by VuokkoVuorinnen** [elastic/puppet-elasticsearch#499]
Is there a particular reason why the init script isn't installed when using status=unmanaged (I'm using pacemaker to manage the elasticsearch service)?

**Comment by electrical** [comment]
Hi,

This same issue was reported via https://github.com/elastic/puppet-elasticsearch/issues/482
I think indeed i should install the init script but not enable it.
I hope to have this solved for the next version.

**Comment by eperdeme** [comment]
Weirdly, I was looking at this today as we have the same issue of wanting
rundeck/jenkins to control the rolling upgrades but still using the init
script/

Glad to see it might be changed in the next release.

**Comment by VuokkoVuorinnen** [comment]
in manifests/service/init.pp (and systemd.pp), removing the 'status != unmanaged' from ' if ( $status != 'unmanaged' and $ensure == 'present' )' seems to solve the problem. Not sure if there's anything that might break. Can I run some tests before making a PR?

**Comment by electrical** [comment]
You can always run `bundle install` and `bundle exec rake spec`
That's for the unit tests.
Don't think i have acceptance tests for the unmanaged part.

The unit tests may fail though but since its a fairly unused feature we can change it without causing to much harm I would think.
