### ISSUE TITLE
Apt module version dependency

### ISSUE THREAD

**Issue by dcroonen** [elastic/puppet-elasticsearch#505]
Hi all

The apt module version dependency for the moment is 1.8.0 while the current apt version is 2.2.0. Is there any progress on this one? 

Kind regards

**Comment by bastelfreak** [comment]
Hi,

please take a look [here](https://github.com/elastic/puppet-elasticsearch/pull/504#issuecomment-159901161).

**Comment by electrical** [comment]
@dcroonen the new release will support pl-apt 2.x

**Comment by dcroonen** [comment]
Great! Somebody any idea when this new release will become available?

**Comment by electrical** [comment]
I'm planning to do a release tomorrow unless anything crops up today.

**Comment by jlyheden** [comment]
Would be great if this version could be uploaded to the Puppet forge

**Comment by electrical** [comment]
@jlyheden I'm trying to do a release today which also includes multiple fixes for ES 2.x

**Comment by electrical** [comment]
0.10.0 is released with a fix for this. Enjoy!
