### ISSUE TITLE
Custom restart command for Elasticsearch service

### ISSUE THREAD

**Issue by krzyzakp** [elastic/puppet-elasticsearch#506]
We're using heavily Elasticsearch cluster on production, with many nodes and this code to manage everything via puppet. Sometimes we have to change our configuration, what right now is not possible in automated way without downtime, as nodes are restarted randomly and it often happen on big clusters, that most of nodes is going down at same time, bringing cluster into red status.

We have some ideas to fix it, as we install already plugins in safe way, but current state of module don't allow us to to it. Easiest idea is to just add param restart to service of elasticsearch and handle rest on our side. 
For this I already forked and make those changes, as it's just few lines. You can check it here if you're not sure about what i write: https://github.com/elastic/puppet-elasticsearch/compare/master...krzyzakp:master

**Comment by electrical** [comment]
Hi,

could you give an example of how you would use that variable?

**Comment by krzyzakp** [comment]
Idea was quite simple for this case, we would put into restart easy command like: `touch /var/lib/puppet/state/safe_elasticsearch_restart.lock`. Tthan in our puppet code add rule, which would restart node in cluster in safe way, something like:
```Puppet
Exec { "restart_ES_safe_way":
  command => "/etc/init.d/elasticsearch restart",
  onlyif => "/usr/bin/curl -s -XGET 'http://${::ipaddress}:${es_port}/_cluster/health?pretty=true' | grep status | grep -q green",
}
```
Similar exec we use when installing plugins to ES, to make it without downtime.

**Comment by krzyzakp** [comment]
@electrical any update on it?

**Comment by electrical** [comment]
I've been looking into this a bit closer now. sorry for the delay.
What i don't like is that you are defaulting the restart to null which i think breaks current behaviour.
If you don't want the module to do restarts you can set the `restart_on_change` option to false which doesn't do any restart actions.
Then you are able to implement your own restart method after that.
Would that be sufficient enough?

**Comment by krzyzakp** [comment]
Yes, it's more than sufficient for us! We'll simply enable it. and whenever change config files use puppet built-in notify to launch our gracefull restart node by node. 
Thanks for suggesting it, I have no idea, why I skipped it when digging in documentation.

**Comment by electrical** [comment]
@krzyzakp no worries at all :-) shows i need to improve documentation ;-)
