### ISSUE TITLE
repo url wrong

### ISSUE THREAD

**Issue by tobiasschaber** [elastic/puppet-elasticsearch#509]
Hey guys,

For me it seems that the repo url for yum packages which is used by default is not correct. 

It seems that the module tries to download the yum repo from "package.elastic.co/.... "

I can get it running if I use "download.elastic.co/..."

Could you please have a look if this may be a bug?

Kind regards,
Tobias

**Comment by electrical** [comment]
Hi,

package.elastic.co should work just fine.
Can you show the settings you used for the puppet module and what error you are getting?

**Comment by olliiiver** [comment]
Hi,

the repository URL seems to be dead for a few days now which renders the installation over puppet unusable.  

```
curl http://packages.elastic.co/elasticsearch/2.0/debian/dists/stable/main/binary-amd64/Packages
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>elasticsearch/2.0/debian/dists/stable/main/binary-amd64/Packages</Key><RequestId>C98177D4D12D722A</RequestId><HostId>lXjZ+7D/zso6I7df9Kf83QLbDzLun1PAIPhXDH9Nea1tGFu9lCwj5Nh6DPuK4il4krLR1Nvqvg8=</HostId></Error>
```

The latest repository URL works (http://packages.elastic.co/elasticsearch/2.x/debian/dists/stable/main/binary-amd64/Packages) but this version of Elasticsearch is not compatible with the puppet module.

**Comment by electrical** [comment]
I'll have a look at this Monday and update you.

**Comment by electrical** [comment]
Hi,

I just saw the issue.
If you set the repo_version to 2.x instead of 2.0 it works fine.

**Comment by olliiiver** [comment]
Hi @electrical, 2.0 installs 2.0.0-beta2, whereas 2.x installs some newer version. I tried this too, but ran into conflicts. The new Kibana version requires Elasticsearch 2.1 or later, so an update for the puppet module would be very helpful.

**Comment by electrical** [comment]
The module should be able to install 2.0.x and 2.1.x  fine when using 2.x as repo version.
Can you show me the conflicts you are getting?
Please don't use 2.0 as repo version as it shouldn't exist actually :-)

**Comment by Erikvv** [comment]
Perhaps you can document the "2.x" feature in the Readme or provide a better error message.

**Comment by olliiiver** [comment]
Hi. Is the puppet module now compatible with ES 2.1.1?

**Comment by electrical** [comment]
@olliiiver yes it is. make sure you use the latest version ( 0.10.2 )

@Erikvv the repo versioning changes is documented in the Elasticsearch breaking changes document See https://www.elastic.co/guide/en/elasticsearch/reference/2.x/breaking_20_plugin_and_packaging_changes.html#_repository_naming_structure_changes

**Comment by olliiiver** [comment]
Great! Thank you.

**Comment by Erikvv** [comment]
@electrical someone who installs elasticsearch with pupppet from scratch is not going to read the breaking changes, they will read the README.md

**Comment by electrical** [comment]
@Erikvv very true. I'll see what i can do about it.
