### ISSUE TITLE
Binding to the wrong IP

### ISSUE THREAD

**Issue by BurningTheSky** [elastic/puppet-elasticsearch#510]
Hi,
I am using the code below to start an instance but it appears to be binding to the 127. loopback IP rather than an external one, how can I change this? When I used 1.7.1 it wasn't doing that but now that I am using 2.1.0 it is, has something changed?

Thanks

        class { 'elasticsearch':
                manage_repo => true,
                repo_version => '2.x',
                version => '2.1.0',
                java_install => false,
        }
                elasticsearch::instance { 'instance1': }

**Comment by eperdeme** [comment]
>2.0.0 ES changed so it brings only to localhost.

elasticsearch::instance { $instance_name:
    config => {
      'network.bind_host'     => '0.0.0.0'
}

Something like that might help, but you'll also want to look
at network.publish_host

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html

**Comment by BurningTheSky** [comment]
bind_host worked perfectly! Thanks

**Comment by electrical** [comment]
Hi. With es 2.x it defaults to local host indeed. It's one of the changes listed.
