### ISSUE TITLE
Marvel Install

### ISSUE THREAD

**Issue by BurningTheSky** [elastic/puppet-elasticsearch#511]
Hey,
I'm sure I have done something very obviously wrong here but Marvel won't install, could anyone tell me where I have gone wrong?
Code:
          class { 'elasticsearch':
                 manage_repo => true,
                 repo_version => '2.x',
                 version => '2.1.0',
                 java_install => false,
         }
                 elasticsearch::instance { 'instance1':
                        config => {
                                'network.bind_host' => '0.0.0.0'
                                }
                 }

                elasticsearch::plugin{'elasticsearch/marvel/latest':
                        instances  => 'instance1',
                        url        => 'https://download.elasticsearch.org/elasticsearch/marvel/marvel-latest.zip',
                }

Errors:
Error: Could not find command '/usr/share/elasticsearch/bin/plugin'
Error: /Stage[main]/Main/Node[host1]/Elasticsearch::Plugin[elasticsearch/marvel/latest]/Exec[install_plugin_elasticsearch/marvel/latest]/returns: change from notrun to 0 1 failed: Could not find command '/usr/share/elasticsearch/bin/plugin'
Notice: /Stage[main]/Main/Node[host1]/Elasticsearch::Plugin[elasticsearch/marvel/latest]/File[/usr/share/elasticsearch/plugins/marvel/.name]: Dependency Exec[install_plugin_elasticsearch/marvel/latest] has failures: true
Warning: /Stage[main]/Main/Node[host1]/Elasticsearch::Plugin[elasticsearch/marvel/latest]/File[/usr/share/elasticsearch/plugins/marvel/.name]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[host1]/Elasticsearch::Instance[instance1]/Elasticsearch::Service[instance1]/Elasticsearch::Service::Init[instance1]/File[/etc/init.d/elasticsearch-instance1]: Dependency Exec[install_plugin_elasticsearch/marvel/latest] has failures: true
Warning: /Stage[main]/Main/Node[host1]/Elasticsearch::Instance[instance1]/Elasticsearch::Service[instance1]/Elasticsearch::Service::Init[instance1]/File[/etc/init.d/elasticsearch-instance1]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[host1]/Elasticsearch::Instance[instance1]/Elasticsearch::Service[instance1]/Elasticsearch::Service::Init[instance1]/Augeas[defaults_instance1]: Dependency Exec[install_plugin_elasticsearch/marvel/latest] has failures: true
Warning: /Stage[main]/Main/Node[host1]/Elasticsearch::Instance[instance1]/Elasticsearch::Service[instance1]/Elasticsearch::Service::Init[instance1]/Augeas[defaults_instance1]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[host1]/Elasticsearch::Instance[instance1]/Elasticsearch::Service[instance1]/Elasticsearch::Service::Init[instance1]/Service[elasticsearch-instance-instance1]: Dependency Exec[install_plugin_elasticsearch/marvel/latest] has failures: true
Warning: /Stage[main]/Main/Node[host1]/Elasticsearch::Instance[instance1]/Elasticsearch::Service[instance1]/Elasticsearch::Service::Init[instance1]/Service[elasticsearch-instance-instance1]: Skipping because of failed dependencies

**Comment by electrical** [comment]
This is another es 2.x change.  See https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking-changes-2.0.html for more details.

**Comment by BurningTheSky** [comment]
Thanks for the information, I am not very experienced with ES, would you mind explaining in practical terms what this change means for installing marvel through puppet? Thanks

**Comment by electrical** [comment]
Hi,

The module it self with regards to plugin installations isn't fully ready yet for 2.x
There were several changes that required a large rewrite for that.

I'm hoping to do a release this week to get it all working.

**Comment by BurningTheSky** [comment]
Ah, ok, for now I will get a manual install done. Thanks for the information, I look forward to the update.

**Comment by electrical** [comment]
https://github.com/elastic/puppet-elasticsearch/pull/507 will fix the plugin install issue. Hoping to have the tests pass by today.

**Comment by BurningTheSky** [comment]
Has the plugin changed passed or is this still in progress? Thanks

**Comment by electrical** [comment]
Its still in progress but finalizing the changes right now.. I'm expecting to merge the PR today

**Comment by BurningTheSky** [comment]
Cool, thanks for the update

**Comment by electrical** [comment]
0.10.0 is released with a fix for this. Enjoy!

**Comment by BurningTheSky** [comment]
Hey, thanks for the update, I am still having an issue though. The error says that it is failing to download the files, but if I do a wget on the url it works fine. Any ideas?

Code:
              elasticsearch::plugin{'elasticsearch/marvel/latest':
                       instances  => 'instance1',
                       url        => 'https://download.elastic.co/elasticsearch/marvel/marvel-1.3.1.zip',
               }

Error:
Error: Execution of '/usr/share/elasticsearch/bin/plugin install https://download.elastic.co/elasticsearch/marvel/marvel-1.3.1.zip' returned 70: -> Installing from https://download.elastic.co/elasticsearch/marvel/marvel-1.3.1.zip...
Trying https://download.elastic.co/elasticsearch/marvel/marvel-1.3.1.zip ...
Downloading ...........................................................................................................................DONE
Verifying https://download.elastic.co/elasticsearch/marvel/marvel-1.3.1.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip
Error: /Stage[main]/Main/Node[host]/Elasticsearch::Plugin[elasticsearch/marvel/latest]/Elasticsearch_plugin[elasticsearch/marvel/latest]/ensure: change from absent to present failed: Execution of '/usr/share/elasticsearch/bin/plugin install https://download.elastic.co/elasticsearch/marvel/marvel-1.3.1.zip' returned 70: -> Installing from https://download.elastic.co/elasticsearch/marvel/marvel-1.3.1.zip...
Trying https://download.elastic.co/elasticsearch/marvel/marvel-1.3.1.zip ...
Downloading ...........................................................................................................................DONE
Verifying https://download.elastic.co/elasticsearch/marvel/marvel-1.3.1.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by electrical** [comment]
@BurningTheSky when using ES 2.x you can't use that marvel version. You will need to use the one with the exact same version as ES it self.

**Comment by BurningTheSky** [comment]
Ah ok, I am getting a bit confused of the best config. If I use the code below, which I assume should get the right version, I get another error.

Code:
                elasticsearch::plugin{'elasticsearch/marvel/2.1.0': module_dir => 'marvel', instances  => 'instance1'}

Error:
Error: Execution of '/usr/share/elasticsearch/bin/plugin install elasticsearch/marvel/2.1.0' returned 74: -> Installing elasticsearch/marvel/2.1.0...
Trying https://download.elastic.co/elasticsearch/marvel/marvel-2.1.0.zip ...
Trying https://search.maven.org/remotecontent?filepath=elasticsearch/marvel/2.1.0/marvel-2.1.0.zip ...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/elasticsearch/marvel/2.1.0/marvel-2.1.0.zip ...
Trying https://github.com/elasticsearch/marvel/archive/2.1.0.zip ...
Trying https://github.com/elasticsearch/marvel/archive/master.zip ...
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information
Error: /Stage[main]/Main/Node[host]/Elasticsearch::Plugin[elasticsearch/marvel/2.1.0]/Elasticsearch_plugin[elasticsearch/marvel/2.1.0]/ensure: change from absent to present failed: Execution of '/usr/share/elasticsearch/bin/plugin install elasticsearch/marvel/2.1.0' returned 74: -> Installing elasticsearch/marvel/2.1.0...
Trying https://download.elastic.co/elasticsearch/marvel/marvel-2.1.0.zip ...
Trying https://search.maven.org/remotecontent?filepath=elasticsearch/marvel/2.1.0/marvel-2.1.0.zip ...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/elasticsearch/marvel/2.1.0/marvel-2.1.0.zip ...
Trying https://github.com/elasticsearch/marvel/archive/2.1.0.zip ...
Trying https://github.com/elasticsearch/marvel/archive/master.zip ...
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information

**Comment by electrical** [comment]
Ah i see now. Can you change the name to 'marvel' ?
They changed how official plugins are handled and only require the short name.
The version is automatically detected based on the ES version.
See https://www.elastic.co/guide/en/elasticsearch/plugins/current/installation.html#_core_elasticsearch_plugins for details.

**Comment by BurningTheSky** [comment]
Still no joy.

Code:
 elasticsearch::plugin{'elasticsearch/marvel': module_dir => 'marvel', instances  => 'instance1'}

Gives error:
Error: Execution of '/usr/share/elasticsearch/bin/plugin install elasticsearch/marvel' returned 74: -> Installing elasticsearch/marvel...
Trying https://github.com/elasticsearch/marvel/archive/master.zip ...
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information
Error: /Stage[main]/Main/Node[host]/Elasticsearch::Plugin[elasticsearch/marvel]/Elasticsearch_plugin[elasticsearch/marvel]/ensure: change from absent to present failed: Execution of '/usr/share/elasticsearch/bin/plugin install elasticsearch/marvel' returned 74: -> Installing elasticsearch/marvel...
Trying https://github.com/elasticsearch/marvel/archive/master.zip ...
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information

and code:
elasticsearch::plugin{'marvel': module_dir => 'marvel', instances  => 'instance1'}

Gives error:
Error: Execution of '/usr/share/elasticsearch/bin/plugin install marvel' returned 74: -> Installing marvel...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/marvel/2.1.0/marvel-2.1.0.zip ...
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information
Error: /Stage[main]/Main/Node[host]/Elasticsearch::Plugin[marvel]/Elasticsearch_plugin[marvel]/ensure: change from absent to present failed: Execution of '/usr/share/elasticsearch/bin/plugin install marvel' returned 74: -> Installing marvel...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/marvel/2.1.0/marvel-2.1.0.zip ...
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information

Wasn't sure which might be right

**Comment by BurningTheSky** [comment]
Should it be marvel agent in line with this url?
https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/marvel-agent/2.1.1/marvel-agent-2.1.1.zip

**Comment by electrical** [comment]
Ah sorry yeah. so many changes :-)

**Comment by BurningTheSky** [comment]
Making progress! That worked, using the agent parameter. It complained about there not being a license which is fair enough. I have the code below now and puppet ran fine with it but I still cant get to a marvel page using IP:5601/app/marvel, any thoughts?

elasticsearch::plugin{'marvel-agent': module_dir => 'marvel', instances  => 'instance1'}
elasticsearch::plugin{'license': module_dir => 'license', instances  => 'instance1'}

**Comment by electrical** [comment]
@BurningTheSky the marvel-agent part is only for the backend process to pull the data and index it. you will need the marvel web UI part for kibana to be able to view it.
Assuming you have installed that ( still working on kibana module btw ) then the kibana UI should work afaik.

**Comment by BurningTheSky** [comment]
Ah ok, thanks for your continued assistance with my issues @electrical!

**Comment by electrical** [comment]
You're very welcome. I'm closing this issue then.
