### ISSUE TITLE
Default JAVA_OPTS in elasticsearch.in.sh

### ISSUE THREAD

**Issue by aman-ttc** [elastic/puppet-elasticsearch#512]
`elasticsearch.in.sh` (`/usr/share/elasticsearch/bin/elasticsearch.in.sh` on Ubuntu 12.04) contains following JAVA_OPTS defaults:

```
JAVA_OPTS="$JAVA_OPTS -XX:+UseParNewGC"
JAVA_OPTS="$JAVA_OPTS -XX:+UseConcMarkSweepGC"
JAVA_OPTS="$JAVA_OPTS -XX:CMSInitiatingOccupancyFraction=75"
JAVA_OPTS="$JAVA_OPTS -XX:+UseCMSInitiatingOccupancyOnly"
```

It seems there is no way to disable them at the moment. This is causing issues when one wants to enable G1GC instead. How about making these defaults conditional?

**Comment by electrical** [comment]
Please open an issue in the elasticsearch repo it self since I can't fix this in the puppet module.
