### ISSUE TITLE
Latest snapshot (pre v0.9.10) and plugin 'royrusso/elasticsearch-HQ'

### ISSUE THREAD

**Issue by driegel** [elastic/puppet-elasticsearch#515]
Hi,

using the following with Elasticsearch 2.1 
```
        elasticsearch::plugin{'royrusso/elasticsearch-HQ':
                instances  => [ 'inst01' ],
        }
```
and the latest snapshot of the 'puppet-elasticsearch' puppet module causes the following error:
```
Notice: /Stage[main]/Myelasticsearch/Elasticsearch::Plugin[royrusso/elasticsearch-HQ]/Exec[install_plugin_royrusso/elasticsearch-HQ]/returns: executed successfully
Info: /Stage[main]/Myelasticsearch/Elasticsearch::Plugin[royrusso/elasticsearch-HQ]/Exec[install_plugin_royrusso/elasticsearch-HQ]: Scheduling refresh of Elasticsearch::Service[inst01]
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /usr/share/elasticsearch/plugins/HQ/.name20151209-21102-t00hj7.lock at 167:/etc/puppet/modules/elasticsearch/manifests/plugin.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /usr/share/elasticsearch/plugins/HQ/.name20151209-21102-t00hj7.lock at 167:/etc/puppet/modules/elasticsearch/manifests/plugin.pp
Wrapped exception:
No such file or directory @ dir_s_rmdir - /usr/share/elasticsearch/plugins/HQ/.name20151209-21102-t00hj7.lock
Error: /Stage[main]/Myelasticsearch/Elasticsearch::Plugin[royrusso/elasticsearch-HQ]/File[/usr/share/elasticsearch/plugins/HQ/.name]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /usr/share/elasticsearch/plugins/HQ/.name20151209-21102-t00hj7.lock at 167:/etc/puppet/modules/elasticsearch/manifests/plugin.pp
```

The plugin does actually install, however, the problem is uppercase/lowercase in the path '/usr/share/elasticsearch/plugins/HQ'

Priority: low

Thanks!

**Comment by electrical** [comment]
Hi,

This is something i found as well with my tests.  PR #507 will solve this problem as soon as i get everything working and tested :-)

**Comment by driegel** [comment]
By the way, the latest snapshot is now working for me with ES 2.1,

There is one problem I need to workaround for now:
'[::1]:9300'

This is beyond the realm of this issue.

**Comment by electrical** [comment]
@driegel that is with the pr added that I linked ?

**Comment by driegel** [comment]
@electrical I tested the plugin with the following commit on branch master (after 'git clone')
```
commit 0aa805a84c86c51c3cfa4023af45e09577705b68
Merge: b930ab8 af08d3e
Author: Richard Pijnenburg <richard@ispavailability.com>
Date:   Mon Dec 7 13:41:47 2015 +0000
```
Result: ERROR as written above.

**Comment by driegel** [comment]
@electrical The IPv6 thing I will test more and open as separate issue if needed. For now I feel we need a working module for ES 2.1 asap.

**Comment by electrical** [comment]
The current master branch should work fine for ES 2.x indeed except for the plugin install parts which should be solved with #507.
Once that is stable I can make a release.

**Comment by driegel** [comment]
Thank you for doing this, I appreciate that. I thought, PR #507 is an easy patch and I will try it but I was wrong.

**Comment by electrical** [comment]
Its quite a large change indeed and been working on it for a while now but getting very close.

**Comment by electrical** [comment]
0.10.0 is released with a fix for this. Enjoy!
