### ISSUE TITLE
elasticsearch-elasticsearch.service never wrote its PID file. Failing.

### ISSUE THREAD

**Issue by shreejit13** [elastic/puppet-elasticsearch#516]
getting following error on CentOS 7:

[root@elasticsearch log]# systemctl status elasticsearch-elasticsearch.service
elasticsearch-elasticsearch.service - Starts and stops a single elasticsearch instance on this system
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch-elasticsearch.service; enabled)
   Active: failed (Result: resources) since Thu 2015-12-10 18:36:29 UTC; 4min 47s ago
     Docs: http://www.elasticsearch.org
  Process: 15968 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -d -p /var/run/elasticsearch/elasticsearch-elasticsearch.pid -Des.default.config=$CONF_FILE -Des.default.path.home=$ES_HOME -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR (code=exited, status=0/SUCCESS)
 Main PID: 15760 (code=exited, status=1/FAILURE)

Dec 10 18:36:29 elasticsearch elasticsearch[15968]: at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
Dec 10 18:36:29 elasticsearch elasticsearch[15968]: at java.nio.file.Files.walkFileTree(Files.java:2602)
Dec 10 18:36:29 elasticsearch elasticsearch[15968]: at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:142)
Dec 10 18:36:29 elasticsearch elasticsearch[15968]: ... 4 more
Dec 10 18:36:29 elasticsearch elasticsearch[15968]: log4j:WARN No appenders could be found for logger (bootstrap).
Dec 10 18:36:29 elasticsearch elasticsearch[15968]: log4j:WARN Please initialize the log4j system properly.
Dec 10 18:36:29 elasticsearch elasticsearch[15968]: log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Dec 10 18:36:29 elasticsearch systemd[1]: elasticsearch-elasticsearch.service never wrote its PID file. Failing.
Dec 10 18:36:29 elasticsearch systemd[1]: Failed to start Starts and stops a single elasticsearch instance on this system.
Dec 10 18:36:29 elasticsearch systemd[1]: Unit elasticsearch-elasticsearch.service entered failed state.

Following system logs says it is not able to find $CONF_DIR :

Dec 10 18:36:28 localhost puppet-agent[15816]: (/Stage[main]/Profile::Elasticsearch/Elasticsearch::Instance[elasticsearch]/Elasticsearch::Service[elasticsearch]/Elasticsearch::Service::Systemd[elasticsearch]/File[/lib/systemd/system/elasticsearch-elasticsearch.service]) Scheduling refresh of Exec[systemd_reload_elasticsearch]
Dec 10 18:36:29 localhost systemd: Reloading.
Dec 10 18:36:29 localhost systemd: [/usr/lib/systemd/system/elasticsearch-elasticsearch.service:16] Failed to parse resource value, ignoring:
Dec 10 18:36:29 localhost puppet-agent[15816]: (/Stage[main]/Profile::Elasticsearch/Elasticsearch::Instance[elasticsearch]/Elasticsearch::Service[elasticsearch]/Elasticsearch::Service::Systemd[elasticsearch]/Exec[systemd_reload_elasticsearch]) Triggered 'refresh' from 1 events
Dec 10 18:36:29 localhost systemd: Reloading.
Dec 10 18:36:29 localhost systemd: [/usr/lib/systemd/system/elasticsearch-elasticsearch.service:16] Failed to parse resource value, ignoring:
Dec 10 18:36:29 localhost systemd: Starting Starts and stops a single elasticsearch instance on this system...
Dec 10 18:36:29 localhost systemd: PID file /var/run/elasticsearch/elasticsearch-elasticsearch.pid not readable (yet?) after start.
Dec 10 18:36:29 localhost elasticsearch: Failed to configure logging...
Dec 10 18:36:29 localhost elasticsearch: ElasticsearchException[Failed to load logging configuration]; nested: NoSuchFileException[$CONF_DIR];
Dec 10 18:36:29 localhost elasticsearch: at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:158)
Dec 10 18:36:29 localhost elasticsearch: at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:103)
Dec 10 18:36:29 localhost elasticsearch: at org.elasticsearch.bootstrap.Bootstrap.setupLogging(Bootstrap.java:204)
Dec 10 18:36:29 localhost elasticsearch: at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:258)
Dec 10 18:36:29 localhost elasticsearch: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Dec 10 18:36:29 localhost elasticsearch: Caused by: java.nio.file.NoSuchFileException: $CONF_DIR
Dec 10 18:36:29 localhost elasticsearch: at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
Dec 10 18:36:29 localhost elasticsearch: at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
Dec 10 18:36:29 localhost elasticsearch: at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
Dec 10 18:36:29 localhost elasticsearch: at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
Dec 10 18:36:29 localhost elasticsearch: at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
Dec 10 18:36:29 localhost elasticsearch: at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:97)
Dec 10 18:36:29 localhost elasticsearch: at java.nio.file.Files.readAttributes(Files.java:1686)
Dec 10 18:36:29 localhost elasticsearch: at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:109)
Dec 10 18:36:29 localhost elasticsearch: at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
Dec 10 18:36:29 localhost elasticsearch: at java.nio.file.Files.walkFileTree(Files.java:2602)
Dec 10 18:36:29 localhost elasticsearch: at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:142)
Dec 10 18:36:29 localhost elasticsearch: ... 4 more
Dec 10 18:36:29 localhost elasticsearch: log4j:WARN No appenders could be found for logger (bootstrap).
Dec 10 18:36:29 localhost elasticsearch: log4j:WARN Please initialize the log4j system properly.
Dec 10 18:36:29 localhost elasticsearch: log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Dec 10 18:36:29 localhost systemd: elasticsearch-elasticsearch.service never wrote its PID file. Failing.
Dec 10 18:36:29 localhost systemd: Failed to start Starts and stops a single elasticsearch instance on this system.
Dec 10 18:36:29 localhost systemd: Unit elasticsearch-elasticsearch.service entered failed state.

I am not able to find what is actually causing this issue, Can someone tell me what can be the possible reasons of this issue ?

**Comment by electrical** [comment]
Can you paste the puppet code config you use and which version of the puppet module?

Cheers.

**Comment by electrical** [comment]
Closing due to no response. Can re-open if needed.
