### ISSUE TITLE
Service file not created

### ISSUE THREAD

**Issue by devopsprosiva** [elastic/puppet-elasticsearch#521]
Hi,

I'm trying to configure elasticsearch on centos7. This is how I declared the class. However after a puppet agent run, none of the systemd files are being created from the template. Any idea how to fix it?

    class { 'elasticsearch':
        ensure           => present,
        version          => '2.1.0',
        status           => 'enabled',
        manage_repo      => true,
        repo_version     => '2.x',
        service_provider => 'systemd',
    }

Thanks,
Siva

**Comment by electrical** [comment]
Hi @devopsprosiva this is most likely because you didn't specify an [instance](https://github.com/elastic/puppet-elasticsearch#instances)
Please check the docs for more information.

**Comment by devopsprosiva** [comment]
@electrical Thanks for pointing that out. It works now.

**Comment by electrical** [comment]
Great to hear. If you run into other issues please let me know.
