### ISSUE TITLE
plugin install not handling return code 74 for 'Already installed'

### ISSUE THREAD

**Issue by thenom** [elastic/puppet-elasticsearch#524]
Hi,

Thanks for the update for ES2.  I am just redoing my puppet code and hiera and it seems that the plugin install work fine first time round and then subsequent runs file due to ES returning exit code 74

```
Error: Execution of '/usr/share/elasticsearch/bin/plugin install file:///opt/elasticsearch/swdl/license-2.1.0.zip' returned 74: -> Installing from file:/opt/elasticsearch/swdl/license-2.1.0.zip...
Trying file:/opt/elasticsearch/swdl/license-2.1.0.zip ...
Downloading .DONE
Verifying file:/opt/elasticsearch/swdl/license-2.1.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: plugin directory /usr/share/elasticsearch/plugins/license already exists. To update the plugin, uninstall it first using 'remove license' command
Error: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[licence]/Elasticsearch_plugin[licence]/ensure: change from absent to present failed: Execution of '/usr/share/elasticsearch/bin/plugin install file:///opt/elasticsearch/swdl/license-2.1.0.zip' returned 74: -> Installing from file:/opt/elasticsearch/swdl/license-2.1.0.zip...
```

Does this exit code need catching or is it just me mis-reading the docs?  This is my code:

```
        ::elasticsearch::plugin{'licence':
            instances => $es_shield_instances,
            source    => $licence_source,
            ensure    => present,
        }
```

and hiera:

```
profiles::elasticsearch::licence_source: 'puppet:///modules/profiles/elasticsearch/license-2.1.0.zip'
profiles::elasticsearch::es_shield_instances:
    - es-01
    - es-02
```

Thanks again

**Comment by electrical** [comment]
Oh, interesting... I'll have to take a closer look at this and see if i can fix it.
To confirm you are using version 0.10.0 of the module right?

**Comment by electrical** [comment]
It seems i have a test for this already which should catch this:

https://github.com/elastic/puppet-elasticsearch/blob/master/spec/acceptance/021_es2x_spec.rb#L214-L231

I'll take a closer look at this.

**Comment by thenom** [comment]
Hi,

Yes, this is 0.10.0:

```
[root@foreman1 ws_dev]# head modules/elasticsearch/CHANGELOG.md
##0.10.0 ( Dec 14, 2015 )

###Summary
Module now works with ES 2.x completely

####Features
* Work with ES 2.x new plugin system and remain to work with 1.x
* Implemented datacat module from Richard Clamp so other modules can hook into it for adding configuration options
* Fixed init and systemd files to work with 1.x and 2.x
* Made the module work with newer pl-apt module versions
```

Thanks.

**Comment by electrical** [comment]
Also the test you did was this on a clean machine or did it already have something installed?

**Comment by thenom** [comment]
This is a clean machine.  I am redoing my full ES node build with puppet and foreman.

I will trigger a rebuild anyway as i have been tinkering but nothing has been done manually on this build nor has it been built with the older module.

p.s. i might have edited and posted my previous comment after you posted so:

Could this be a multi-instance issue? Doesn't the module only need installing once into the ES home dir for both instances to access it? (just my little knowledge having a guess)

**Comment by electrical** [comment]
The plugin path is shared between instances so that you only need to install it once yeah.
I'll have a closer at this issue today and see if i can find anything weird with it.

**Comment by electrical** [comment]
Oh an other thing you could do is run with `--debug` flag,
This should expose come debug logging lines in the custom provider to give some idea what its doing.
Could you do that run and paste the whole log?

Thanks.

**Comment by thenom** [comment]
I am currently rebuilding node01 but node02 has the same issue.  Here is the output of the --debug that i think you need:

```
Debug: Executing '/usr/share/elasticsearch/bin/elasticsearch -v'
Debug: Executing '/usr/share/elasticsearch/bin/elasticsearch --version'
Debug: Elasticsearch_plugin[shield](provider=plugin): Found ES version 2.1.0
Debug: Elasticsearch_plugin[shield](provider=plugin): Plugin exists
Debug: Executing '/usr/share/elasticsearch/bin/elasticsearch -v'
Debug: Executing '/usr/share/elasticsearch/bin/elasticsearch --version'
Debug: Elasticsearch_plugin[licence](provider=plugin): Found ES version 2.1.0
Debug: Elasticsearch_plugin[licence](provider=plugin): Plugin file /usr/share/elasticsearch/plugins/licence/.name does not exist
Debug: Executing '/usr/share/elasticsearch/bin/plugin install file:///opt/elasticsearch/swdl/license-2.1.0.zip'
Error: Execution of '/usr/share/elasticsearch/bin/plugin install file:///opt/elasticsearch/swdl/license-2.1.0.zip' returned 74: -> Installing from file:/opt/elasticsearch/swdl/license-2.1.0.zip...
Trying file:/opt/elasticsearch/swdl/license-2.1.0.zip ...
Downloading .DONE
Verifying file:/opt/elasticsearch/swdl/license-2.1.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: plugin directory /usr/share/elasticsearch/plugins/license already exists. To update the plugin, uninstall it first using 'remove license' command
Error: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[licence]/Elasticsearch_plugin[licence]/ensure: change from absent to present failed: Execution of '/usr/share/elasticsearch/bin/plugin install file:///opt/elasticsearch/swdl/license-2.1.0.zip' returned 74: -> Installing from file:/opt/elasticsearch/swdl/license-2.1.0.zip...
Trying file:/opt/elasticsearch/swdl/license-2.1.0.zip ...
Downloading .DONE
Verifying file:/opt/elasticsearch/swdl/license-2.1.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: plugin directory /usr/share/elasticsearch/plugins/license already exists. To update the plugin, uninstall it first using 'remove license' command
```

If you need any more info then please let me know.

**Comment by electrical** [comment]
Interesting. I assume this is the log of the second run?
can you check if that .name file indeed doesn't exist?

**Comment by thenom** [comment]
Arrgggh!  To start with i used the English spelling of Licence (not the American - license :P ) so it was the directory /usr/share/elasticsearch/plugins/licence that didn't exist whereas this one /usr/share/elasticsearch/plugins/license did.

I have corrected this and i am still getting the same error:

```
Debug: Executing '/usr/share/elasticsearch/bin/elasticsearch -v'
Debug: Executing '/usr/share/elasticsearch/bin/elasticsearch --version'
Debug: Elasticsearch_plugin[license](provider=plugin): Found ES version 2.1.0
Debug: Elasticsearch_plugin[license](provider=plugin): Plugin file /usr/share/elasticsearch/plugins/license/.name does not exist
Debug: Executing '/usr/share/elasticsearch/bin/plugin install file:///opt/elasticsearch/swdl/license-2.1.0.zip'
Error: Execution of '/usr/share/elasticsearch/bin/plugin install file:///opt/elasticsearch/swdl/license-2.1.0.zip' returned 74: -> Installing from file:/opt/elasticsearch/swdl/license-2.1.0.zip...
Trying file:/opt/elasticsearch/swdl/license-2.1.0.zip ...
Downloading .DONE
Verifying file:/opt/elasticsearch/swdl/license-2.1.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: plugin directory /usr/share/elasticsearch/plugins/license already exists. To update the plugin, uninstall it first using 'remove license' command
Error: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[license]/Elasticsearch_plugin[license]/ensure: change from absent to present failed: Execution of '/usr/share/elasticsearch/bin/plugin install file:///opt/elasticsearch/swdl/license-2.1.0.zip' returned 74: -> Installing from file:/opt/elasticsearch/swdl/license-2.1.0.zip...
Trying file:/opt/elasticsearch/swdl/license-2.1.0.zip ...
Downloading .DONE
Verifying file:/opt/elasticsearch/swdl/license-2.1.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: plugin directory /usr/share/elasticsearch/plugins/license already exists. To update the plugin, uninstall it first using 'remove license' command
```

Also the .name file still does not exist:

```
[root@pup-esnode02 ~]# ll -a /usr/share/elasticsearch/plugins/license/
total 164
drwxr-xr-x. 2 root          root           4096 Dec 16 09:58 .
drwxr-xr-x. 5 elasticsearch elasticsearch    52 Dec 16 10:27 ..
-rw-r--r--. 1 root          root          71376 Dec 16 09:58 license-2.1.0.jar
-rw-r--r--. 1 root          root          22217 Dec 16 09:58 license-core-2.1.0.jar
-rw-r--r--. 1 root          root           9401 Dec 16 09:58 license-plugin-api-2.1.0.jar
-rw-r--r--. 1 root          root          43590 Dec 16 09:58 LICENSE.txt
-rw-r--r--. 1 root          root            155 Dec 16 09:58 NOTICE.txt
-rw-r--r--. 1 root          root           2617 Dec 16 09:58 plugin-descriptor.properties
```

Not sure if this is due to an issue that occurred during the first run due to the naming issue though.  So i have removed the plugin manually (with bin/plugin remove) and re-ran puppet:

```
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[license]/Elasticsearch_plugin[license]/ensure: created
Info: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[license]/Elasticsearch_plugin[license]: Scheduling refresh of Elasticsearch::Service[es-01]
Info: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[license]/Elasticsearch_plugin[license]: Scheduling refresh of Elasticsearch::Service[es-02]
```

And then ran again with no licence plugin error.  Sorry for the mis-lead and thanks for looking into it so quick.

**Comment by electrical** [comment]
No worries at all! I'm glad its found now.

This is the only 'issue' with the plugin system that I have to use the resource name to know the directory name, which usually works when installing it online :-)

**Comment by thenom** [comment]
Sorry, just one last question...  (p.s. esnode01 rebuilt perfectly with no issues and all modules)

I am still having the issue with multi-instance ES not reading the shield users created with:

```
[root@pup-esnode01 ~]# /usr/share/elasticsearch/bin/shield/esusers useradd admin -r admin
Enter new password:
Retype new password:
[root@pup-esnode01 ~]# curl -u admin http://127.0.0.1:9200/_cluster/health
Enter host password for user 'admin':
{"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate user [admin] for REST request [/_cluster/health]","header":{"WWW-Authenticate":"Basic realm=\"shield\""}}],"type":"security_exception","reason":"unable to authenticate user [admin] for REST request [/_cluster/health]","header":{"WWW-Authenticate":"Basic realm=\"shield\""}},"status":401}
```

Is this still an issue?

Please let me know if you want me to register this elsewhere.

**Comment by electrical** [comment]
Hi, the shield stuff is still an issue i'm afraid and still looking for a working solution around this.
The main issue is that with the built in security its not allowing me to do symlinking so i'm looking for a better solution.

**Comment by thenom** [comment]
Ok, is there a thread i can follow for this?

**Comment by electrical** [comment]
Currently https://github.com/elastic/puppet-elasticsearch/issues/433 is the main issue for it.
I'm working on a shield related module which hopefully will solve this at some point, no eta on it yet though :-(

**Comment by thenom** [comment]
Great, thanks again for your help and work on this.

**Comment by electrical** [comment]
No problem at all!

**Comment by lucabelluccini** [comment]
Sorry to comment on this, but it seems plugin installation is broken when a custom plugindir is provided.

**Comment by tylerjl** [comment]
@lucabelluccini I wasn't super familiar with that parameter so I dug deep in the git history and can confirm that the plugindir parameter never actually _installed_ plugins to different directories, but was exposed to help point the module at a different directory if you were installing plugins there outside of the scope of the module.

I do think that perhaps plugindir needs better documentation in that regard since it appears to not change where `bin/plugin` installs plugins to; it may even need to be replaced since it seems to be basically a no-op. While path.plugins exists to tell Elasticsearch where to look at to find plugins, that settings was completely removed in 5.x so I'm hesitant to try and add the ability to install plugins to arbitrary directories to the module.

**Comment by lucabelluccini** [comment]
Thank you @tylerjl for the explaination and the checks.
As you stated, in the breaking changes of Elasticsearch 5, plugin installation destination path cannot be customized, so I see no interest on keeping this parameter in the future.
