### ISSUE TITLE
puppet-elasticsearch freezes with ES 2.1 on CentOS 6

### ISSUE THREAD

**Issue by jmjansen** [elastic/puppet-elasticsearch#528]
To determine the version of the installed instance of ES '/usr/share/elasticsearch/bin/elasticsearch -v' is started. On ES 1.7 it returns the version, on ES 2.x it just runs ES and it does not return to puppet.

As a result the puppet run freezes ...

When I remove the line 'version = es('-v') # ES 1.x' (and the 'rescue' line just below it) from the file lib/puppet/provider/elasticsearch_plugin/plugin.rb, puppet runs perfectly on my updated systems. Now it will freeze on systems not upgraded to 2.x though.

**Comment by electrical** [comment]
That's weird since i run tests on both 1.x and 2.x systems without any issues so far.
Can you run with --debug line and paste the output?

Thanks!

**Comment by electrical** [comment]
Also can you check which puppet, ruby and java versions you have?

**Comment by jmjansen** [comment]
I did already this morning ... that's how we found out the process froze on the -v   

Notice the delays between the '/usr/share/elasticsearch/bin/elasticsearch -v' and '/usr/share/elasticsearch/bin/elasticsearch --version' ... It wasn't until I killed the '/usr/share/elasticsearch/bin/elasticsearch -v' the script would continue and invoke '/usr/share/elasticsearch/bin/elasticsearch --version' ...

Thu Dec 17 09:02:03 +0100 2015 /Stage[main]/Elasticsearch_wrapper::Curator/Package[elastic-curator] (debug): Nothing to manage: no ensure and the resource doesn't exist
Thu Dec 17 09:02:03 +0100 2015 Puppet (debug): Prefetching crontab resources for cron
Thu Dec 17 09:02:03 +0100 2015 /Stage[main]/Generic::Users/User[jenkinsdeploy] (debug): Nothing to manage: no ensure and the resource doesn't exist
Thu Dec 17 09:02:03 +0100 2015 Puppet (debug): Executing '/usr/share/elasticsearch/bin/elasticsearch -v'
Thu Dec 17 09:12:06 +0100 2015 Puppet (debug): Executing '/usr/share/elasticsearch/bin/elasticsearch --version'
Thu Dec 17 09:12:07 +0100 2015 Elasticsearch_plugin[royrusso/elasticsearch-HQ](provider=plugin) (debug): Found ES version 2.1.0
Thu Dec 17 09:12:07 +0100 2015 Elasticsearch_plugin[royrusso/elasticsearch-HQ](provider=plugin) (debug): Plugin exists
Thu Dec 17 09:12:07 +0100 2015 Puppet (debug): Executing '/usr/share/elasticsearch/bin/elasticsearch -v'
Thu Dec 17 09:12:37 +0100 2015 Puppet (debug): Executing '/usr/share/elasticsearch/bin/elasticsearch --version'
Thu Dec 17 09:12:37 +0100 2015 Elasticsearch_plugin[mobz/elasticsearch-head](provider=plugin) (debug): Found ES version 2.1.0
Thu Dec 17 09:12:37 +0100 2015 Elasticsearch_plugin[mobz/elasticsearch-head](provider=plugin) (debug): Plugin exists

Versions:
- puppet-3.8.1-1.el6.noarch
- ruby-1.8.7.352-13.el6.x86_64
- java version "1.7.0_79"

**Comment by electrical** [comment]
Hmm, I've been unable to reproduce this so far in any of my tests.
I'll try to do some more debugging next week.

**Comment by donovankim** [comment]
+1

**Comment by electrical** [comment]
I still haven't been able to reproduce this.
Could you execute the -v and --version commands manually and see what happens? i wonder if it stalls there as well.

**Comment by gingerwizard** [comment]
Version 2.0 it errors and tries -version.
2.1 it hangs and thus prevents any further actions. Centos 6.5.

**Comment by electrical** [comment]
Okay, regression bug in ES between 2.0 and 2.1 then :-(

**Comment by jmjansen** [comment]
On 2.1, -v is a shorthand for --verbose, which does nothing for elasticsearch. The effect is, elasticsearch is started and is never to return unless you kill it manually.
Seems someone didn't care about backwards compatibility ...

**Comment by electrical** [comment]
This makes it even weirder.. Did 2.0.x and 2.1.x tests on a centos 6 docker container with all my tests and it runs fine :-(
Something somewhere is causing this weird behaviour but i'm unable to reproduce it at all.

**Comment by electrical** [comment]
for the record, the plugin provider runs elasticsearch as user root.
So -v should fail stating that running as root is not allowed and exit with a non zero exit code.
-version should give the right version.

**Comment by electrical** [comment]
@jmjansen i assume you run puppet as user root as well right?

**Comment by jmjansen** [comment]
@electrical, root is running puppet indeed. (And user elasticsearch is running Elasticsearch.)

**Comment by electrical** [comment]
it seems that in some weird cases -v actually starts up Elasticsearch with 2.x as user root.
Currently trying out a different approach which might be more stable.

**Comment by philipwigg** [comment]
Seems like it should always error as root unless ```es.insecure.allow.root``` is set?

https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java#L88-L94

**Comment by electrical** [comment]
@philipwigg with ES 1.x it was allowed to use root, with ES 2.x it breaks indeed but its allowed to return the version number ;-)

**Comment by philipwigg** [comment]
Yes, but I don't think 2.x will return a version number with ```-v```?
It will just quit with the ```don't run elasticsearch as root``` error and then the provider will retry with ```--version``` to get the version number?

I can reproduce the issue, i.e. get 2.x to hang at...

```Debug: Executing '/usr/share/elasticsearch/bin/elasticsearch -v'```

if I first ```export ES_JAVA_OPTS=-Des.insecure.allow.root=true``` before running Puppet.

Maybe that's set on the OP's system?

**Comment by electrical** [comment]
@philipwigg that could be the possibility yeah. but we've also seen some other systems without that flag and it continues to run :-(

**Comment by electrical** [comment]
Okay. new solution :-)
`/usr/share/elasticsearch/bin/elasticsearch -version` will get the following on the different versions:

1.x:
```
$ ./bin/elasticsearch -version
getopt: invalid option -- 'e'
getopt: invalid option -- 'r'
getopt: invalid option -- 's'
getopt: invalid option -- 'i'
getopt: invalid option -- 'o'
getopt: invalid option -- 'n'
Version: 1.7.3, Build: 05d4530/2015-10-15T09:14:17Z, JVM: 1.7.0_79
```
The puppet command ignores the getopt stuff because thats via stderr and not stdout.

on 2.x:
```
$ ./bin/elasticsearch -version
Version: 2.1.1, Build: 40e2c53/2015-12-15T13:05:55Z, JVM: 1.7.0_79
```

This way there is only a single command to execute and always get the expected result. Until someone decides to change it again :-)

**Comment by gingerwizard** [comment]
+1 great. thanks.

**Comment by jmjansen** [comment]
Sounds good :-)
