### ISSUE TITLE
Ubuntu 14.04(Vagrant) - Fails to Install

### ISSUE THREAD

**Issue by shaharlinial** [elastic/puppet-elasticsearch#533]
Hi, 
Using the basic configuration from the documentation:
(I'm using Hiera so this is a wrapper class)
````
class vagrant_elasticsearch(){
  class { 'elasticsearch':
    version => '1.4.2'
  }
  elasticsearch::instance { 'es-01': }
}
````
**Produces:**

    Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-   yes install elasticsearch=1.4.2' returned 100: Reading package lists...
    ==> default: Building dependency tree...
    ==> default: Reading state information...
    ==> default: E: Unable to locate package elasticsearch

After I tried couple of times injecting the `apt-get update` before puppet tries to fetch elasticsearch (without success, causing the same error `100`),
I've added multiple elasticsearch versions the modules, so I'm passing the package_url:

````
class vagrant_elasticsearch(){

  $elastic_values = hiera("elasticsearch")
  $elasticsearch_version = $elastic_values["ver"]

  class { 'elasticsearch':
    java_install => $elastic_values['java_install'],
    package_url => "puppet:///modules/elasticsearch/elasticsearch-$elasticsearch_version.deb",
  }
  elasticsearch::instance { 'es-01': }
}
````
Does work.

I thought you might want to know about this.

**Comment by electrical** [comment]
Hi,
By default the repo management is not enabled. See https://github.com/elastic/puppet-elasticsearch#repository

**Comment by shaharlinial** [comment]
So passing 
````
class { 'elasticsearch':
  manage_repo  => true,
  repo_version => '1.4',
}
````
Suppose to solve this?

**Comment by electrical** [comment]
Correct

**Comment by electrical** [comment]
Oh, and please don't use 1.4.x  we are already at 1.7.x and even 2.1.x :-)

**Comment by shaharlinial** [comment]
:+1: I'm using 2.0.0 but it was just for the sake of Copy-Paste.

Thanks for the reply,
IMO you should address this issue better, imagine that I've spent 1.5 days on it and nothing came from Google.

**Comment by electrical** [comment]
ah okay. I thought it was already clear in the documentation :-)  I'll see if i can improve it
