### ISSUE TITLE
should support optionally not managing $datadir

### ISSUE THREAD

**Issue by alexharv074** [elastic/puppet-elasticsearch#553]
Some people will be using LVM, mounted SAN storage etc for the ElasticSearch data directory, whereas this module assumes that it can make the data directory.  There needs to be a feature to optionally disable this.

**Comment by bflad** [comment]
For what its worth, we generally set the elasticsearch data directory one subdirectory below anything we LVM/mount.

**Comment by alexharv074** [comment]
While there's nothing wrong with that, I still think the module should support use of a directory that was created outside of the module.

**Comment by electrical** [comment]
Hi guys,

I've added the discussion label to get more input from others before making a decision on this.

**Comment by alexharv074** [comment]
@electrical well to get things moving I already submitted a pull request.

Please note that I am upgrading from both an earlier version of ElasticSearch and an earlier version of this module.  Seems like the earlier version of this module evidently didn't try to manage the $datadir?  Unless my colleague hacked it. :)

To me it's a no-brainer, of course the module should allow people to manage the LVM externally to the module, and some people simply won't be able to use a subdirectory.  I can't, if the feature can't be added I'll simply have to fork it.
