### ISSUE TITLE
Plugins installed with wrong ownership

### ISSUE THREAD

**Issue by jsnod** [elastic/puppet-elasticsearch#565]
I've just upgraded from 0.9.9 to 0.10.2 of this plugin, and it looks like https://github.com/elastic/puppet-elasticsearch/issues/107 has returned.  Plugins are installed/owned by root, which means they can't be read by the elasticsearch user when starting ES.  I was able to get around this by running the following manually:

`chown -R elasticsearch.elasticsearch /usr/share/elasticsearch/plugins/`

**Comment by electrical** [comment]
Hi. I have some plugin tests and none of them have shown issues loading them in elasticsearch.
They are with the elasticsearch user but they should be readable by the elasticsearch user. Can you check the mode set on the directory and files ?

**Comment by jsnod** [comment]
`/usr/share/elasticsearch/plugins` is owned by `elasticsearch` as expected, but `/usr/share/elasticsearch/plugins/marvel` is owned by `root` after the plugin installs.  Note, I am still on v1.7 of ES.  Here is the relevant part of my class:

```
    $instance_name = 'vagrant'
    elasticsearch::plugin { 'elasticsearch/marvel/latest':
        instances  => $instance_name,
    }
```

To reproduce all I need to do is manually remove the plugin (`/usr/share/elasticsearch/bin/plugin -r marvel`) and then run `vagrant provision` to trigger a Puppet run.

**Comment by electrical** [comment]
Did a quick check and everything has `-rw-r--r--` as rights. so everything is readable for everyone.

**Comment by jsnod** [comment]
Just checked, and while the root plugin dir has the expected permissions, the individual plugin dirs do not:

```
drwxr-xr-x 4 elasticsearch elasticsearch 4.0K Jan 26 13:08 /usr/share/elasticsearch/plugins
drwxr-x--- 3 root          root          4.0K Jan 28 10:30 /usr/share/elasticsearch/plugins/marvel
```

**Comment by electrical** [comment]
Hi,

I'll do some more digging into it this week.

**Comment by eperdeme** [comment]
Same problem here after upgrading ES versions. Perms seemed fine prior to upgrading ES and all I did was tell it a new verison of the plugin + es.

[root@cxpxelk02mas001 ~]# ls -al /usr/share/elasticsearch/plugins/
total 16
drwx------. 4 root          root          4096 Apr  8 09:41 .
drwxr-xr-x. 8 elasticsearch elasticsearch 4096 Apr  8 09:41 ..
drwx------. 2 root          root          4096 Apr  8 09:41 license
drwx------. 2 root          root          4096 Apr  8 09:41 marvel-agent

**Comment by MEPhoenyx** [comment]
Same with puppetmodule for elasticsearch v10.3 and Elasticsearch 2.3 

Plugin Folder Owner is root not elasticsearch. 

Result is:```
 Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/elasticsearch_plugin: Could not autoload puppet/provider/elasticsearch_plugin/plugin: undefined method `[]' for Facter:Module at /etc/puppetlabs/code/environments/ciso_master/external_modules/elasticsearch/manifests/plugin.pp:134:7 at /etc/puppetlabs/code/environments/ciso_master/services/cselastic/manifests/init.pp:44 on node cselasticdbbsba01.db.server.lan
Warning: Not using cache on failed catalog

```

**Comment by RogierSchuring** [comment]
Same problem here with the kopf plugin. (using offline installation)
worked around this issue by adding the next block of code to our profile, but it would be ideal if the module would take care of this:
`  if ($ensure=='present') {
    file { $path_plugins:
      ensure  => directory,
      owner   => $es_user,
      group   => $es_group,
      recurse => true,
    }
  }`
ES 2.3.3
Kopf 2.1.2
Puppet module: 0.13.1

**Comment by deepybee** [comment]
Frustrating to see a new release of the module where this is still a problem. Have had to work around this with hacky exec calls and file resources to get EC2 discovery and ElasticHQ installed and enabled with the correct permissions 😞

**Comment by cdenneen** [comment]
I'm curious as to what issue people are experiencing with this?
I have the same issue that the plugins are being installed with root:root ownership but the permissions are in such a way that they are readable and executable by elasticsearch user, so there are no errors on puppet runs and plugins are running without issue.

I'm using module 0.11.0 and ES 2.3.3 and there are no issues loading the plugins (kopf, head, marvel, etc)

**Comment by tylerjl** [comment]
I also can't reproduce the behavior cited here; the plugin permissions and mode I'm seeing are also `root:root` but with read privileges for all, so plugins seem to work correctly in my testing scenario.

However, given the issues raised here, it's evident we can't assume ownership and mode will be correct; my best guess here is that some customized setups have different `umask` settings of some sort and are thus restricting the `elasticsearch` user from reading plugin files.

Bearing in mind the (valid) concerns in #568 regarding permissions granted to the `elasticsearch` user, it seems the most robust and secure option here is to recursively manage the plugin directory to ensure files and directories are readable for all users (i.e. `a+r` or something like that). Ensuring plugin source files are owned as the elasticsearch user/`bin/plugin` is executed as the elasticsearch user stopped happening as of df3047fc when the native provider was swapped in.

**Comment by RogierSchuring** [comment]
this is how the elasticsearch dir looks like after a fresh installation (looks okay):
> sudo ls -al /usr/share/elasticsearch/
> total 40
> drwxr-xr-x.   9 elasticsearch elasticsearch  4096 Aug 17 08:25 .
> drwxr-xr-x. 106 root          root           4096 Aug 17 08:25 ..
> drwxr-xr-x.   2 root          root            102 Aug 17 08:25 bin
> drwxr-xr-x.   2 elasticsearch elasticsearch  4096 Aug 17 08:25 lib
> -rw-r--r--.   1 root          root          11358 Jan 27  2016 LICENSE.txt
> drwxr-xr-x.   5 root          root             60 Aug 17 08:25 modules
> -rw-r--r--.   1 root          root            150 May 12 15:24 NOTICE.txt
> drwxr-xr-x.   2 elasticsearch elasticsearch     6 Aug 17 08:25 plugins
> -rw-r--r--.   1 root          root           8700 May 12 15:24 README.textile
> drwxr-xr-x.   2 elasticsearch elasticsearch     6 Aug 17 08:25 scripts
> drwxr-xr-x.   2 root          root              6 Aug 17 08:25 shield
> drwxr-xr-x.   2 elasticsearch elasticsearch     6 Aug 17 08:25 templates_import

This is how the plugins dir looks like after plugin installation:
> sudo ls -al /usr/share/elasticsearch/plugins/
> total 8
> drwxr-xr-x. 3 elasticsearch elasticsearch   17 Aug 17 08:29 .
> drwxr-xr-x. 9 elasticsearch elasticsearch 4096 Aug 17 08:25 ..
> drwxr-x---. 8 root          root          4096 Aug 17 08:29 kopf

As you can see, on my RHEL 7 system (umask = 0027), it is not readable for everyone :(

Also someone decided somewhere between ES 1.7.2 and 2.3.3 that it would be an excellent idea for elasticsearch to FAIL when it can't load one of it's plugins :(
> [2016-08-17 08:29:21,877][INFO ][node                     ] [mynode] version[2.3.3], pid[26287], build[218bdf1/2016-05-17T15:40:04Z]
> [2016-08-17 08:29:21,877][INFO ][node                     ] [mynode] initializing ...
> [2016-08-17 08:29:23,225][ERROR][bootstrap                ] Exception
> java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [kopf]. Was the plugin built before 2.0?

> Aug 17 08:29:23 mynode systemd[1]: elasticsearch-myinstance.service: main process exited, code=exited, status=1/FAILURE
> Aug 17 08:29:23 mynode systemd[1]: Unit elasticsearch-myinstance.service entered failed state.
> Aug 17 08:29:23 mynode systemd[1]: elasticsearch-myinstance.service failed.

If you need more system specific information, let me know.

**Comment by cdenneen** [comment]
@RogierSchuring so you are configuring this umask change as it isn't default. I have a EL7 system as well and the default permissions are 0022 umask which is fine. So I'm guessing you are specifying this umask somewhere in your code which is what is causing this problem as that isn't the default?

**Comment by RogierSchuring** [comment]
@cdenneen Its the default setting of the company stack, so unfortunately, i am not allowed to change it.
Seeing that i'm not the only one with the problem, I don't think my company is the only company with the umask set that way ;)

**Comment by jsnod** [comment]
CentOS 6.8 does this in `/etc/profiles`:

```
# By default, we want umask to get set. This sets it for login shell
# Current threshold for system reserved uid/gids is 200
# You could check uidgid reservation validity in
# /usr/share/doc/setup-*/uidgid file
if [ $UID -gt 199 ] && [ "`id -gn`" = "`id -un`" ]; then
    umask 002
else
    umask 022
fi
```

We pre-create the elasticsearch user with a GID > 200, which explains why we're getting wrong permissions in our setup.

**Comment by tylerjl** [comment]
Without casting blame here, this is definitely something that arises out of end-user changes to the system, and the module functions entirely correctly out-of-the box by default. This is only an issue when folks make some change that skews the umask that plugins are installed with.

The super conservative response here would be "if you're changing the umask, it's your responsibility to ensure the fallout doesn't break anything", but practically, the module does some shifty things to figure out what the plugin directory name is, so it's *far* easier to control this directly in the module where we can reliably determine the plugin directory's name.

The changeset in #685 makes that happen by ensuring the relevant plugin dir is (basically) `chmod -R o+Xr`. The change should be in the next release.

**Comment by jsnod** [comment]
Thanks @tylerjl.  To be clear, we're not explicitly changing the umask, it's a side effect of specifying our own UID/GID for the `elasticsearch` user, which I imagine is a common practice especially for large deployments with managed user accounts.  This fix looks like it will do the job, thanks so much!

**Comment by cdenneen** [comment]
@tylerjl to be fair the fact that puppet runs as root is what makes the plugins install as root. If ES is meant to run as non-root user then the module should change the ownership of the installed plugins or runas es user. You could login as es user on a server and install the plugins and the ownership would be correct so this is actually more of a side effect of the puppet run. 
I know with puppet Exec you can specify a different user, is the same possible when using a puppet Type like this?

**Comment by tylerjl** [comment]
The question of whether the running service should have the same effective user ID as the plugin files is an open one. While we could run the `elasticsearch` service as the `elasticsearch` user and ensure that `chown -R elasticsearch:elasticsearch /usr/share/elasticsearch`, the concern raised is #568 still valid. That is, if someone gets control of the Elasticsearch daemon, the goal should be to limit the possible damage done to the system with as few paths writable to the daemon as possible - this is pretty unavoidable for the Elasticsearch data directory, but there's really no reason the running daemon needs ownership and thus write permissions for the plugin directory - it just needs to read plugin source files.

I'm aware that this definitely isn't the case for many of the paths that ship with Elasticsearch packages out-of-the box, but we can certainly move the in the right direction regardless. 👍 

P.S. FWIW I still don't know what the best practice is for setting an effective user ID for shell commands within custom types/providers - my guess is that the "correct" approach would be to recursively manage directory owner/group similar to the way it's managing the mode now, but I'd love to learn if that's not the case 🎱

**Comment by RogierSchuring** [comment]
Thanks @tylerjl

**Comment by jsnod** [comment]
I just updated to 0.13.2, and this still broken for me.  It looks like permissions are set correctly on the individual plugin dirs, but not on the `/usr/share/elasticsearch/plugins` dir itself:

```
01:36 PM [vagrant@vagrant /] ls -lh /usr/share/elasticsearch
total 60K
drwxr-xr-x 2 root          root          4.0K Aug 29 13:25 bin
drwxr-x--- 3 elasticsearch elasticsearch 4.0K Aug 29 13:25 data
drwxr-xr-x 2 elasticsearch elasticsearch 4.0K Aug 29 13:25 lib
-rw-r--r-- 1 root          root           12K Jun 30 04:22 LICENSE.txt
drwxr-xr-x 5 root          root          4.0K Aug 29 13:25 modules
-rw-r--r-- 1 root          root           150 Jun 30 04:22 NOTICE.txt
drwxr-x--- 3 root          root          4.0K Aug 29 13:25 plugins
-rw-r--r-- 1 root          root          8.5K Jun 30 04:22 README.textile
drwxr-xr-x 2 elasticsearch elasticsearch 4.0K Aug 29 13:25 scripts
drwxr-xr-x 2 root          root          4.0K Aug 29 13:25 shield
drwxr-xr-x 2 elasticsearch elasticsearch 4.0K Aug 29 13:25 templates_import
```

Starting ES in this state gives the following error:
```Unable to access 'path.plugins' (/usr/share/elasticsearch/plugins)```

If I manually fix the permissions, it works:
```
01:36 PM [vagrant@vagrant /] chmod o+Xr /usr/share/elasticsearch/plugins/
01:36 PM [vagrant@vagrant /] ls -lh /usr/share/elasticsearch
total 60K
drwxr-xr-x 2 root          root          4.0K Aug 29 13:25 bin
drwxr-x--- 3 elasticsearch elasticsearch 4.0K Aug 29 13:25 data
drwxr-xr-x 2 elasticsearch elasticsearch 4.0K Aug 29 13:25 lib
-rw-r--r-- 1 root          root           12K Jun 30 04:22 LICENSE.txt
drwxr-xr-x 5 root          root          4.0K Aug 29 13:25 modules
-rw-r--r-- 1 root          root           150 Jun 30 04:22 NOTICE.txt
drwxr-xr-x 3 root          root          4.0K Aug 29 13:25 plugins
-rw-r--r-- 1 root          root          8.5K Jun 30 04:22 README.textile
drwxr-xr-x 2 elasticsearch elasticsearch 4.0K Aug 29 13:25 scripts
drwxr-xr-x 2 root          root          4.0K Aug 29 13:25 shield
drwxr-xr-x 2 elasticsearch elasticsearch 4.0K Aug 29 13:25 templates_import
```

@tylerjl Can the module update permissions on the plugins dir itself as well?

**Comment by tylerjl** [comment]
Dang - sorry about that. The dangers of fixing issues without reproducing a viable test case in CI. 🎲 

Given that all the subdirectories of `plugin/` are being managed now, the only thing that needs to be changed is adding a `mode => 'o+Xr'` at https://github.com/elastic/puppet-elasticsearch/blob/0.13.2/manifests/config.pp#L140 (with an added parameter to check the mode at https://github.com/elastic/puppet-elasticsearch/blob/0.13.2/spec/classes/000_elasticsearch_init_spec.rb#L279).

Should be an easy fix, I'll open a new ticket to track it and get it into another minor bugfix release.
