### ISSUE TITLE
Shield - key_file

### ISSUE THREAD

**Issue by pricecarl** [elastic/puppet-elasticsearch#567]
Hello,
I am trying to setup ElasticSearch via your puppet module.

However I have hit a problem and I'm not sure if it is with puppet or shield.
I have multiple nodes on a single server which puppet can do quite easily. The problem is when I try to install the shield plugin (via puppet) I get this error:

    java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/elasticsearch/shield/system_key" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
        at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795)
        at sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:290)
        at java.nio.file.Files.exists(Files.java:2385)
        at org.elasticsearch.shield.crypto.InternalCryptoService.readSystemKey(InternalCryptoService.java:185)
        at org.elasticsearch.shield.crypto.InternalCryptoService.loadKeys(InternalCryptoService.java:133)
        at org.elasticsearch.shield.crypto.InternalCryptoService.doStart(InternalCryptoService.java:115)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
        at org.elasticsearch.node.Node.start(Node.java:242)
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:221)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:287)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

The way I have the node set up is like this:

    [root@localhost shield]# cd /etc/elasticsearch/
    [root@localhost elasticsearch]# ll
    total 28
    drwxr-xr-x. 2 elasticsearch elasticsearch 4096 Jan 28 17:03 es-c01
    drwxr-xr-x. 2 elasticsearch elasticsearch 4096 Jan 28 17:03 es-d01
    drwxr-xr-x. 2 elasticsearch elasticsearch 4096 Jan 28 17:03 es-d02
    drwxr-xr-x. 2 elasticsearch elasticsearch 4096 Jan 28 17:10 es-m01
    drwxr-xr-x. 2 elasticsearch elasticsearch 4096 Jan 28 17:03 es-m02
    drwxr-x---. 2 elasticsearch elasticsearch 4096 Dec 15 13:37 scripts
    drwxr-xr-x  2 elasticsearch elasticsearch 4096 Jan 28 17:11 shield

the shield directory above contains the roles.yml file etc...

in each of the node folders is a symlink to the shield folder above (so all the nodes pick up the same shield configuration files) so /etc/elasticsearch/es-m01/shield ->  /etc/elasticsearch/shield and /etc/elasticsearch/es-m02/shield -> /etc/elasticsearch/shield and so on …

I have gone through the docs:

https://www.elastic.co/guide/en/shield/current/enable-message-authentication.html

and have the key in the right place (/etc/elasticsearch/shield/system_key) with the right permissions and the elasticsearch user is able to read it fine. But ES keeps refusing to start throwing that error. I have also tried adding the setting shield.system_key.file: /etc/elasticsearch/shield/system_key to the elasticsearch.yml file but this doesn’t seem to make and different.

If I put the key_file in /etc/elasticsearch/es-m01/shield without the syml link to /etc/elasticsearch/shield the node starts fine. Does this mean shield can’t follow symlinks?

Has anyone else come across this problem and managed to solve it? Or do you have a better way I can achieve this?

**Comment by electrical** [comment]
Hi. I'm afraid this is a known issue indeed.
I'm still searching for a workable solution. I do have som ideas that I want to try out.
Soon I'll have more time to dig into this.

**Comment by pricecarl** [comment]
Hey, this works in es 1.7.1 though. What is the point of having the option shield.system_key.file if it just gets ignored?

**Comment by electrical** [comment]
Hi. This is caused by the security manager that was introduced in 2.x for ensuring only certain paths can be accessed.

**Comment by pricecarl** [comment]
Is there anything you can think of that I can try please?

**Comment by electrical** [comment]
The only thing i can think of is symlinking the individual files. If i remember correctly that worked but haven't validated it my self.

**Comment by pricecarl** [comment]
Ah let me try this, what I did was symlinked the whole shield directory.

**Comment by pricecarl** [comment]
Nope that doesn't work either

**Comment by electrical** [comment]
only other solution that might work is hard links instead of soft links. not sure what kind of impact that might have.

**Comment by pricecarl** [comment]
yes hard links work, thank you very much :)

**Comment by electrical** [comment]
Cool :-) I'll have to see if i can implement that in the puppet module as well.

**Comment by pricecarl** [comment]
I've managed to get it working, now I'm no puppet expert (only been working with it a week) so this can probably be tidied up quite a bit. This is what I did:
    
development_node.pp

    if str2bool($platform::es_shield) {
    # License Plugin needs to be updated when we get an actual license
    profile::app::elasticsearch::license_plugin { 'license plugin install':
      instances => [
        'es-m01',
        'es-d01',
        'es-m02',
        'es-d02',
        'es-c01']
    }
    profile::app::elasticsearch::shield_plugin { 'shield plugin install': instances => ['es-m01'] }
     }

shield_plugin.pp

    define profile::app::elasticsearch::shield_plugin ($instances = [], $instance_conf = $platform::es_shield_ldap_role_mapping) {
      elasticsearch::plugin { 'shield':
    instances => $instances,
    source    => "puppet:///modules/elasticsearch/shield-$platform::es_shield_version.zip",
      }

      exec { 'system key':
    command => '/usr/share/elasticsearch/bin/shield/syskeygen /etc/elasticsearch/shield/system_key',
    #path    => '/usr/share/elasticsearch/bin/shield/',
    #before  => Package['profile::app::elasticsearch::shield_plugin_configuration'],
    }

    file { "/etc/elasticsearch/shield/system_key":
    ensure => present,
    owner  => 'elasticsearch',
    group  => 'elasticsearch',
    mode   => '0600',
    require => Exec['system key'],
      }
  
      profile::app::elasticsearch::shield_plugin_configuration { $instances: }
    }

shield_plugin_configuration.pp

    define profile::app::elasticsearch::shield_plugin_configuration ($instance = $title) {
    file { "/etc/elasticsearch/${instance}/shield/":
    ensure => directory,
    owner  => 'elasticsearch',
    group  => 'elasticsearch',
    mode   => '0644',
      }

    exec { 'link':
    command => "/bin/ln /etc/elasticsearch/shield/system_key /etc/elasticsearch/${instance}/shield/system_key",
    require => File["/etc/elasticsearch/${instance}/shield/"]
      }
    }

Hopefully this makes sense, I know the indentation will be all over the place on here but hey.

**Comment by electrical** [comment]
hi @pricecarl it looks pretty good after a quick look.
I do see a few things that might cause problems later on.

1. Make sure all resources that are in defines utilize the `$title` variable so they are all unique. Otherwise you can get duplicate resource names.

2. In exec resources its best to add a check if the file already exists or not to avoid it being executed all the time.
Have a look at the `onlyif` or `creates` options.

**Comment by pricecarl** [comment]
Good points I will add these in now. Also need to add in links to the rest of the files, so role_mapping.yml etc.

I'll keep you posted.

**Comment by jcochard** [comment]
Here's what I'm using to get around this currently.  
```
define profile::defines::hardlink (
  $source,
  $target = $title,
  $ensure = 'present',
) {

  validate_re($ensure,  ['present', 'absent'])

  if $ensure == 'present' {
    exec { "hardlink from ${source} to ${target}":
      command => "ln ${source} ${target}",
      path    => '/usr/local/bin:/bin',
      creates => $target,
    }
  }
  elsif $ensure == 'absent' {
    file { $target:
      ensure => absent,
    }
  }
}
```

```
  Profile::Defines::Hardlink {
    require => [
      Elasticsearch::Instance[$instance],
    ]
  }

  profile::defines::hardlink { "${es_home}/${instance}/shield/role_mapping.yml":
    source => "${es_home}/shield/role_mapping.yml",
  }
  profile::defines::hardlink { "${es_home}/${instance}/shield/roles.yml":
    source => "${es_home}/shield/roles.yml",
  }
  profile::defines::hardlink { "${es_home}/${instance}/shield/logging.yml":
    source => "${es_home}/shield/logging.yml",
  }
  profile::defines::hardlink { "${es_home}/${instance}/shield/users":
    source => "${es_home}/shield/users",
  }
  profile::defines::hardlink { "${es_home}/${instance}/shield/users_roles":
    source => "${es_home}/shield/users_roles",
  }
  profile::defines::hardlink { "${es_home}/${instance}/shield/system_key":
    source => "${es_home}/shield/users_roles",
  }
```

**Comment by fgimian** [comment]
The app desperately needs to support symlinks for this, hard links are prone to many issues.  Running the esusers command for instance (and manipulating users) creates a new inode and breaks hard links.

Symlinks would be a significantly more elegant solution here.

**Comment by tylerjl** [comment]
@fgimian unfortunately symlinks just plain won't work with Elasticsearch's security manager; that's a matter for Elasticsearch upstream. See the [comment on this issue](https://github.com/elastic/puppet-elasticsearch/issues/433#issuecomment-216231207) for the approach I'm trying, which is to manage the roles/users in `/usr` and leveraging puppet to keep everything in sync.

**Comment by fgimian** [comment]
Thanks @tylerjl, was just reading that thread actually 😄 

Seems like a tricky problem to solve.  Symlinking ability would have made my and your life a lot easier, hehe.

Thanks a lot for your help!!
Fotis
