### ISSUE TITLE
Offline install of plugin doesn't seem to work as intended when specifying source

### ISSUE THREAD

**Issue by LyndonArmitage** [elastic/puppet-elasticsearch#570]
When I try to perform an offline install of a plugin (on a CentOS 7 machine) using the `$source` parameter it fails to copy the given file to the swdl directory.

I think this could potentially be fixed by adding a [Before relationship](https://docs.puppetlabs.com/puppet/latest/reference/lang_relationships.html) to this [file resource](https://github.com/elastic/puppet-elasticsearch/blob/ff3ccb4e91b2411de91550172801bb1c26231eaf/manifests/plugin.pp#L118).

As a work around I had to copy the plugin zip file (in this case elasticsearch-head) into `/opt/elasticsearch/swdl/`:

```puppet
  file { '/opt/elasticsearch/swdl/elasticsearch-head-master.zip':
   ensure => present,
   mode   => 0600,
   source => 'puppet:///modules/mymodule/elasticsearch-head-master.zip',
 }

  elasticsearch::plugin { 'head':
    source => 'puppet:///modules/mymodule/elasticsearch-head-master.zip',
    instances => 'master',
  }
```

**Comment by electrical** [comment]
Ah, i must completely missed that when refactoring it. sorry about that. Will fix it for the next release.
