### ISSUE TITLE
Recursion in the $instance_datadir makes puppet painfully slow

### ISSUE THREAD

**Issue by vide** [elastic/puppet-elasticsearch#571]
Given a big instance datadir (one of ours for example is about 2.5TB), puppet spends a LOT of time (more than 5 minutes) just doing `stat()`/`lstat()` on all the instance's files. 
Why is this needed? Do we really need to force ownership on this directory's files every time?

Do you need a PR? All you need to do is just delete one single line.

**Comment by electrical** [comment]
Hi, this has been solved in version 0.10.2
Which version are you using?

**Comment by vide** [comment]
Ooops, sorry, we are using an older one, I will upgrade right now. Thanks and sorry for the noise!

**Comment by electrical** [comment]
No worries at all. I'm happy with any issue reports :-)

**Comment by vide** [comment]
Ok, just for the record, now it works smoothly; before: 350 seconds, now: 11 seconds :)

**Comment by electrical** [comment]
Nice! glad to hear the improvements.
