### ISSUE TITLE
Just started to get this error.

### ISSUE THREAD

**Issue by chad-upton** [elastic/puppet-elasticsearch#573]
puppet agent version: 4.3.2
puppet server version: 2.2.1 

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: no parameter named 'ensure' at /etc/puppetlabs/code/environments/production/modules/elasticsearch/manifests/package.pp:48 on File[/opt/elasticsearch/swdl] at /etc/puppetlabs/code/environments/production/modules/elasticsearch/manifests/package.pp:48 on node webapp.local.dev
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

elasticsearch.pp file
```
class sc::logstash (
  $package_url   =  'https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/rpm/elasticsearch/2.1.1/elasticsearch-2.1.1.rpm',
  $instance_name =  'logstash'
) {

  class { '::elasticsearch':
    autoupgrade                       =>  true,
    manage_repo                       =>  true,
    repo_version                      =>  '2.x',
    java_install                      =>  true,
  }
}
```

This seems to be an issue with the `file` type but can't find any reason why.

**Comment by electrical** [comment]
Ah, interesting. Must be one of those puppet 4 changes i missed.

**Comment by electrical** [comment]
Can you also tell me which version of the puppet module you are using?

**Comment by chad-upton** [comment]
The one from the forge.  The latest.  Oddly I only get this error on CentOS 6, my Amazon Linux distribution it doesn't happen.

**Comment by electrical** [comment]
that's weird indeed. Could you rebuild your centos 6 vm?

**Comment by chad-upton** [comment]
I've rebuilt it 3 times, it's a vagrant box so easy to replicate.

Would you like me to make it public so you can try it?

**Comment by philipwigg** [comment]
Is it something to do with the quotes around 'directory' here?

https://github.com/elastic/puppet-elasticsearch/blob/0.10.2/manifests/package.pp#L49

Maybe you could try manually removing the quotes and seeing if that works? Seems like a Puppet bug though...

**Comment by chad-upton** [comment]
So now I feel silly.  I fixed it by rebuilding my puppet server vagrant.

It seems somewhere along the way something didn't get mounted or wasn't available like it should have been after my laptop was put to sleep.

Thanks for the quick responses phillip!

**Comment by electrical** [comment]
No problem at all. I'm glad you found the issue.  Always happy to help.
