### ISSUE TITLE
Exec timeout should default to undef

### ISSUE THREAD

**Issue by alexharv074** [elastic/puppet-elasticsearch#580]
The Exec timeout is defaulting to 600 whereas a user behind a slow network connection is likely to want to set an Exec timeout globally via 

```puppet
Exec {
  timeout => 0,
}

include ::elasticsearch
include ::logstash
include ::kibana4
```

etc

**Comment by alexharv074** [comment]
Conversely, without this fixed up it means that to change the Exec timeout for all of these Elastic.co modules:

```puppet

class { 'elasticsearch':
  package_dl_timeout => 0,
}
class { 'logstash':
  package_dl_timeout => 0,
}
class { 'logstashforwarder':
  package_dl_timeout => 0,
}
```

I hope that makes the motivation for this change a bit clearer.

**Comment by electrical** [comment]
Hi,

I understand the reasoning but the Exec is used in multiple places and makes little sense to have a single overriding setting for all of them.
Having the variable makes it cleaner to set it per module.

**Comment by alexharv074** [comment]
It does in fact make sense to disable the Exec timeout everywhere, even if, as you say, it disables Execs that have nothing to do with downloading software.

If a user ever hits an Exec timeout, in any context, their puppet apply will fail.  However, a puppet apply should never fail, ever.  If there's any real issue in the code, whether a slow software download or other slow command, it should be detected in the CI stage before the code gets to production.  If it does get as far as production, I'm more than happy for puppet to wait forever until someone kills it.  That's no uglier than having Puppet fail with Exec timeout.

Therefore, I recommend always disabling Exec timeouts globally.  I think the PR I've sent is an improvement that shouldn't cause any issues to your users.  However if updating the tests to function with the change is more work than I realised, feel free to decline the PR.

**Comment by alexharv074** [comment]
Anyhow, probably best to close this if there's no interest in the feature.
