### ISSUE TITLE
java_install => true does not work as expected. 

### ISSUE THREAD

**Issue by ravinaik1312** [elastic/puppet-elasticsearch#586]
I am using the **latest version** of the module. 

Below is my configuration file to set up a node with elasticsearch. The node does not have 'java' installed so as per the documentation I used the 'java_install' attribute, but the puppet run errors out. 

**Config file:**
---
classes:
 -elasticsearch

elasticsearch::instances:
&nbsp;es-01:
&nbsp;&nbsp;config:
&nbsp;&nbsp;&nbsp;node.name: 'es-01'
&nbsp;&nbsp;&nbsp;java_install: true
&nbsp;&nbsp;&nbsp;package_url: 'https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.2.noarch.rpm'

Have also tried adding the java_install and package_url under the elasticsearch class instead of under 'instances' like above. 

**Error:**

Error: /Stage[main]/Elasticsearch/Elasticsearch::Instance[es-01]/Elasticsearch::Service[es-01]/Elasticsearch::Service::Init[es-01]/Service[elasticsearch-instance-es-01]/ensure: change from stopped to running failed: Could not start Service[elasticsearch-instance-es-01]: Execution of '/sbin/service elasticsearch-es-01 start' returned 1: which: no java in (/sbin:/usr/sbin:/bin:/usr/bin)
17 Feb 2016 16:34:15,873 | 697017      [ERROR] {Connect thread 52.34.177.30 session} (com.orchestral.continuousdelivery.solution.ssh.SshHandler$SshSession#centos@solution_quickstart_ravin_mbp_graviton-elasticsearch1/52.34.177.30) [solution_quickstart_ravin_mbp_graviton-elasticsearch1] Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME

**Comment by electrical** [comment]
hi, java_install is part of the main class, not of the instances part.

**Comment by ravinaik1312** [comment]
Yeah, that's what I thought and tried in the first place. 

elasticsearch:
&nbsp;package_url: 'https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.2.noarch.rpm'
&nbsp;java_install: true

But since this doesn't work, I tried to incorporate that part in the instances part.

**Comment by ravinaik1312** [comment]
classes:
 - elasticsearch

elasticsearch::java_install: true
elasticsearch::package_url: 'https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.2.noarch.rpm'

elasticsearch::instances:
&nbsp;es-01:
&nbsp;&nbsp;config:
&nbsp;&nbsp;&nbsp;node.name: 'es-01'



Tried this, but getting an error

Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class ::java at /opt/puppet/environments/solution_quickstart_ravin_mbp_graviton/modules/elasticsearch/manifests/init.pp:372

So, it seems that it is taking the java_install: 'true' parameter but it is not able to download/install java. 

I am sure, I'm missing something, any help would be appreciated.

**Comment by electrical** [comment]
Ahh. Seems you are missing the puppetlabs-java module for dependency. I wonder why its not installed. How did you install the elasticsearch puppet module?

**Comment by ravinaik1312** [comment]
So, it seems that if we were to include the java_install => true attribute, we got to have some puppet module that will have java installed on that machine. When I explicitly specify the puppetlabs-java module , java becomes available on that machine and there is no need to specify 'java_install => true'. 

It is confusing because, reading the documentation I thought that if the machine does not have java installed already, including 'java_install => true' will automatically solve the problem. Correct me if I am wrong here, thanks!

If it was just me misunderstanding the documentation, we can go ahead and close this.

**Comment by electrical** [comment]
Hi. You are partially right indeed. If you explicitly state that the java module is included for a node then it installs it and you don't need the java_install flag. But not everyone does or wants that so I added the flag to reduce the number of classes required to define. 
Hope this makes sense.

**Comment by ravinaik1312** [comment]
Correct, but what if I do not specify the java (puppet)module? Initially, it was failing because I did not include a java (puppet)module and added the java_install => true attribute giving the above errors.

**Comment by philipwigg** [comment]
I've added this to the requirements section of the README

**Comment by joshuar** [comment]
Thanks @ravinaik1312 for the report and @philipwigg for the quick PR.  Merged.
