### ISSUE TITLE
class elasticsearch::package fails with strict_variables = true

### ISSUE THREAD

**Issue by simon77** [elastic/puppet-elasticsearch#588]
When running puppet apply with strict_variables = true class elasticsearch::package fails because $exec_environment is undef when not using a proxy.

`if $elasticsearch::proxy_url != undef {
            $exec_environment = [
              'use_proxy=yes',
              "http_proxy=${elasticsearch::proxy_url}",
              "https_proxy=${elasticsearch::proxy_url}",
            ]
          }`

The following else has stopped the error but I'm not sure if this is the correct solution.

`if $elasticsearch::proxy_url != undef {
            $exec_environment = [
              'use_proxy=yes',
              "http_proxy=${elasticsearch::proxy_url}",
              "https_proxy=${elasticsearch::proxy_url}",
            ]
          } else {
            $exec_environment = [
              'use_proxy=no',
            ]
          }`

> strict_variables = true (Puppet master/apply only) — This makes uninitialized variables cause parse errors, which can help squash difficult bugs by failing early instead of carrying undef values into places that don’t expect them. This one has a strong chance of causing problems when you turn it on, so be wary, but it will eventually improve the general quality of Puppet code. This will be enabled by default in Puppet 5.0.

**Comment by jsnod** [comment]
Seeing the same with `$file_source` in `manifests/plugin.pp`.  The var only gets set `if ($source != undef)` but gets referenced in the `elasticsearch_plugin` call below.
