### ISSUE TITLE
When putting Network.host in Config it Doesn't Show up in Elasticsearch.yml

### ISSUE THREAD

**Issue by cpitzak** [elastic/puppet-elasticsearch#592]
What am I doing wrong? I added network.host in the config but when running puppet on the client machine the network.host is not in the elasticsearch.yml

class { 'elasticsearch':
        version => '2.2.0-1',
}
elasticsearch::es01":
         config => {
           'http.cors.allow-origin'                  => '/.*/',
           'http.cors.enabled'                       => 'true',
           'http.cors.allow-credentials'             => 'true',
           'network.host'                            => 'myHost',
           'discovery.zen.ping.multicast.enabled'    => 'false'
         }
      }

**Comment by tylerjl** [comment]
Hi @cpitzak, could you re-open this question on the [Elasticsearch Discourse forums](https://discuss.elastic.co/c/elasticsearch)? We can open an issue if we happen to find an actual bug in the module.

On the topic you create, could you also include the configuration files puppet creates in addition to your puppet manifest? You can tag me directly on the topic under the same handle (@tylerjl) to pull me into the new topic.

Thanks!

**Comment by cpitzak** [comment]
Thanks for the quick response.

I resolved the issue I was having. It was on my side, the elasticsearch puppet module had no problems. My puppet master was failing and falling back on a cache copy of the last known working version of the manifest. I fixed the error and also ran with no caching on fail.

Thanks.
