### ISSUE TITLE
service for debian 8 with initV

### ISSUE THREAD

**Issue by ssanden** [elastic/puppet-elasticsearch#594]
hi,

we use lxc with debian8 and that means the init system provider is "init" - not systemd!
i have trouble to set this up with the puppet-elasticsearch module in version 0.10.3. i tried to enforce the init provider or better yet to completely deactivate the service:

    class { 'elasticsearch':
        java_install      => false,
        package_url       => $elasticsearch_deb,
        status            => 'unmanaged',
        restart_on_change => false,
        init_template     => "elasticsearch/etc/init.d/elasticsearch.Debian.erb",
        service_provider  => 'init',
      } ->
      elasticsearch::instance { 'elasticsearch':
        config => {
          'cluster.name' => $elastic_clustername,
          status         => 'unmanaged',
        }
      }

but i still face systemd errors everytime:

    Info: /Stage[main]/Profile::Logging::Elk/Elasticsearch::Instance[elasticsearch]/Elasticsearch::Service[elasticsearch]/Elasticsearch::Service::Systemd[elasticsearch]/Augeas[defaults_elasticsearch]: Scheduling refresh of Exec[systemd_reload_elasticsearch]
    Debug: /Stage[main]/Profile::Logging::Elk/Elasticsearch::Instance[elasticsearch]/Elasticsearch::Service[elasticsearch]/Elasticsearch::Service::Systemd[elasticsearch]/Augeas[defaults_elasticsearch]: The container Elasticsearch::Service::Systemd[elasticsearch] will propagate my refresh event
    Error: /Stage[main]/Profile::Logging::Elk/Elasticsearch::Instance[elasticsearch]/Elasticsearch::Service[elasticsearch]/Elasticsearch::Service::Systemd[elasticsearch]/Exec[systemd_reload_elasticsearch]: Failed to call refresh: Could not find command '/bin/systemctl'
    Debug: Puppet::Type::Service::ProviderSystemd: file systemctl does not exist

am i going wrong somewhere or is this a bug? any help is very appreciated. thanks.

**Comment by tylerjl** [comment]
If you take a look at the lines around [defining the `service_provider`](https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/init.pp#L280), you'll see that the module is restricting the service module based upon what type of services the distribution supports (based on `params.pp`.) Debian 8 only supports systemd at the moment.

Right now, using init in place of systemd in Debian 8 is pretty undefined, so that'd be a feature we'd need to add.

**Comment by ssanden** [comment]
thank you, for the quick response, @tylerjl 
changing the params.pp did the trick - it now runs without errors. the (init) service also works out of the box when i tried manually. i therefore consider this issue as closed.

still, i would expect the service not to be touched - and especially not to fail - when configured as 'unmanaged'. since that may be of interest, you may want to consider adding it.

thanks again. bye!
