### ISSUE TITLE
empty elasticsearch.yml on ubuntu 14.04

### ISSUE THREAD

**Issue by tobiasschaber** [elastic/puppet-elasticsearch#603]
Hey guys,

I'm currenty trying to install elasticsearch with this great module on Ubuntu 14.04.
Before that, I've install it on CentOS 7.1, everything works fine and elasticsearch is installed and running without problems.

Now I tried to perform this installation on Ubuntu 14.04.
The installation process finishes completely without any errors, and elasticsearch is installed on the machine. But there is no elasticsearch.yml under /etc/elasticsearch or at any other location.

I compared the installation logs of the CentOS and Ubuntu installations and found that the (working) CentOS installation continues at a point with a datacat creating the elasticsearch.yml where the Ubuntu installation finishes the installation.

For me this seems similar to https://github.com/elastic/puppet-elasticsearch/issues/597, because
I've also seen that the puppet version is 3.4.3 on Ubuntu and 3.8.6 or such on CentOS, but I can't get 3.8.6 running on Ubuntu 14.04.

Considdering the elasticsearch support matrix (https://www.elastic.co/support/matrix) it seems that 14.04 is the latest supported Ubuntu version which therefore should work.

Do you have any solution for me?

Thank you and kind regards,

Tobias

**Comment by fennnec** [comment]
to update to puppet 3.8.6 you could use the official puppetlabs repository

deb http://apt.puppetlabs.com trusty main

**Comment by tobiasschaber** [comment]
Hey!

wouldn't it be better if the installer fails if the installation can not be completed due to a missing or not correctly working software?

**Comment by tylerjl** [comment]
Hey @tobiasschaber,

Yeah, it looks like a puppet version issue. For what it's worth, I'm running tests against 14.04 on puppet 3.8.6 and things work correctly.

Regarding installer failure, I agree with you, but the minimum required puppet version probably belongs in the [datacat module](https://github.com/richardc/puppet-datacat)'s metadata file to more accurately reflect what modules are compatible with which versions of puppet.

**Comment by tobiasschaber** [comment]
Thanks @tylerjl and @fennnec  I got it running with puppet 3.8.6, and opened a ticket at the datacat project concerning the dependencies.

Kind regards,

Tobias
