### ISSUE TITLE
Error while evaluating a Resource Statement

### ISSUE THREAD

**Issue by dcroonen** [elastic/puppet-elasticsearch#616]
Hi

Since we upgraded our Elasticsearch Puppet module from version 10.0.1 to version 10.0.3 we are experiencing multiple times a day failed Puppet runs on our Elasticsearch servers. The failed message is always the same:

Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/elasticsearch_plugin: Could not autoload puppet/provider/elasticsearch_plugin/plugin: undefined method `[]' for Facter:Module at /etc/puppetlabs/code/environments/production/modules/elasticsearch/manifests/plugin.pp:134:7

We are running PE 2015.3.3. Also notable is that a succesfull Puppet run on these hosts takes a large amount of time up to 300 seconds and more.

Somebody any idea what could cause these errors?

Kind regards
Davy

**Comment by philipwigg** [comment]
At a guess, this was fixed in https://github.com/elastic/puppet-elasticsearch/commit/61a52fb740f930c003f2cc13be3e6ab29a2569fe but there's been no release since then.

Maybe you could try the latest master?

**Comment by dcroonen** [comment]
I applied the fix manually and I can confirm this will solve the error. Looking forward to a next release. Thanks for pointing us in the right direction.

**Comment by tylerjl** [comment]
Thank you for reporting back @dcroonen - I'll make sure to make note that the changeset fixes this bug in the release changelog. 👍
