### ISSUE TITLE
Elasticsearch 5.x Support

### ISSUE THREAD

**Issue by tylerjl** [elastic/puppet-elasticsearch#623]
This issue serves as a central spot to enumerate compatibility fixes that need to be done to support the breaking changes in the 5.x series.
- [x] `bin/plugin` [changes](https://www.elastic.co/guide/en/elasticsearch/plugins/master/installation.html) (now under `bin/elasticsearch-plugin`)
- [x] Several tests use the `"string"` field mapping; `string` [has been replaced](https://www.elastic.co/guide/en/elasticsearch/reference/master/string.html) by either `keyword` (for non-analyzed fields) and `text` (for large analyzed fields)
- [x] Ensure there's no fallout from a change which [removes the cluster name from the data path](https://github.com/elastic/elasticsearch/pull/18554)
- [x] Repository URLs have changed for yum/apt
- [x] Certain command-line JAVA_OPTS parameters (https://www.elastic.co/guide/en/elasticsearch/plugins/master/_other_command_line_parameters.html#_proxy_settings) - all `-Des.*` settings need to be replaced with `-E*`
- [x] Handle management of the 5.x logging configuration file, `log4j2.properties`

**Comment by nelg** [comment]
where are we upto with this?  now that Elastic search 5.0 is GA, it would be helpful to deploy it with Puppet.

**Comment by tylerjl** [comment]
The main blocker right now is that last item, wherein Elasticsearch command-line options need to be translated from `-Des.*` to `-E*` for all versions >= 5.x. I don't have any fixes in the pipeline right now, though I'll be looking to fix that when I get some time to give the module some attention (PR's are also welcome).

**Comment by LordBonkerz** [comment]
bummer!  smashed up my elasticsearch cluster due to me thinking this would work with ver5.

**Comment by edestecd** [comment]
I think the rpm / deb repo urls are different now also.

**Comment by tylerjl** [comment]
I'm going to see if I can't knock this out. The repository URLs are an easy fix, but I'm going to have to go with one of two options for changing the Java options:

1. Implement some sort of solution with a native type/provider in order to access the `Package[elasticsearch]` type's `version` parameter. This is the "most correct" option since Puppet is managing the package natively and can find out the version of the installed package through normal means.
2. Hack around it by looking at the `repo_version` or package URL and trying (with a regex?) to guess at the Elasticsearch version to use the correct flags.

Option 1 is the preferable option, but I honestly do not know how I would do that. From within a native provider, I can call `@resource.catalog.resource('Package[elasticsearch]').provider.properties[:version]` and get a known, reliable, installed version number across distros, but because templates are evaluated at catalog compilation time, and the provider can get called mid-run on an agent (and thus can't be relied upon when writing the template), using this method call to write the right flags isn't straightforward.

Option 2 _should_ be workable, and it's probably the  route I'll take, but I'm wary of the implications down the road given that the init script content will rely upon a regex to parse a version from a few potential sources in the module.

/cc @jarpy here, I'd be curious if you have other potential solutions. I'm going to see what option 2 looks like for the time being.

**Comment by nelg** [comment]
Yesterday I had a play with Elastic Search 5 and the puppet module, my findings are:

new files, jvm.options and log4j.properties probably need to be copied into the instance directory, for each instance type.

JVM memory ideally should then be set with jvm.options  - although it seemed to be ignored - anyone know how it works?

The augeas component that writes the /etc/sysconfig/elasticsearch-instancename
file needs to not write CONF_FILE, as this file is I think not compatible with Elastic Search 5.  See the default init script even has a elasticsearch-systemd-pre-exec script which checks to see it's not set.

WorkingDirectory needs to be set in the systemd startup for an instance I think

Checks must be in place, because WORK_DIR, CONF_DIR, DATA_DIR and LOG_DIR variables cannot be empty, elastic search won't start with empty values

A number of other params are in the standard systemd file, that maybe should exist in the instance version, such as:

TimeoutStopSec=0
KillSignal=SIGTERM
SendSIGKILL=no
SuccessExitStatus=143

**Comment by nelg** [comment]
The alternative, I used because jvm.options seems ignored, was to set ES_JAVA_OPTS in /etc/sysconfig/elasticsearch-instance

**Comment by fluggo** [comment]
Don't forget that bootstrap.mlockall changed to bootstrap.memory_lock. You also can't set the default scripting language or index parameters in elasticsearch.yml, and Elasticsearch won't start if it sees logging.yml in its config directory.

From personal experience.

**Comment by jarpy** [comment]
I would be more inclined to create a new major version of the module that sacrifices backward compatibility for simplicity. The module could even be released as "version 5" to make explicit which version of Elasticsearch it supports in a really obvious way that is aligned with the versioning scheme of the Elastic products themselves.

Maintaining backward compatibility clearly means more conditional logic/more complexity that will grow over time. I think there is a definite threshold at which the benefits of simplicity and maintainability outweigh the advantages of backward compatibility. Where that threshold lies is, of course, not a provable fact, but a matter of taste. For me, now is an excellent time for a new major version which would allow the shedding of a good deal of conditional complexity.

I like the user story that says "Elasticsearch v5? Use the version v5 Puppet module". I also like the stability that this could offer to people who will be running pre-v5 Elasticsearch versions for a while. A new major version would enable aggressive refactoring and API changes where appropriate, without breaking people's v2 clusters as they track minor fixes in the (relatively static) V2 compatible module.

**Comment by jarpy** [comment]
I'd be more inclined to release a new major version that sacrifices backward compatibility for simplicity. As more conditional logic is added, any code base gets harder to read, maintain, and test. I believe there is a threshold somewhere at which conditional complexity costs more than the value of backward compatibility. While the location of that threshold is not a provable fact, but of course, a matter of taste, I think now is a great time to consider a new major version. It could even be labeled as "version 5" of the module, making it immediately obvious which version of Elasticsearch it's intended for, and aligning the versioning with the core Elastic products themselves.

I like the user story that says: "_Elasticsearch v5? Use the v5 Puppet module_". I also like the stability that this could offer people who will be running v2 clusters for a while yet. A new major module version could enable aggressive refactoring and API changes, without breaking things for people who are tracking minor fixes to the (now relatively static) v2 Puppet module branch.

**Comment by jarpy** [comment]
Apologies to those who are watching this issue and received roughly the same message from me twice! I thought that GitHub had black-holed my first, lovingly crafted attempt. 😖

**Comment by lucabelluccini** [comment]
I would share my point of view...
Puppet is done for automation. Breaking change and no backward compatibility means potential manual tasks to be performed.
Indeed, if you are handling a small cluster and you have no strong constraint on outages, this is fine.

I think developing a separated module can be interesting, but everything should be wrapped by a "meta" puppet module which will include the 2.x or 5.x depending on the version we are willing to use.

**Comment by rcalixte** [comment]
@tylerjl I've been mucking with this a little bit. Would it make sense to add another fact to Facter named elasticsearch_version and leverage that globally? I can PR an example of what I'm thinking if it would help. With this fact and the repo_version parameter, this should cover all bases for the remaining downstream configs right? This would allow for maintaining backwards compatibility with 2.x while allowing us to make the necessary changes for 5.x.

**Comment by tylerjl** [comment]
@rcalixte a fact would be great, but there are issues with that solution: from what I understand, facts are loaded at puppet start time (before catalog compilation) and thus if Elasticsearch is not installed, the fact won't be populated for any clean install of Elasticsearch using this module. You mention `repo_version`, which would help, but there are lots of other was people can install Elasticsearch without relying on the repository (for example, just passing a deb/rpm to `package_url`) so there are a couple of different sources that the Elasticsearch package can come from.

That being said, if there is some way to "delay" the loading of a fact until it's absolutely necessary (that is, by the time the package has been installed) then that might provide a way to get the package version consistently. Bear in mind that the current way init scripts are written would have to be changed, though, since any calls to `template()` happen on the puppetmaster at catalog compile time and would have to be delayed until later in the puppet run.

(For those following; @jarpy and I spoke offline about this, and I'm going to see what a backwards-compatible fix looks like, but we're not writing off the idea of separate branches for the module. This solution has the potential to look like just a big list of different versions on the Forge like 1.0, 2.0, 5.0, and so on, so you'd need to retrieve the right branch of this module for the version of Elasticsearch being used.)

**Comment by rcalixte** [comment]
@tylerjl I haven't tested this yet but it seemed promising if it works (https://github.com/hercynium/puppet-refacter). I'd love to find a solution that allowed 2.x users to upgrade to 5.x (and beyond).

While I'm not 100% opposed to having to use a different module version for each corresponding version of Elasticsearch, this might become cumbersome if there are things in 5.1 or if 6.0 comes out but isn't horribly different, etc.

**Comment by tylerjl** [comment]
@rcalixte by all means, do feel free to experiment! PR a solution if you find something that works well and we can brainstorm solutions. puppet-refacter looks potentially useful, though we should vet it thoroughly as it hasn't been updated in over three years and mentions it may not work with Puppetmasters.

**Comment by pythianali** [comment]
Out of curiosity, in many of the webinars and in Elastic training, configuration management is the recommended way to deploy Elasticsearch.  So the question is, which tool is the one Elastic actually uses and supports for their own purposes?   Seems the chef cookbook is getting some love regarding 5.0 support: https://github.com/elastic/cookbook-elasticsearch.   Is chef what you guys prefer to use in general?

**Comment by tylerjl** [comment]
@pythianali configuration management or devops tools of any form are certainly recommended for managing deployments of Elasticsearch. Internally, we dogfood [Elastic Cloud](https://www.elastic.co/cloud) heavily, as it serves our needs well.

When it comes to "which ops tool do you recommend to use with Elasticsearch?", there's no other reasonable answer than "it depends". If your operations team is familiar with and using Puppet, then by all means, use the Puppet module. If you're a Chef shop, then leverage the experience of your team to make use of the Chef cookbook. Same goes for the Docker images; etc. - there's not a degree of favoritism in regards to support across the tools.

Though the module is lagging behind 5.x at the moment, rest assured time is being taken to make the module safe to use, backwards compatible, and supportive of future releases moving forward.

**Comment by stregatto** [comment]
Perhaps I'm working in the wrong direction, but I wrote a little patch to experiment the v5 compatibility:
https://github.com/stregatto/elasticsearch/blob/master/es_v5.patch

**Comment by tylerjl** [comment]
Hi @stregatto - note that if we wanted to derive the major version number from top-level parameters, there's a few different sources that the package can be installed from, including `package_url`. You can see an experiment I went with [here](https://github.com/elastic/puppet-elasticsearch/compare/master...tylerjl:5.x-java-opts) to try and take the same approach - though the solution [here](https://github.com/elastic/puppet-elasticsearch/commit/802a7faa4ab745d4713b50162d3ab465c74d4fdc) seems to be more reliable by pulling out the version number natively from a `Package[elasticsearch]` resource.

**Comment by smougenot** [comment]
As a matter of fact, releasing those fixes are IMO worth doing.
- actual version 0.14.0 deploys only elasticsearch package 5.0.0_alpha5-1
- OS specific repos are using wrong urls (ugly if someone wants to update)

Consequently, for user wanting to use ES 5.x this module is not production ready.
(as a devops concerned user ... I don't want to update Puppet code outside of a release)

So could someone tell us if a release is on the way.

**Comment by stregatto** [comment]
@tylerjl Yes of course my approach is little naive, only a test to check all the component, like logs, init and plugins , also there is a bug in a plugin management for ver > 2.3 (but perhaps another topic).
Perhaps, guess the package info from the name of the package is imho is not the right way. In my idea is int the user the choice of version of the package

**Comment by CoaxVex** [comment]
Managing jvm.options should probably also be in scope. I just tried this on vagrant, and ran into "Execution of '/bin/systemctl start elasticsearch-es-01.service' returned 1: Job for elasticsearch-es-01.service failed because a configured resource limit was exceeded"

**Comment by tylerjl** [comment]
@smougenot, I'll be releasing as soon as I merge in #733, which should make the 5.x changes compatible with OpenBSD.

@stregatto as of this writing, the 5.x code in the module pulls the version out of the `package { 'elasticsearch' : }` Puppet resource, which seems to work correctly. I'm always open to refactoring how that works in the future though if we come up with a better way.

@CoaxVex I agree that file should probably be managed - though I'll probably leave that for another issue since my testing seems to work correctly without that file under puppet management and these changes need to get out soon. We do need to manage it at some point, though.

**Comment by pythianali** [comment]
> Execution of '/bin/systemctl start elasticsearch-es-01.service' returned 1: Job for elasticsearch-es-01.service failed because a configured resource limit was exceeded"

I ran into this same issue also with Vagrant

**Comment by tylerjl** [comment]
This has been released in version 0.15.0. For additional features/bugfixes to support other parts of 5.x, please create an issue and we can iterate on additional needs as they come up.
