### ISSUE TITLE
Ability to manage multiple CAs?

### ISSUE THREAD

**Issue by fgimian** [elastic/puppet-elasticsearch#641]
Allo again, sorry for creating two issues in one day 😄 

In certain circumstances (such as ours), we require 2 CAs to be placed into the truststore for us.  This is because we have:

* 1 CA we created ourselves for Elasticsearch and communication among nodes
* 1 CA provided to us for authenticating against our LDAP server

Is this something that could be supported or would it be a huge task?

Thanks a lot
Fotis

**Comment by tylerjl** [comment]
This should be possible, as the [module seems to indicate](https://github.com/puppetlabs/puppetlabs-java_ks#namevars) you just need to define multiple certificates for the keystore in question.

This will probably involve turning the `elasticsearch::instance::ca_certificate` into an array and then adding all those certificate paths to the keystore that gets built up for the instance.

**Comment by fgimian** [comment]
Cool, I can give that a go and see if passing an array does the trick with the current codebase.  I'll keep you posted on this and perhaps we can add a note about it to the docs if it works 😄

**Comment by fgimian** [comment]
Hey buddy, sadly this doesn't work for me:

e.g.

```puppet
  elasticsearch::instance { 'master-node':
    # Enable SSL and configure certificates for Shield
    ssl               => true,
    ca_certificate    => [
      '/etc/elasticsearch/cacerts/My-Root-CA.crt',
      '/etc/openldap/cacerts/LDAP-Root-CA.pem',
    ],
    certificate       => '/etc/elasticsearch/certs/example.com.crt',
    private_key       => '/etc/elasticsearch/certs/example.com.key',
    keystore_password => $keystore_password,
    ...
```

Output:

```
Error: /Stage[main]/Profile::Elasticsearch::Master_node/Elasticsearch::Instance[master-node]/Java_ks[elasticsearch_instance_master-node_keystore_ca]/ensure: change from present to latest failed: can't convert Array into String
```

Any ideas?
Fotis

**Comment by fgimian** [comment]
Looks like this won't work mate, you need multiple `java_ks` definitions, one per CA or cert.  As such, I think it's best if I just manage my own keystore due to my more complex requirements.  This also allows me to share the ks with my Marvel instance since the certs are the same.

Huge thanks for your help.  If you have nothing else to add, feel free to close this one off 😄

**Comment by tylerjl** [comment]
Sorry, I wasn't clear - I meant we'd have to modify the module to accept multiple certificate PEM files, but if you're happy just managing the keystore files manually, then that's totally fine as well. Given that `java_ks` is a dependency of this module now, using it should be pretty straightforward since it gets pulled in already.

Let me know if the situation changes for you (or anyone else following this issue) and we need to have multiple certificates supported and we can certainly revisit this issue if needed. 👍
