### ISSUE TITLE
Manage Shield with Hiera

### ISSUE THREAD

**Issue by lfacchinelli** [elastic/puppet-elasticsearch#648]
Hi guys !
I've using your module at work a couple of days ago and seems like you cannot use shield with hiera.
So I made a few tweaks on the code to be able to use hiera.

May I create a pull request to solve this issue ?

**Comment by tylerjl** [comment]
Certainly! Just check out [CONTRIBUTING.md](https://github.com/elastic/puppet-elasticsearch/blob/master/CONTRIBUTING.md) to help get you started. Any tests you write to help validate the functionality you're adding would be a great help as well.

Thank you for your willingness to contribute! 👍

**Comment by cdenneen** [comment]
@lfacchinelli I'd be interested to know what you mean. I'm using hiera for almost everything.

**Comment by lfacchinelli** [comment]
@cbuescher And are you using hiera to set shield user and roles ? Without touching anything in the module ?

**Comment by cbuescher** [comment]
@lfacchinelli just got mentioned by you, maybe by mistake? Not sure what this discussion is about really, sorry.

**Comment by lfacchinelli** [comment]
@cbuescher UPS! my bad ! 

@cdenneen The original post was for you :-)

**Comment by cdenneen** [comment]
@lfacchinelli yes in my profile::elasticsearch I'm just creating those resources from hiera.

**Comment by lfacchinelli** [comment]
@cdenneen Can you show me an example ? Probably i'm doing it wrong

**Comment by cdenneen** [comment]
```yaml
my_esusers:
  admin:
    password: 'changeme'
    roles:
      - 'admin'
```
```puppet
$es_users = hiera_hash('my_esusers',{})
create_resources(elasticsearch::shield::user,$es_users)
```

That's probably the quickest example... 
I usually use naming like:
```yaml
profile::elasticsearch::es_users:
  admin:
```
for cleaner naming but you should get the general idea.

**Comment by lfacchinelli** [comment]
@cdenneen Well , in that example you are coding in order to support hiera. 
My post was about including hiera support by default, without coding anything else.

**Comment by cdenneen** [comment]
I do hash lookups in order to merge across hierarchy, which doesn't work with APL.
If you use:
```puppet
class profile::elasticsearch($es_users){
  include ::elasticsearch
  create_resources(elasticsearch::shield::user,$es_users)
```
it does it without the additional hiera_hash lookup because its explicit in the APL.
You are going to have to include the class and types somewhere in code (hopefully a profile) so this is where it gets done. 
if your suggesting adding `elasticsearch/manifests/shield/users.pp` which contains basically:
```puppet
class elasticsearch::shield::users {
  create_resources('elasticsearch::shield:user',$elasticsearch::esusers_hash)
}
```
There is some contention to this model, one of the reasons there is no `elasticsearch::plugins` as a similar wrapper for `elasticsearch::plugin` because you should be including this as needed vs having module forcibly create. Also when it comes to hash merging across hierarchy, the APL here described doesn't work. So you'd end up having to create your own variable and pass that to create resources anyway.

**Comment by tylerjl** [comment]
As @cdenneen has noted, making a call to `create_resources` is similar to how I've consumed hiera structures in the past for defined types. Thanks for the clarification, btw. 👍 

@lfacchinelli do you have an example of what you're proposing would look like is the `create_resources` approach doesn't work for you? There's always the option to add a parameter to the elasticsearch class like `elasticsearch::shield_users` which you can inject via hiera (and the module can call `create_resources` with), but as @cdenneen mentioned, there's a significant loss of flexibility there as you can't merge the hiera structures that easily so you lose some of the benefits of hiera with that approach anyway.

**Comment by skade** [comment]
I'm not sure how much benefit that would add. e.g. we have automated password management on top of all that, so we will load from both hiera and a password store. I see no issue with having retrieval from hiera and create_resources be two lines. The approach of speaking directly to hiera also means a hidden interaction in the background.

**Comment by tylerjl** [comment]
This should be natively supported with the addition of #813.
