### ISSUE TITLE
No support for path.repo for managing snapshots

### ISSUE THREAD

**Issue by chris1879** [elastic/puppet-elasticsearch#649]
Hi!

There is no puppet support for the "path.repo" setting. We would need it for creating
ES snapshots. It should be part of the elasticsearch.yaml (like data, or logs) or as a parameter for the daimon process. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html

best regards
Christian

**Comment by tylerjl** [comment]
Hi @chris1879,

Every setting in the `elasticsearch.yml` config should be settable with the `config` parameter, so controlling `path.repo` would be a matter of:

```puppet
class { 'elasticsearch':
  config => { 'path.repo' => ['/path'] }
}
```

Or as a parameter on an  `elasticsearch::instance`, depending on how you're configuring instances.

Does that meet the requirement you're outlining here, or am I misunderstanding the feature you're describing?

**Comment by chris1879** [comment]
Hi tylerjl,

I think this is it, what I have ment. Thanks for your explaining.

best regards
