### ISSUE TITLE
Network host of "::" leads to invalid YAML

### ISSUE THREAD

**Issue by hansmi** [elastic/puppet-elasticsearch#650]
Setting `network.host` to `::` (the IPv6 bind-all address) causes `elasticsearch.yml.erb` to write YAML in a format Elasticsearch can't parse.

Puppet configuration:
```
class { '::elasticsearch':
  …
  config => {
    'network.host': '::',
  },
}
```

Result in configuration file:
```
network:
  host: ::
```

Error message:
```
Exception in thread "main" SettingsException[Failed to load settings from [elasticsearch.yml]]; nested: ScannerException[mapping values are not allowed here
 in 'reader', line 17, column 10:
      host: ::
             ^
];
Likely root cause: mapping values are not allowed here
 in 'reader', line 17, column 10:
      host: ::
```

**Comment by hansmi** [comment]
For my specific case I could work around the issue by double-quoting:

```
config => {
  'network.host': '"::"',
},
```

**Comment by tylerjl** [comment]
Thanks for the report @hansmi, that's a little unexpected but makes sense.

I don't think there's a bug anywhere in the elasticsearch.yml template or in the to_yaml code, but I agree that the behavior is unexpected from a user perspective.

We could probably try and catch odd yaml formatting, though it'd be a very case-by-case basis and the code would have to look pretty specifically for tokens have been observed to cause problems (like `::`).

**Comment by hansmi** [comment]
@tylerjl, wouldn't it be more sensible to serialize strings per the YAML specification rather than including them raw?

See, for example, what Python does:
```
$ python -c 'import yaml; print yaml.dump(["foo:", {"bar": True, "key": "{bar: True}", "host": "::"}, "\n\t\n"], default_flow_style=False)'
- 'foo:'
- bar: true
  host: '::'
  key: '{bar: True}'
- "\n\t\n"

```

**Comment by tylerjl** [comment]
@hansmi yes, though I forgot to take into account what version of the module you're using. The changes in #635 change the template to use the native `to_yaml` rather than the custom yaml generation code, which should actually quote special values like `::` (at least it did so in the test I ran).

The updated yaml template code hasn't been released yet, but it's on `master` so feel free to verify whether the updated template code works for you.

**Comment by hansmi** [comment]
@tylerjl, we're using version 0.11.0, the latest release as of this writing. I can confirm that current master (revision `ccb59c6`) quotes the string properly:

```
network: 
  host: "::"
```

As far as I can tell this issue can be considered fixed once this changed quoting behaviour is part of a release.

**Comment by trevor-vaughan** [comment]
You might also want to try adding square brackets around your entry and testing that. This is the standard method for identifying ipv6 addresses and will also generate invalid YAML. The suggested patch should fix the issue but both scenarios should be tested.

**Comment by tylerjl** [comment]
Agree with the comments here; FYI I've added a small test to the template unit tests to verify that the template to_yaml code properly quotes IPv6 values in fa88347a4.

**Comment by tylerjl** [comment]
Latest released version has the fix.
