### ISSUE TITLE
elasticsearch::config has a non functional path

### ISSUE THREAD

**Issue by trevor-vaughan** [elastic/puppet-elasticsearch#653]
This line https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/config.pp#L42 is invalid since elasticsearch::service is now a define.

I'm not sure if you meant to actually make it a define as it makes it *extremely* difficult to trigger service restarts.

Also, the elasticsearch::service class (if it should be that) should `contain` the subclasses so that any external notification events propagate through to the service restarts. As it stands, it is impossible to reliably trigger a restart of the ES service from outside the ES module since the names are dynamically generated.

**Comment by tylerjl** [comment]
Good catch; I actually came across this while refactoring `restart_on_change` in a feature branch I'm getting ready to merge. I [fixed it in there](https://github.com/tylerjl/puppet-elasticsearch/commit/45bf57db4cd0378b5888b46ad22b921c09118379) so it should be landing in master once it's ready.

In regards to the second item regarding notifying instance services, do you have an example of what you'd like to see exposed in the module? I'd imagine most people are doing something like

```puppet
elasticsearch::service { 'example' : subscribe => $foo }
# or
Elasticsearch::Service { subscribe => $foo }
# or
Exec['thing'] ~> Service['elasticsearch-instance-example']
```

Or some variation. What would make it more usable for you?

**Comment by trevor-vaughan** [comment]
If I'm making changes that require ES to be restarted, say something like updates to SELinux contexts on  relocated data directories, I need some way to restart *all* of my instances without knowing what they are (i.e. if you're generating them via Hiera).

**Comment by tylerjl** [comment]
Would the above example using resource default statements

```puppet
Elasticsearch::Service { subscribe => $foo }
```

Work in that case? Defining the resource default doesn't require knowledge of the instance names beforehand and should let you subscribe to any arbitrary resource you want to watch (I don't _think_ the plussignment operator needs to be used here). It may need to be defined somewhere early in the manifests before `create_resources` (or what else you may be using) gets called since Puppet ordering is weird, but I think it should work.

**Comment by trevor-vaughan** [comment]
No, this would not work because the Elasticsearch::Service defines don't propagate to the internally called defines.

So, for instance, you have Elasticsearch::Service::Systemd. This would not get a notification based on the suggested code and this is what *actually* needs to get the notification.

**Comment by tylerjl** [comment]
Hmm, so I tested this on CentOS 7 and Ubuntu 14.04 (systemd and SysV init, respectively). The following manifest:

```puppet
class { 'elasticsearch':
        java_install => true,
        manage_repo => true,
        repo_version => '1.7',
}
notify { 'forced notify' : }
elasticsearch::instance { 'es-01': }
Elasticsearch::Instance { subscribe => Notify['forced notify'] }
```

Properly restarted the elasticsearch service with each `puppet apply` (not just the top-level defines but the actual system service and ES process). I could understand if it wasn't notifying if the defines were including classes at any point, but it's `define`s all the way down so the containment seems to be behaving as expected. Do you have an example (Puppet version, distro + version, etc.) where it doesn't behave like this?

**Comment by trevor-vaughan** [comment]
My fault, I had a bug that was causing an issue. Wrong and loud on the Internet points +1!

Thanks

**Comment by tylerjl** [comment]
Relevant dead line removed as of #655
