### ISSUE TITLE
Instance hash merges are non-deterministic on EL6 systems

### ISSUE THREAD

**Issue by trevor-vaughan** [elastic/puppet-elasticsearch#654]
On line https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/instance.pp#L377 using puppetlabs-stdlib 4.8.0, the merge of the passed hashes are non-deterministic.

This is using the latest system Ruby 1.8.7.

With this, the results of /etc/elasticsearch/simp/elasticsearch.yml based on the simple call to elasticsearch::instance { 'simp': } causes the following output to flip at random:

```
diff elasticsearch*.yml
22c22
<   name: el6-server.int.localdomain
---
>   name: el6-server-simp
24c24
<   data: /usr/share/elasticsearch/data/simp
---
>   data: /var/elasticsearch
```

**Comment by tylerjl** [comment]
Eugh, that's a gross bug. I reproduced this on `master` on CentOS 6 with the following:

```puppet
class { 'elasticsearch':
        java_install => true,
        manage_repo => true,
        repo_version => '1.7',
        config => {
                'node' => {
                        'name' => 'top-level',
                }
        }
}
elasticsearch::instance { 'es-01':
        config => {
                'node.name' => 'es-01',
        },
}
```

It flips basically every time. I'll probably work this into the configuration hash refactor as a part of #633 when I change `elasticsearch.yml` to be flattened.

If anyone needs a workaround in the interim, note that defining configs without different hash structures makes the keys consistent, i.e. replacing the above config with

```puppet
class { 'elasticsearch':
        java_install => true,
        manage_repo => true,
        repo_version => '1.7',
        config => {
                'node.name' => 'top-level',
        }
}
elasticsearch::instance { 'es-01':
        config => {
                'node.name' => 'es-01',
        },
}
```

Makes the `instance` config take precedence.

**Comment by trevor-vaughan** [comment]
Your workaround is functional but is probably going to mess up people using Hiera stacks to push their data in.

Will look for the upcoming fix.

Thanks for being so responsive!

**Comment by tylerjl** [comment]
Latest version release has the fix. Happy puppeting!
