### ISSUE TITLE
File mode error with puppet 4.5.2

### ISSUE THREAD

**Issue by shine60vn** [elastic/puppet-elasticsearch#661]
Hi guys, I got an error when trying to run `puppet apply`
> Error: Parameter mode failed on File[/opt/elasticsearch/swdl]: The file mode specification must be a string, not 'Fixnum' at /path/to/modules/elasticsearch/manifests/package.pp:52

I guess there are many people here who tested `puppet-elasticsearch` with puppet 4.5.2. Anyone faced this issue before?
Below is my manifest, very simple and basic ;)
```ruby
class { 'elasticsearch':
  manage_repo  => true,
  repo_version => '2.x',
  java_install => true,
}

elasticsearch::instance { 'xx-01':
  config => {
    'network.host' => '0.0.0.0',
    'index.number_of_shards' => 4,
  }
}
```

**Comment by tylerjl** [comment]
Thanks for the report, @shine60vn. What OS/version are you on, and what version of the module is this occurring with?

**Comment by shine60vn** [comment]
Thanks for your reply, @tylerjl . I'm using Ubuntu 14.04 Trusty and latest version of module 0.11.0. I faced with this problem on every module which use `file` resource type and without explicit `mode` attribute not only `elasticsearch` module.

**Comment by tylerjl** [comment]
Thanks. The error messages makes sense, but within the context of this module I'm confused why it's being raised. 0.11.0 doesn't pass any explicit calls to `mode =>` with integers, strings are used everywhere already, so I don't even know where in the code a changed to quoted numbers would be necessary. Do you perhaps have a resource default somewhere in your manifest (like `File { mode => 755 }`)? Otherwise I'm not sure what change needs to happen to resolve this issue.

**Comment by shine60vn** [comment]
I have the same thinking with you, the error should not be thrown because I did not define any resource default parameters like you mentioned. I've also tried to add `File { mode => "0644"}`, it did not work, too. Which version of Puppet 4 have you tested?

**Comment by tylerjl** [comment]
I just ran a test on Ubuntu 14.04, using version 0.11.0 of the module on puppet 4.5.2 and your manifest worked successfully for me in a VM environment.

At this point I'm not really sure where the problem may lie. Unless there's some reliable way to reproduce what you're seeing, it may be some part of your environment that's configured in some odd way?

**Comment by jarpy** [comment]
Maybe a quick:

```
grep -r 'mode * =>'
```

will turn up something odd?

**Comment by shine60vn** [comment]
As @tylerjl commented and a tip from @jarpy, the root cause come from a line in my manifest file which was copied from dev env using puppet 3. Many thanks to you guys 👍 !
