### ISSUE TITLE
Elasticsearch::config doesn't support Hiera merge_behaviour: deeper

### ISSUE THREAD

**Issue by pietervogelaar** [elastic/puppet-elasticsearch#662]
At the moment there is no support for the Hiera setting "merge_behaviour: deeper" when using the property "elasticsearch::config".

Please support this just like "elasticsearch::instances" and "elasticsearch::plugins" that DO have deeper support.

**Comment by cdenneen** [comment]
@tylerjl this would be useful for the init_defaults as well.
