### ISSUE TITLE
Could not back up files of type characterSpecial when masking  '/etc/systemd/system/elasticsearch.service'

### ISSUE THREAD

**Issue by danieloa** [elastic/puppet-elasticsearch#677]
* Module version: "0.12.0"
* Puppet version: 3.8.6
* OS and version: CentOS 7.1 && CentOS 7.2

## Bug description
after initial installation, every puppet run fails in 
    if ($elasticsearch::service_providers == 'systemd') {
      # Mask default unit (from package)
      file { '/etc/systemd/system/elasticsearch.service':
        ensure => link,
        target => '/dev/null',
      }
    }
with 
Error: Could not back up files of type characterSpecial
Error: /Stage[main]/Elasticsearch::Config/File[/etc/systemd/system/elasticsearch.service]/ensure: chang
e from characterSpecial to link failed: Could not back up files of type characterSpecial
---
Even including inside site.pp a File resource definition to disable backup, the error still shown

**Comment by tylerjl** [comment]
Interesting - just to help with debugging this, do you have any details on the file `/etc/systemd/system/elasticsearch.service` from one of your systems? As in, what the contents are, what `file` says it is, `ls -la` for the file, etc.

**Comment by danieloa** [comment]
Hi,
its just a normal simlink to /dev/null... nothing special on it. 

[root@hostname ~]# ls -la /etc/systemd/system/elasticsearch.service 
lrwxrwxrwx. 1 root root 9 Aug  4 13:14 /etc/systemd/system/elasticsearch.service -> /dev/null

I also been thinking that could be a problem of the puppet agent itself not 'understanding' the link to /dev/null. Might be worth to just 'ensure => absent' instead of masking it ? 

thanks and let me know how i can help further.
cheers
daniel

**Comment by tylerjl** [comment]
Changing `ensure` from `absent` to `link` was done as part of #644 since masking the unit 1) maintains the integrity of the distribution's package manager database and 2) opens up possibilities to reference the unit when creating instances instead of doing so via hard-coded templates in the puppet code (plus it's the recommended way to do it in systemd). I'll keep digging and see if I can figure out what's going on.

**Comment by tylerjl** [comment]
This is in as of 4c687d1. Instead of doing the manual work of symlinking to `/dev/null`, which apparently makes puppet choke in some cases, we'll use an `exec` cal to `systemctl` to mask the unit, which should be more reliable. 👍  Thanks again for the report!

**Comment by danieloa** [comment]
Thanks to you! very much appreciated :)
