### ISSUE TITLE
Major Point Release Breaking Changes

### ISSUE THREAD

**Issue by tylerjl** [elastic/puppet-elasticsearch#681]
## Executive Summary

This module is probably overdue for a 1.x release - it's used in production by lots of people, and a major point release means that people can finally start relying on the assurances that [semver](http://semver.org/) offers them (that is, they can move around within a major version number without fear of breaking changes or incompatible code in their manifests). We'll use this issue as a point of discussion for changes to bring into the next major point release.
## Current Status

The module is incrementing at major release zero (0.12, 0.13, etc.) which means [the API isn't guaranteed to be stable](http://semver.org/#spec-item-4) (though we do our best to keep it that way!) There's some scattered issues with references to a major point release, but no comprehensive list of what those changes might include.
## Proposal

Though I don't have a timeline in mind for 1.x, we should accumulate a list of potentially breaking changes that we want to make to the module and enumerate them here so we can 1) spot potential collisions between big changes, 2) keep the number of them reasonable, 3) solicit feedback from people regarding whether the list of big changes is good/bad/worth it/not worth it.

So!
### Parameters
- I'd like to nuke some of the parameters that were associated with API access (like `ssl_user`) and unify them under the longer (but more specific and accurate) names like `api_basic_auth_user`
### Remove Package Pinning

The inclusion of a yum module as a dependency for pinning the `elasticsearch` package feels like the module is overreaching its responsibilities. If a user wants to pin a package, they just need their own yum module (maybe even the one that's currently required) and define a single resource to pin their package. Collisions in the `yum` namespace happens to lots of people, which would solve those problems as well.
### Templated systemd Units

Though I haven't done the requisite background research on this yet, using the units that ship with elasticsearch as a template for service instances means we get fixes, updates, and version-specific compatibility out of the box when creating new instances. Though this may be possible with other init systems, systemd seems like it'd be the most likely to work.

**Comment by choffee** [comment]
In line with other es pacakges would it be good to bump this to v5? Would it then be reasonable to keep v5 around until elastic stop supporting the upstream? I might make moving to new versions easier.

**Comment by tylerjl** [comment]
@choffee that was my exact thought as well. I'm preparing a set of releases that moves to follow upstream versioning to make it clear which versions of Elasticsearch this module supports, as well as moving to the more accurate `elastic/elasticsearch` Puppet forge namespace. 👍  Thank you for confirming this decision would make sense for users!
