### ISSUE TITLE
Failing to apply elasticsearch::template

### ISSUE THREAD

**Issue by pabrahamsson** [elastic/puppet-elasticsearch#688]
* Module version: `0.13.1`
* Puppet version: `3.8.7`
* OS and version: `Ubuntu 14.04`

## Bug description

Error message
```
$ sudo puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for marvel01.example.com
Info: Applying configuration version ''
Error: Could not prefetch elasticsearch_template provider 'ruby': end of file reached
Notice: /Stage[main]/Role::Marvel/Elasticsearch::Template[marvel]/Elasticsearch_template[marvel]/ensure: created
Error: /Stage[main]/Role::Marvel/Elasticsearch::Template[marvel]/Elasticsearch_template[marvel]: Could not evaluate: end of file reached
Notice: Finished catalog run in 13.38 seconds
```

Manifest
```
elasticsearch::template { 'marvel':
  content => 
    'order' => 1,
    'settings' => {
      'number_of_replicas' => 0
    },
    'template' => ".marvel*"
  }
}
```

Hiera
```
elasticsearch::api_basic_auth_password: <eyaml encrypted password>
elasticsearch::api_basic_auth_username: admin
elasticsearch::api_host: "%{::fqdn}"
elasticsearch::api_protocol: https
```

Some additional info
```
/var/lib/puppet/lib/puppet/provider/elasticsearch_template$ ruby ruby.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- puppet_x/elastic/deep_to_i (LoadError)
           from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
           from ruby.rb:7:in `<main>'
/var/lib/puppet/lib/puppet/provider/elasticsearch_template$ cd ../../..
/var/lib/puppet/lib$ ruby puppet/provider/elasticsearch_template/ruby.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- puppet_x/elastic/deep_to_i (LoadError)
           from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
           from puppet/provider/elasticsearch_template/ruby.rb:7:in `<main>'
/var/lib/puppet/lib$ ll puppet_x/elastic/
total 20
drwxr-xr-x 2 root root 4096 Aug 19 17:54 ./
drwxr-xr-x 6 root root 4096 Jul 28 17:32 ../
-rw-r--r-- 1 root root  727 Aug 19 17:54 deep_implode.rb
-rw-r--r-- 1 root root  644 Aug 19 17:54 deep_to_i.rb
-rw-r--r-- 1 root root 2178 Jul 28 17:32 hash.rb
```

**Comment by tylerjl** [comment]
I set up a test environment with those specs and the template resource works there. It looks like you may have a somewhat non-standard setup - typically the `lib/` directory bundled with a module sits alongside the other files in the module (i.e. `manifests/`, `templates/`, etc) which is where `require` is trying to pull them from.

Does your installed elasticsearch module have the `lib/` directory present?

**Comment by pabrahamsson** [comment]
Yes it does have a `lib/` directory. The above output was from the node where I'm trying to apply the template. The module dir on the puppet master looks like below.
```
root@puppet-r10k:/etc/puppetlabs/code/environments/staging/modules/elasticsearch# tree lib
lib
├── facter
│   └── es_facts.rb
├── puppet
│   ├── feature
│   │   └── elasticsearch_shield_users_native.rb
│   ├── parser
│   │   └── functions
│   │       ├── array_suffix.rb
│   │       ├── concat_merge.rb
│   │       ├── deep_implode.rb
│   │       └── plugin_dir.rb
│   ├── provider
│   │   ├── elasticsearch_plugin
│   │   │   └── plugin.rb
│   │   ├── elasticsearch_shield_role
│   │   │   └── parsed.rb
│   │   ├── elasticsearch_shield_role_mapping
│   │   │   └── parsed.rb
│   │   ├── elasticsearch_shield_user
│   │   │   ├── esusers.rb
│   │   │   └── parsed.rb
│   │   ├── elasticsearch_shield_user_roles
│   │   │   └── parsed.rb
│   │   ├── elasticsearch_template
│   │   │   └── ruby.rb
│   │   ├── elastic_yaml.rb
│   │   └── es_instance_conn_validator
│   │       └── tcp_port.rb
│   ├── type
│   │   ├── elasticsearch_plugin.rb
│   │   ├── elasticsearch_shield_role_mapping.rb
│   │   ├── elasticsearch_shield_role.rb
│   │   ├── elasticsearch_shield_user.rb
│   │   ├── elasticsearch_shield_user_roles.rb
│   │   ├── elasticsearch_template.rb
│   │   └── es_instance_conn_validator.rb
│   └── util
│       └── es_instance_validator.rb
└── puppet_x
    └── elastic
        ├── deep_implode.rb
        ├── deep_to_i.rb
        └── hash.rb

17 directories, 26 files
```

**Comment by tylerjl** [comment]
Is [pluginsync](https://docs.puppet.com/puppet/4.6/reference/plugins_in_modules.html#auto-download-of-agent-side-plugins-pluginsync) disabled perhaps? The provider file `ruby.rb` modifies ruby's LOAD_PATH to require the file relative to it's location, so if the master isn't sending over the relevant `lib/` to the client, it'd encounter `require` errors.

**Comment by pabrahamsson** [comment]
No, it's set to `true`

**Comment by tylerjl** [comment]
Could you post the results of executing your puppet run with `--trace` and then another run with `--debug` mode? Feel free to use pastebin/gist if the output is long.

**Comment by pabrahamsson** [comment]
Here's the [trace.txt](https://gist.github.com/pabrahamsson/6f4e6a10ed5563541948a54b5d10a10d). I have a debug log as well but it would require a bit of cleaning before posting publically. Let me know if you still need it.

**Comment by tylerjl** [comment]
I think the most important lines are these:

    Error: Could not prefetch elasticsearch_template provider 'ruby': end of file reached
    ...
    /var/lib/puppet/lib/puppet/provider/elasticsearch_template/ruby.rb:35:in `rest'

Which would indicate the provider is failing when using the ruby `net/http` libraries when attempting to communicate with the Elasticsearch API. What does the Elasticsearch setup look like in your environment? For example:

- What bound address does `netstat -lpnt | grep 9200` show (assuming you're binding on 9200) - I'd expect something like `0.0.0.0:9200`
- Are you using shield/is the API accessible over HTTP or HTTPS?
- Is the cluster experiencing timeouts/networking problems? Can you `curl http://localhost:9200/_template` successfully from the command line? (or whatever address/port combination from the agent machine should use to access the API)

It'd also be useful to know the version of Elasticsearch you're working with.

**Comment by pabrahamsson** [comment]
We're using shield and are running over HTTPS on port 9200 on Elasticsearch 2.3.4.
```

**Comment by pabrahamsson** [comment]
This instance is running Elasticsearch 2.3.4 with shield with all ES related config being done through Puppet. I can use curl to create/list/delete the template with no issues.
```
$ sudo netstat -lpnt|grep 9200
tcp6       0      0 10.45.6.25:9200         :::*                    LISTEN      4370/java
```

One thing I'd missed yesterday was to take a look at the Elasticsearch log file. Every time puppet runs the below two lines clearly points out the problem.
```
[2016-08-25 13:30:26,564][WARN ][shield.transport.netty   ] [marvel2] received plaintext http traffic on a https channel, closing connection [id: 0x08fda0fe, /1.2.3.4:33569 => /1.2.3.4:9200]
[2016-08-25 13:30:26,568][WARN ][shield.transport.netty   ] [marvel2] received plaintext http traffic on a https channel, closing connection [id: 0xdbe8eb45, /1.2.3.4:33570 => /1.2.3.4:9200]
```

As you can see in the original message `elasticsearch::api_protocol` is set to `https`. Just for testing I also tried with `elasticsearch::use_ssl` set to `true` with the same result.
I'm unfortunately not familiar enough with puppet providers to debug why the protocol isn't having any effect.

**Comment by tylerjl** [comment]
Well, this is definitely a bug - turns out I never set the HTTPS flag in the provider if the scheme was set to HTTPS. Sorry about the inconvenience!

I've got a PR open at #689 that fixes the issue, with an accompanying test to ensure the code works as intended. This is a pretty glaring bug, so once it gets merged I'll probably cut a bugfix release to get this fix in particular out quickly (other fixes made since then will get carried along for the ride).

**Comment by pabrahamsson** [comment]
Thank you for the quick turnaround, confirmed working on my end with [#689](https://github.com/elastic/puppet-elasticsearch/pull/689) applied. Closing the issue.
