### ISSUE TITLE
proxy support for plugin installation does not work in 0.13.2

### ISSUE THREAD

**Issue by trondiz** [elastic/puppet-elasticsearch#695]
* Module version: 0.13.2
* Puppet version: 4.6.1
* OS and version: Debian 8

## Bug description
Installing plugins in 0.13.2 no longer works with proxy settings. Reverting back to 0.13.0 and it works again.

**Comment by tylerjl** [comment]
Yep, I can see in the code where this would have happened. Should be a pretty straightforward fix in the provider.

**Comment by smetj** [comment]
applying elasticsearch::plugin() simply doesn't work.

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter proxy on Elasticsearch_plugin[license] at /xxxxxxx/modules/elasticsearch/manifests/plugin.pp:168 on node xxxxxxx
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
which makes it impossible(?) to install/manage plugins ....
Looks pretty urgent to me....

**Comment by cdenneen** [comment]
I'm not specifying proxy settings and this is still erroring.

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: no parameter named 'proxy' at /etc/puppetlabs/code/environments/logging/thirdparty/elasticsearch/manifests/plugin.pp:161 on Elasticsearch_plugin[mobz/elasticsearch-head] at /etc/puppetlabs/code/environments/logging/thirdparty/elasticsearch/manifests/plugin.pp:161 on node
```

**Comment by jaynefox** [comment]
+1 to this.

**Comment by dutsmiller** [comment]
This still seems broken with module version 0.14.0 against ES 1.7.5.  Was the fix only for the 2.x branch?  I was able to roll back to 0.13.0 and everything worked as expected, with 0.14.0, the proxy settings were ignored.

**Comment by tylerjl** [comment]
@dutsmiller we're still on a single module for all versions. The fix should have resolved issues for all versions of Elasticsearch; but if it's broken for the 1.x series, we can take a closer look to see if there's a subtle bug somewhere.

**Comment by dutsmiller** [comment]
Thanks for the reply!  It was definitely giving me problems on RHEL6.8/Puppet 4.8/ES 1.7.5 when trying to install plugins with a proxy.
