### ISSUE TITLE
Plugin install questions

### ISSUE THREAD

**Issue by tamarintech** [elastic/puppet-elasticsearch#696]
- Module version: 0.13.2
- Puppet version: 3.8.7
- OS and version: CentOS 6/7
## Bug description

When using only `elasticsearch::plugin { 'polyfractal/elasticsearch-inquisitor': ensure => present }` I end up with an error that '.name' cannot be created in a directory that doesn't exist.  After providing a `module_dir => '/usr/share/elasticsearch/plugins/elasticsearch-inquisitor',` parameter the plugin installation seems to work.  The plugin is accessible at _plugin/elasticsearch-inquisitor instead of _plugin/inquisitor, though.

Should I follow up here or look into the Inquisitor plugin to discover more about the strange behavior?

**Comment by tylerjl** [comment]
Generally plugin behavior is such that plugins create directories without the leading `elasticsearch-` in the directory name. The provider strips off those when looking for the directory, so it sounds like inquisitor may be an exception to the rule.

If that is indeed the case (probably needs confirming), the options are either to 1) change `inquisitor` behavior, 2) leave the puppet code as-is and let people use `module_dir` as you've described, and 3) update the plugin name detection plugin to attempt to derive the name with fuzzier methods.

**Comment by tamarintech** [comment]
Thanks.

I just discovered the behavior seems different between elasticsearch versions.  On elasticsearch 1.x it seems Inquisitor ends up in plugins/inquisitor and works as expected without specifying the module_dir parameter.  For my elasticsearch 2.3.3 nodes the behavior is different.

`/usr/share/elasticsearch/bin/plugin install polyfractal/elasticsearch-inquisitor` results in `Installed elasticsearch-inquisitor into /usr/share/elasticsearch/plugins/elasticsearch-inquisitor` which triggers the puppet module to not be able to locate '.name' for ensure and fail because it is looking for /inquisitor instead of /elasticsearch-inquisitor.

Maybe this is a difference in behavior around the plugin-descriptor.properties between 2.x and 1.x?  The `name` in inquistor's properties file is `elasticsearch-inquisitor`.

**Comment by tamarintech** [comment]
Sorry, left this open for a silly amount of time.
