### ISSUE TITLE
Version lock in metadata.json prevents from upgrading ceritsc-yum module

### ISSUE THREAD

**Issue by marcinbojko** [elastic/puppet-elasticsearch#697]
- Module version: latest 0.13.2
- Puppet version: 3.8.7
- OS and version: CentOS 7.2 (1511)
## Bug description

Version lock in metadata.json prevents from upgrading ceritsc-yum module

`{"name":"ceritsc/yum","version_requirement":">= 0.9.6 < 1.0.0"},`
## proposed change

`{"name":"ceritsc/yum","version_requirement":">= 0.9.6"},`

**Comment by tylerjl** [comment]
Based upon what I found in their github repo and the puppet forge, there is no 1.x release - am I mistaken/is there a release somewhere you can point me to? Reason being that we'd need to test the module against that version to ensure there's no breakage, but I can't find that version anywhere.

**Comment by marcinbojko** [comment]
Hi,
ceritsc-yum was replaced by puppet-yum (which is not suitable yet), but in my case ceritsc is forked and maitained internally by me. Adding new features causes to increment version (leaving old name intact), which conflicts with elasticsearch module.
I would like to propose to remove < 1.0.0 version from requirements.

**Comment by marcinbojko** [comment]
Guys, it's not a revolutionary change - simple unlock 'below'. I don't want to do this manually on every server I have, but since yum class is forked and available in version higher than 1.0.0, it would be nice to have status green.

**Comment by marcinbojko** [comment]
Thanks!
