### ISSUE TITLE
Template produces extra "index." in config nesting.

### ISSUE THREAD

**Issue by cFire** [elastic/puppet-elasticsearch#698]
- Module version: 0.13.2
- Puppet version: 4.6.2
- OS and version: CentOS 7
## Bug description

When implementing https://www.elastic.co/blog/hot-warm-architecture I ran into the following issue:

I have this template in hierdata:

```
logstash-template :
  content : '{"template":"logstash-*","settings":{"index.routing.allocation.require.box_type": "hot"}}'
```

On the elasticsearch nodes this produces a template with a double "index." ie. ``"settings.index.index.routing.allocation.require.box_type": "hot"`

When providing the template in hieradata with the leading **index.** chopped of, ie `{"template":"logstash-*","settings":{"routing.allocation.require.box_type": "hot"}}` the actual correct template is produced with a single **index.**.

**Comment by tylerjl** [comment]
Yeah, I think I can see where the problem arises in the code. There's ambiguity in how index settings can be defined, so the code has to fully qualify some settings to ensure the template you define is in sync with what's currently in elasticsearch.

Like you mentioned, the workaround is to not explicitly prepend the setting with `index.`, but it's definitely something that can be fixed.
