### ISSUE TITLE
Exec[systemd_reload_data] doesn't actually restart

### ISSUE THREAD

**Issue by cdenneen** [elastic/puppet-elasticsearch#712]
* Module version: 0.13.2
* Puppet version: 4.3.2
* OS and version: CentOS 7

## Bug description

```puppet
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for eslogdata.domain.local
Info: Applying configuration version 'cb9d179cfe4825da6bb7e3924219ea276ea4053a'
Notice: Augeas[defaults_data](provider=augeas):
--- /etc/sysconfig/elasticsearch-data  	2016-07-25 12:07:05.712798319 -0400
+++ /etc/sysconfig/elasticsearch-data.augnew   	2016-10-03 16:55:12.149654356 -0400
@@ -3,7 +3,7 @@
 DATA_DIR=/var/lib/elasticsearch
 ES_GROUP=elasticsearch
 ES_HOME=/usr/share/elasticsearch
-ES_JAVA_OPTS=-Djava.net.preferIPv4Stack=true
+ES_JAVA_OPTS="-Djava.net.preferIPv4Stack=true -Dmapper.allow_dots_in_name=true"
 ES_USER=elasticsearch
 LOG_DIR=/var/log/elasticsearch/data
 MAX_LOCKED_MEMORY=unlimited

Notice: /Stage[main]/Profile::Elasticsearch/Elasticsearch::Instance[data]/Elasticsearch::Service[data]/Elasticsearch::Service::Systemd[data]/Augeas[defaults_data]/returns: executed successfully
Info: /Stage[main]/Profile::Elasticsearch/Elasticsearch::Instance[data]/Elasticsearch::Service[data]/Elasticsearch::Service::Systemd[data]/Augeas[defaults_data]: Scheduling refresh of Exec[systemd_reload_data]
Notice: /Stage[main]/Profile::Elasticsearch/Elasticsearch::Instance[data]/Elasticsearch::Service[data]/Elasticsearch::Service::Systemd[data]/Exec[systemd_reload_data]: Triggered 'refresh' from 1 events
Notice: Applied catalog in 21.09 seconds
```
```
[root@ctceslogs11 tempdir]# ps -ef |grep elastic
root      75748 119253  0 17:01 pts/0    00:00:00 grep --color=auto elastic
elastic+ 120632      1 99 Sep30 ?        5-11:30:48 /bin/java -Xms30g -Xmx30g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Djna.nosys=true -Djava.net.preferIPv4Stack=true -Des.path.home=/usr/share/elasticsearch -cp /usr/share/elasticsearch/lib/elasticsearch-2.4.1.jar:/usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch start -d -p /var/run/elasticsearch/elasticsearch-data.pid -Des.default.path.home=/usr/share/elasticsearch -Des.default.path.logs=/var/log/elasticsearch/data -Des.default.path.data=/var/lib/elasticsearch -Des.default.path.work=/tmp/elasticsearch -Des.default.path.conf=/etc/elasticsearch/data
```

**Comment by tylerjl** [comment]
Is one of the parameters that controls daemon restart set to `true`? I'm referring to the behavior [noted here in the README](https://github.com/elastic/puppet-elasticsearch#automatically-restarting-the-service-default-set-to-false) (this did change recently). The actual `Exec[systemd_reload_data]` resource noted here just reloads the actual systemd daemon, not the ES service itself, so the behavior I'm seeing is expected.

**Comment by cdenneen** [comment]
Good point... i expect this with config changes... but figured systemd or sysconfig settings to behave differently.
So while I might not want changes to elasticsearch.yml to restart service, it might be good idea if you are changing JAVA_OPTS that it does... guess I can work around this.

**Comment by tylerjl** [comment]
Yeah, if we really wanted to, we could create even more fine-grained parameters for things like `restart_on_config_change`, `restart_on_defaults_change`, and so on, but I think the general parameters reflect the uses most people care about (i.e., whether you're ready/prepared for ES to restart if the module detects it needs to be.)

Is using `restart_on_change` acceptable or do you need a more specific parameter like one of the ones I've mentioned? If the former works we can close.

**Comment by cdenneen** [comment]
I can probably get by with `restart_on_change` but it might be useful to others to make these more fine-grained.
