### ISSUE TITLE
Permission of elasticsearch.yml is world readable and contains keystore passwords

### ISSUE THREAD

**Issue by choffee** [elastic/puppet-elasticsearch#719]
- Module version: 0.13.2
- Puppet version: 3.8
- OS and version: Ubuntu 16.04 ( Other affected )
## Bug description

By default the module does not manage the permissions of the elasticsearch.yml config file. This can contain the keystore and truststore passwords. It should probably be set to '0440'.

**Comment by tylerjl** [comment]
Barring any unforeseen consequences of locking down the `.yml` permissions, this sounds reasonable to me given the potential for sensitive material in the config.
