### ISSUE TITLE
Is Ubuntu 1604 supported or is the Forge Compatibility page behind?

### ISSUE THREAD

**Issue by madnice** [elastic/puppet-elasticsearch#722]
I believe this supports systemd so it should work, but I am looking for confirmation.

**Comment by tylerjl** [comment]
My gut reaction is that it should be supported, but I'll hold off on adding it to the compatibility list until it's certifiably tested and confirmed to work in CI. I've pushed a test branch to my repo to see if anything broken shows up. Most of the ubuntu logic in `params.pp` correctly guesses the init system for versions of Ubuntu >= 15.x, so I think it'll be fine.

Oddly, there were very strange errors when trying to run the acceptance tests on 16.04 with Elasticsearch 1.4, so I bumped the tests to run against the most recent in the 1.x series (1.7) but I think that needed to happen anyway.

**Comment by tylerjl** [comment]
I've got a PR baking in #723; the tests pass on xenial, though I haven't added Puppet Enterprise tests yet as the versions that support 16.04 have issues in beaker. Once the PR passes the tests I can merge and get the forge page updated.

**Comment by madnice** [comment]
Awesome! Thanks for doing this, I'm sure a lot of people are probably running it on 16.04 already.

**Comment by tylerjl** [comment]
Tests added, pass, and the module metadata updated.

For those following, xenial looks good to go with this module, and the forge page will reflect this upon next release. 👍
