### ISSUE TITLE
template failing on missing ca_file parameter

### ISSUE THREAD

**Issue by siliconalchemy** [elastic/puppet-elasticsearch#735]
* Module version: 0.15.0
* Puppet version: 4.7.0
* OS and version: CentOS 7

## Bug description
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'ca_file' at /srv/puppet/environments/production/modules/elasticsearch/manifests/template.pp:161 on Elasticsearch_template[logstash-custom] at /srv/puppet/environments/production/modules/elasticsearch/manifests/template.pp:161 on node prod-infra
```

I've also tried setting api_ca_file => undef in elasticsearch and elasticsearch::template classes to no luck.

**Comment by tylerjl** [comment]
Hi @siliconalchemy, have you ensured that any puppet agents (or the puppetmaster) have been restarted after updating to the new module? New parameters on defined types can cause problems when updating puppet modules. The `ca_file` parameter 100% percent exists on the template type.

**Comment by siliconalchemy** [comment]
@tylerjl - Doh, I had restarted the agent a dozen times and cleared out all the provider and type files , but not the puppetmaster.  Restarting the puppetmaster fixed it.  Thanks!
