### ISSUE TITLE
Issue with MAX_LOCKED_MEMORY in es5

### ISSUE THREAD

**Issue by MoisesRT** [elastic/puppet-elasticsearch#738]
* Module version: 0.15
* Puppet version: 3.8.4
* OS and version: Ubuntu 14
* ES version: 5.0.1

I had this setting in ElasticSeach 2 and now moving to version 5.0.1 I am encountering an issue.

the guide(https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html) says I need to set the MAX_LOCKED_MEMORY to 'unlimited',
But I get the error:

> MAX_LOCKED_MEMORY is set - ES_HEAP_SIZE must also be set
* I did set Xmx and Xms

ES_HEAP_SIZE  is not supported in ES5, therefore it doesn't boot.

**Comment by tylerjl** [comment]
Yep, definitely a bug, thank you so much for reporting it @MoisesRT. I've opened #739 to resolve it.

**Comment by tylerjl** [comment]
Merged; fix will be in next release. 👍
