### ISSUE TITLE
init_template must be fully qualified

### ISSUE THREAD

**Issue by christofhaerens** [elastic/puppet-elasticsearch#742]
* Module version: 0.15.0
* Puppet version: 3.7.4 (Puppet Enterprise 3.7.2)
* OS and version: rhel 7.2 x86_64

## Bug description
When usimg the module to create an instance I get the following puppet error (manifest is added at the bottom):
Error 400 on SERVER: Files must be fully qualified at /etc/puppetlabs/puppet/environments/test/modules/elasticsearch/manifests/service/systemd.pp:167

line 167 is the line starting with content:
 ```
     elasticsearch_service_file { "${elasticsearch::params::systemd_service_path}/elasticsearch-${name}.service":
        ensure            => $ensure,
        content           => file($init_template),
        defaults_location => $elasticsearch::defaults_location,
```

When adding debug code I see that init_template is set to " elasticsearch/etc/init.d/elasticsearch.systemd.erb"

my manifest:
```
  $config_hash = {
    'ES_USER' => 'elasticsearch',
    'ES_GROUP' => 'elasticsearch',
    'ES_HEAP_SIZE' => '16g',
  }

  class { '::elasticsearch':
    manage_repo => false,
    status      => enabled,
    restart_on_change => true,
    config      => {
      'cluster.name' => "test",
      'discovery.zen.ping.multicast.enabled' => 'false',
      'discovery.zen.ping.unicast.hosts' => $unicast_hosts,
      'discovery.zen.minimum_master_nodes' => 1,
      'indices.fielddata.cache.size' => $fielddata_cache_size,
    },
    java_install => false,
    init_defaults => $config_hash,
  }

  elasticsearch::instance { "i1":
    config  => {
      'node.name' => "node1-i1",
    },
    datadir => '/data/elastic',
  }
```

**Comment by tylerjl** [comment]
I ran all the tests against Puppet Enterprise 3.7.2 and wasn't able to reproduce the errors. Is there anything unique in your environment that may be related to the error? Also, if possible, I'd suggest finding out whether the bug persists in Puppet Enterprise 3.8.x, since version 3.7.2 [isn't supported anymore](https://puppet.com/misc/puppet-enterprise-lifecycle) (either by Puppet Labs or this module) so a later version may behave differently.

**Comment by christofhaerens** [comment]
Hi,
We have a jenkins job syncing the master @ github for our upstream modules. The previous time I tested the module against our manifest was on Nov 3 (commit id 2e214ab0d764879bc2477e0425869d389d9c7a44) (version 0.14.0 in metadata.json). This worked fine.
So when I stated above version 0.15.0, that's the version from the metadata.json but it is fact commit id 883b145ca9e58885b2fa713f6907de6e90d7e2d6 (Nov 22)
I don't have a PE3.8 available for testing. I will try to get one up asap and retest. If I have more info will post it here.
Cheers

**Comment by dawi** [comment]
We have the same issue on ubuntu after upgrading to 0.15.0.

Is there any possible known workaround?

**Comment by tylerjl** [comment]
@dawi what version of puppet are you on?

**Comment by dawi** [comment]
@tylerjl We are still on 3.4.3.

**Comment by tylerjl** [comment]
@dawi similar to the original post, I don't know whether 3.4.3 supports the `file()` function used in the way this provider is using it - I'd suggest trying a newer version of puppet (3.8 is tested by the integration tests and should work, though from reading the puppet function reference, 3.7 may work for you if 3.8 is too great of a leap).

Apologies for what appears to be a wrong version support matrix on the forge - I've updated the supported versions in `metadata.json` in 903e8129b to accurately reflect what is actively tested and what this module supports (basically following Puppet Lab's support lifecycle).

**Comment by dawi** [comment]
Sadly I cannot just update our puppet server version.
So I am going to delay our elasticsearch 5 update until our infrastructure is updated. :/

**Comment by smougenot** [comment]
Migrating from 0.14 to 0.15.1 I have the same trouble on Centos 7 with puppet master 3.6.2.

Looking at the code for templating concerning systemd it refers to a ```init_template``` using the ```file()``` function.
https://github.com/elastic/puppet-elasticsearch/blob/0.15.1/manifests/service/systemd.pp#L167
The value for this init_template is 
``` elasticsearch/etc/init.d/elasticsearch.systemd.erb ```

Two things trouble me:

- I think it might be a template function instead of the file function (also need to move the templates from the files directory to the templates directory?
- I don't think file function is able to interpret ruby markup (I might be wrong).

I might be wrong, sorry if it is the case.

**Comment by tylerjl** [comment]
@smougenot while it does look a little odd, the template is there for a reason and definitely works as it passes all acceptance tests. The reason the init script is passed that way is that the template is evaluated late in the puppet run when the version of Elasticsearch is known so we can write the correct invocation for the daemon (for example, whether to use `-Des` or `-E`. 

With that being said I do apologize that the module relies on functionality that differs in minor versions of puppet (i.e. how `file()` behaves after 3.7), but at least it'll be consistent moving forward.

**Comment by smougenot** [comment]
@tylerjl Thank you for the explanations

**Comment by tylerjl** [comment]
These problems should go away with a puppet version >= 3.8, and the forge page is now updated with the new minimum required puppet version. Though the 3.x series is EOL, I'll try and keep the module compatible with 3.8 (within reason) to help people that are still migrating.
