### ISSUE TITLE
ES_HEAP_SIZE variable is no longer supported for elasticsearch-5.x

### ISSUE THREAD

**Issue by jurim76** [elastic/puppet-elasticsearch#743]
* Module version: 0.15.0
* Puppet version: 3.8.5
* OS and version: Debian 8

## Bug description
elasticsearch version - 5.0.1

My hiera definition:
elasticsearch::init_defaults:
  ES_HEAP_SIZE: '4g'

> puppet agent -t
....
Notice: /Stage[main]/Elasticsearch/Elasticsearch::Instance[graylog]/Elasticsearch::Service[graylog]/Elasticsearch::Service::Systemd[graylog]/Exec[systemd_reload_graylog]: Triggered 'refresh' from 1 events
Error: Could not start Service[elasticsearch-instance-graylog]: Execution of '/bin/systemctl start elasticsearch-graylog.service' returned 1: Job for elasticsearch-graylog.service failed. See 'systemctl status elasticsearch-graylog.service' and 'journalctl -xn' for details.

> systemctl status elasticsearch-graylog
elasticsearch[48002]: Error: encountered environment variables that are no longer supported
elasticsearch[48002]: Use jvm.options or ES_JAVA_OPTS to configure the JVM
 elasticsearch[48002]: ES_HEAP_SIZE=4g: set -Xms4g and -Xmx4g in jvm.options or add "-Xms4g -Xmx4g" to ES_JAVA_OPTS

Modify hiera definition as
elasticsearch::init_defaults:
 ES_JAVA_OPTS: 'Xms4g -Xmx4g'

This does not work, because it's hash, not array.
> puppet agent -t 
....
Notice: /Stage[main]/Elasticsearch/Elasticsearch::Instance[graylog]/Elasticsearch::Service[graylog]/Elasticsearch::Service::Systemd[graylog]/Service[elasticsearch-instance-graylog]: Dependency Augeas[defaults_graylog] has failures: true
Warning: /Stage[main]/Elasticsearch/Elasticsearch::Instance[graylog]/Elasticsearch::Service[graylog]/Elasticsearch::Service::Systemd[graylog]/Service[elasticsearch-instance-graylog]: Skipping because of failed dependencies

How to define ES_JAVA_OPTS 'Xms4g -Xmx4g' for hiera in a true way?

**Comment by elisiano** [comment]
https://github.com/elastic/puppet-elasticsearch/issues/736

**Comment by Cloudance** [comment]
Hi,
I did following fixes to bypass this issue - added ES_HEAP_SIZE="" statement )))
#####################################################################
# export unsupported variables so bin/elasticsearch can reject them and inform the user these are unsupported
ES_HEAP_SIZE=""
if test -n "$ES_HEAP_SIZE"; then export ES_HEAP_SIZE; fi
######################################################################
otherwise just comment $ES_HEAP_SIZE 
Good Luck
Nat
