### ISSUE TITLE
 No such file to load -- puppet_x/elastic/es_versioning 

### ISSUE THREAD

**Issue by Cosaquee** [elastic/puppet-elasticsearch#744]
* Module version: 0.15.0
* Puppet version: 4.6.2
* OS and version: Ubuntu 16.04

## Bug description

Puppet manifest:

```
  class { 'elasticsearch':
    java_install => true,
    manage_repo  => true,
    repo_version => '5.x',
    datadir      => '/var/lib/elasticsearch',
  }

  elasticsearch::instance { 'es-01': }
```

Puppet output:

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/elasticsearch_service_file: no such file to load -- puppet_x/elastic/es_versioning at /etc/puppetlabs/code/environments/production/modules/elasticsearch/manifests/service/systemd.pp:165:7 at /etc/puppetlabs/code/environments/production/modules/elasticsearch/manifests/service.pp:89 on node [nodename]`

If i remove `elasticsearch::instance { 'es-01': }` everything works.

Any idea what I do wrong ? It worked on version 0.14.0 and `repo_version => "2.x"`

**Comment by olafz** [comment]
We have the same issue. It is unrelated to the ES version change though: just updating the module and leaving `repo_version` unchanged triggers the error in our case.

- Module version: 0.15.0
- Puppet version: 3.8.7
- OS and version: Debian Wheezy

**Comment by olafz** [comment]
In our case, it is fixed by a trivial $LOAD_PATH change:

```
diff --git a/modules/elasticsearch/lib/puppet/type/elasticsearch_service_file.rb b/modules/elasticsearch/lib/puppet/type/elasticsearch_service_file.rb
index fcf5982..0a13c2d 100644
--- a/modules/elasticsearch/lib/puppet/type/elasticsearch_service_file.rb
+++ b/modules/elasticsearch/lib/puppet/type/elasticsearch_service_file.rb
@@ -1,4 +1,4 @@
-$LOAD_PATH.unshift(File.join(File.dirname(__FILE__),"..","..",".."))
+$LOAD_PATH.unshift(File.join(File.dirname(__FILE__),"..",".."))

 require 'puppet/util/checksums'
```

**Comment by Cosaquee** [comment]
@olafz it works, thank you! @tylerjl are planning to include this fix in upcoming release ? Or should @olafz, or i can, provide PR for that ?

**Comment by tylerjl** [comment]
I'll try and get this into the next bugfix release, seems like a sensible change. 👍

**Comment by tylerjl** [comment]
Baking in CI at #746

**Comment by tylerjl** [comment]
Merged; will be in next release. Thanks again for feedback!
