### ISSUE TITLE
 hiera discovery.zen.ping.unicast.hosts  failed

### ISSUE THREAD

**Issue by jurim76** [elastic/puppet-elasticsearch#749]
* Module version: 0.15.1
* Puppet version: 3.8.5
* OS and version: Debian 8

## Bug description

Unable to define "discovery.zen.ping.unicast.hosts" in hiera definition

Hiera config
elasticsearch::instances:
  graylog:
    config:
      cluster:
        name: 'graylog'
elasticsearch::config:
  discovery.zen.ping.unicast.hosts: '["10.1.112.22","10.1.112.23","10.1.112.24"]'

will produce elasticsearch.yml entry like
discovery.zen.ping.unicast.hosts: "[\x2210.1.112.22\x22,\x2210.1.112.23\x22,\x2210.1.112.24\x22]"

and elasticsearch failed to start
Likely root cause: java.lang.IllegalArgumentException: Invalid bracketed host/port range: ["10.1.112.22"

**Comment by tylerjl** [comment]
Try defining your array of hosts as a yaml array instead of a string:

```
discovery.zen.ping.unicast.hosts:
  - "10.1.112.22"
  - "10.1.112.23"
  - "10.1.112.24"
```

**Comment by jurim76** [comment]
Will produce entry "as is" and failed.

elasticsearch.yml
discovery.zen.ping.unicast.hosts:
  - "10.1.112.22"
  - "10.1.112.23"
  - "10.1.112.24"

**Comment by tylerjl** [comment]
So, I've tried using that syntax in the elasticsearch configuration file and it behaves as expected without errors. Could you perhaps include the exact error you're seeing from Elasticsearch when it's trying to start up?

**Comment by jurim76** [comment]
Sorry, my fault.
