### ISSUE TITLE
Index templates: support 'ensure => latest' to force (re)installation

### ISSUE THREAD

**Issue by ayashjorden** [elastic/puppet-elasticsearch#756]
Hi,
I've encountered a scenario where I deployed new index templates and due to the 'ensure => present' default, they weren't loaded to ES.

Appreciate comments/opinions.

Best,
Yarden

**Comment by tylerjl** [comment]
The custom type should be ensuring that the content in elasticsearch and the content you've defined in the template should be synced, so it should be the same either way.

If you'd like some help, I'd need some example puppet manifests/logging output/template content from Elasticsearch/etc.
