### ISSUE TITLE
CONF_FILE setting is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed

### ISSUE THREAD

**Issue by maneeshmp** [elastic/puppet-elasticsearch#765]
Module version:
0.15.1

Puppet version:
4.3.2

OS and version:
Ubuntu 12.04

Elastic Search Version:
2.4.1

Bug description:

Error: Could not set 'present' on ensure: Failed to install plugin. Received error: #<Puppet::ExecutionFailure: Execution of '/usr/share/elasticsearch/bin/plugin -Des.path.conf=/usr/share/elasticsearch install --batch mapper-attachments' returned 1: CONF_FILE setting is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed.> at 161:/modules/elasticsearch/manifests/plugin.pp 

Additional Info about elastic behavior:
https://github.com/elastic/elasticsearch/pull/13772

**Comment by tylerjl** [comment]
@maneeshmp can you include an example puppet manifest that throws the error for you? The following manifest works without any problems for me:

```puppet
class { 'elasticsearch':
        java_install => true,
        manage_repo => true,
        repo_version => '2.x',
        restart_on_change => true,
}

elasticsearch::instance { 'es-01' : }

elasticsearch::plugin { 'mapper-attachments' : instances => 'es-01' }
```

**Comment by maneeshmp** [comment]
Here is the snippet of  manifest

$es_config = {
    'bootstrap.mlockall'  => true,
    'cluster.name'        => $cluster_name,
     'cloud.aws' => {
      'access_key' => $s3_access_key,
      'secret_key' => $s3_secret_key,
      'region'     => 'us-east',
    },
    'network.host' => '0.0.0.0',
    'discovery' => {
      'type' => 'ec2',
      'ec2' => {
        'tag.aws:cloudformation:stack-name' => $::stackname,
      },
    },
     'gateway' => {
      'recover_after_nodes' => 2, #floor(2 / 3 * $total_nodes),
      'expected_nodes'      => $total_nodes,
      'recover_after_time'  => '2m',
    },
 
    'http.max_content_length' => $http_max_content_length,
    'index' => {
      'search.slowlog.threshold.query.warn'   => '10s',
      'indexing.slowlog.threshold.index.warn' => '10s',
       'merge.scheduler.max_thread_count'      => 1,
       'translog.flush_threshold_size'         => '500mb',
    },
    'indices' => {
       'fielddata.cache.size' => '20%',
      'cache.filter.size'    => '15%',
       'breaker' => {
         'fielddata.limit'   => '60%',
        'request.limit'     => '40%',
        'total.limit'       => '70%',
      },
       'memory' => {
        'index_buffer_size'           => '20%',
        'min_shard_index_buffer_size' => '12mb',
        'min_index_buffer_size'       => '96mb',
      },
    },
 
    'script.inline' => true,
    'script.indexed' => true,
     'index.mapping.attachment.indexed_chars' => -1,
  }

$es_config = {
    'bootstrap.mlockall'  => true,
    'cluster.name'        => $cluster_name,
     'cloud.aws' => {
      'access_key' => $s3_access_key,
      'secret_key' => $s3_secret_key,
      'region'     => 'us-east',
    },
    'network.host' => '0.0.0.0',
    'discovery' => {
      'type' => 'ec2',
      'ec2' => {
        'tag.aws:cloudformation:stack-name' => $::stackname,
      },
    },
     'gateway' => {
      'recover_after_nodes' => 2, #floor(2 / 3 * $total_nodes),
      'expected_nodes'      => $total_nodes,
      'recover_after_time'  => '2m',
    },
 
    'http.max_content_length' => $http_max_content_length,
    'index' => {
      'search.slowlog.threshold.query.warn'   => '10s',
      'indexing.slowlog.threshold.index.warn' => '10s',
       'merge.scheduler.max_thread_count'      => 1,
       'translog.flush_threshold_size'         => '500mb',
    },
    'indices' => {
       'fielddata.cache.size' => '20%',
      'cache.filter.size'    => '15%',
       'breaker' => {
         'fielddata.limit'   => '60%',
        'request.limit'     => '40%',
        'total.limit'       => '70%',
      },
       'memory' => {
        'index_buffer_size'           => '20%',
        'min_shard_index_buffer_size' => '12mb',
        'min_index_buffer_size'       => '96mb',
      },
    },
   'script.inline' => true,
    'script.indexed' => true,
     'index.mapping.attachment.indexed_chars' => -1,
  }

class { 'elasticsearch' :
    ensure        => present,
    config        => $es_config,
    init_defaults => $init_defaults,
    logging_file  => "puppet:///modules/${module_name}/db/logging.yml",
    datadir       => '/opt/elasticsearch/data',
    status        => 'enabled',
    manage_repo   => true,
    repo_version  => '2.x',
    package_url   => 'https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.1/elasticsearch-2.4.1.deb',
    java_install  => false,
  }

**Comment by tylerjl** [comment]
@maneeshmp what is the variable `$init_defaults` set to?

**Comment by maneeshmp** [comment]
$init_defaults = {
    'ES_HEAP_SIZE'      => $max_memory,
    'MAX_LOCKED_MEMORY' => 'unlimited',
    'ES_JAVA_OPTS'      => "-Xmx${max_memory}",
  }

**Comment by tylerjl** [comment]
Thank you - could you also find all the files under `/etc/default/elasticsearch-*` and report back with their contents? `CONF_FILE` may have been left behind in one of the init default files.

**Comment by tylerjl** [comment]
As of version 5.x of this module, `CONF_FILE` is explicitly purged if the setting isn't defined by the user, so this should be resolved.
