### ISSUE TITLE
RESTful interface for index settings

### ISSUE THREAD

**Issue by alexizmailov** [elastic/puppet-elasticsearch#768]
* Module version: 0.15.1
* Puppet version: v4.7.0
* OS and version: CentOS 7.2

## Feature description

Since Elasticsearch 5.x index level settings can NOT be set on the nodes configuration like the Elasticsearch.yaml, in system properties or command line arguments.

https://github.com/elastic/elasticsearch/issues/18073

Elasticsearch 5 now uses RESTful API to set up indexes and indices.

This functionality is often required and such would be advantageous to provide this as part of the module thus preventing the requirement for dirty exec, such as:

```
exec {'set_number_of_shards':
   command => 'curl -XPUT 'http://localhost:9200/_all/_settings?preserve_existing=true' -d '{"index.number_of_shards" : "3"}',
   unless  => 'curl -XGET...'
}
```

For example, this is currently blocking us from deploying ES5 with Puppet as indices level configuration cannot be managed by this module.

**Comment by sammcj** [comment]
I can confirm that this is indeed an issue and I've worked with @alexizmailov to try to find a work around, but short of using `exec` which we don't want to do the only way we could see is by adding this functionality to this model, perhaps by using the [`Elasticsearch::API` gem](https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-api) as part of the modules providers, but neither of us are proficient with ruby enough to submit a MR.

**Comment by tylerjl** [comment]
Gotcha, this seems like something we can definitely add. For anyone running into this issue, note that you can control index settings for _newly_ created indices using index templates (which are supported in this module). Existing indices is something we'll need to add, though.

If someone has time to get to it before I do, note that the strategy will probably be similar to how templates are managed in the native provider.

**Comment by sammcj** [comment]
Great to hear @tylerjl, at present our developers use application/library controlled templates / creation of indices and what's important for us is to make certain that the system ensure some consistent configuration across them regardless of how the developer or application is believes, assumes or defaults to configuring them. Essentially we want to make the system safe and easy to work with and not make assumptions.

**Comment by alexizmailov** [comment]
Hi Tyler
Thank you for adding new feature. 
Looks like new type `elasticsearch::index` requires an index name. We use ES for logs and we have a new index every day, e.g. logstash-YYYY-MM-DD.

Could you clarify how do I now set default values for all indexes?
At the moment I'm using this query, which doesn't contain any index names:
`curl -XPUT http://${hostname}:9200/_settings?preserve_existing=true -d '{\"number_of_replicas\" : \"5\"}'`

**Comment by tylerjl** [comment]
@alekseymykhailov fortunately, that is exactly what [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) are for. This module supports those as well.
