### ISSUE TITLE
Insecure /usr/share/elasticsearch/lib* permissions 

### ISSUE THREAD

**Issue by faxm0dem** [elastic/puppet-elasticsearch#775]
* Module version: 0.15.1
* Puppet version: 3.8
* OS and version: Centos7

## Bug description

By default, the module changes ownership of `/usr/share/elasticsearch/lib` recursively to the user `elasticsearch`. This is both unneccesary and poses a security risk: the jar files can be replaced by a running compromised instance of elasticsearch.

**Comment by tylerjl** [comment]
Agreed. I pushed a branch to my fork to test out the effects of keeping user/group at `root`, if nothing breaks in CI then this seems like a good change to make.
