### ISSUE TITLE
Elasticsearch 6.x Compatibility

### ISSUE THREAD

**Issue by tylerjl** [elastic/puppet-elasticsearch#776]
This is a meta-ticket to track upstream changes to Elasticsearch in the 6.x series that will (probably) require changes from this module.

- [x] All REST requests with a payload will now [_require_ explicitly set `Content-Type` headers](https://github.com/elastic/elasticsearch/pull/22691). (for example, `curl -H "Content-Type:application/json" -XPOST localhost:9200/my_index/my_type -d { "foo": "bar"}'`
- [x] 6.0 snapshot tests indicate the NPROC limits need to be at least 4096; which has been merged into the systemd service unit ( #837)
- [x] `default.path.data` and `default.path.log` have been removed.
- [x] `default.path.conf` has been replaced with `--path.conf`.

**Comment by lucabelluccini** [comment]
Does this impact the plugin installation? https://github.com/elastic/elasticsearch/pull/27093

**Comment by tylerjl** [comment]
@lucabelluccini it shouldn't - plugin installation happens through command-line invocation, so there's no spots in the Puppet/Ruby code to update for that change.
