### ISSUE TITLE
Please tag latest for Forge

### ISSUE THREAD

**Issue by billnbell** [elastic/puppet-elasticsearch#778]
Please tag and submit to Puppet Forge... Would like to have latest with jvm.options.

https://forge.puppet.com/elasticsearch/elasticsearch

**Comment by tylerjl** [comment]
*Please* use GitHub for bugs and feature requests. A request like this has no place here. The work to update, release, and improve the module is an ongoing process.

The changes that have gone into the module for the next release are backwards-incompatible, so extra work is needed to test and release it. Thank you for for your patience.

**Comment by elisiano** [comment]
@tylerjl I'm a bit confused. Isn't _this_ GitHub? 
Is there a specific format on how we open "issues" for this kind of requests?

**Comment by tylerjl** [comment]
As noted in the [issue template](https://raw.githubusercontent.com/elastic/puppet-elasticsearch/bcc0a66f46bb64e015b3c419b4429cc70ffcd1b6/.github/ISSUE_TEMPLATE.md), the forums exist for general discussion. If people are hurting and need a release cut sooner, I can sympathize, but I already burn a lot of time answering generic questions here that aren't really bugs.

I'll try and cut a release that doesn't include the backwards-incompatible changes to unblock people in the meantime, hopefully that helps.
