### ISSUE TITLE
elasticsearch::plugin won't install the migration plugin 

### ISSUE THREAD

**Issue by mklein201** [elastic/puppet-elasticsearch#780]
* Module version: 0.16.0
* Puppet version: 3.5.1
* OS and version: CentOS Linux 7.2.1511

## Bug description

The migration plugin is formally called `elasticsearch-migration` and has the following `plugin-descriptor.properties`:

```description=Elasticsearch Migration Helper
version=2.0.3
name=elasticsearch-migration
site=true
```

This results in:
```
Error: Could not set 'present' on ensure: No such file or directory - /usr/share/elasticsearch/plugins/migration/.name at 169:/etc/puppet/modules/elasticsearch/manifests/plugin.pp
```

I suspect the problem is with `es_plugin_name.rb` since it is removing `elasticsearch` from the name and is looking for `/usr/share/elasticsearch/plugins/migration` instead of `/usr/share/elasticsearch/plugins/elasticsearch-migration`.

**Comment by tylerjl** [comment]
Could I see an example manifest that throws the error? Also note that Puppet < 3.8 isn't supported, so there may be some differences in testing here as well.

**Comment by mklein201** [comment]
```[root@esd6 manifests]# puppet apply -e "include cpt::migration"
Notice: Compiled catalog for esd6.box in environment production in 0.85 seconds
Error: Could not set 'present' on ensure: No such file or directory - /usr/share/elasticsearch/plugins/migration/.name at 169:/etc/puppet/modules/elasticsearch/manifests/plugin.pp
Error: Could not set 'present' on ensure: No such file or directory - /usr/share/elasticsearch/plugins/migration/.name at 169:/etc/puppet/modules/elasticsearch/manifests/plugin.pp
Wrapped exception:
No such file or directory - /usr/share/elasticsearch/plugins/migration/.name
Error: /Stage[main]/Cpt::Migration/Elasticsearch::Plugin[elasticsearch/elasticsearch-migration]/Elasticsearch_plugin[elasticsearch/elasticsearch-migration]/ensure: change from absent to present failed: Could not set 'present' on ensure: No such file or directory - /usr/share/elasticsearch/plugins/migration/.name at 169:/etc/puppet/modules/elasticsearch/manifests/plugin.pp
Notice: /Stage[main]/Cpt::Migration/Elasticsearch::Plugin[elasticsearch/elasticsearch-migration]/File[/usr/share/elasticsearch/plugins/migration]: Dependency Elasticsearch_plugin[elasticsearch/elasticsearch-migration] has failures: true
Warning: /Stage[main]/Cpt::Migration/Elasticsearch::Plugin[elasticsearch/elasticsearch-migration]/File[/usr/share/elasticsearch/plugins/migration]: Skipping because of failed dependencies
Notice: Finished catalog run in 2.29 seconds
[root@esd6 manifests]# cat migration.pp
class cpt::migration {

  elasticsearch::plugin{"elasticsearch/elasticsearch-migration":
    instances  => "esm02",
    url        => 'http://yumrepo.sys.comcast.net/cpt/3rdparty/noarch/all/elasticsearch-migration-2.0.3.zip',
  } 
}
```
OK on the puppet version comment.

**Comment by tylerjl** [comment]
Alright, I was able to reproduce this. This is kind of a greater problem with how plugins are handled; the guesswork that goes into discovering the plugin directory is pretty error-prone and special cased like crazy. The next release for this module will probably be a major point release (5.x) so I'm going to try and see if I can refactor plugin management to go about this a little more carefully so the module doesn't have to guess about plugin names.

**Comment by tylerjl** [comment]
@mklein201 I dug into this today, and unfortunately, the way that various plugins get installed into the `plugins/` directory is crazy varied, and there's not really a good way to find what plugin ends up creating a certain directory on disk.

*However*, fortunately, the plugin resource lets you specify this directly. In your case, just adding

```puppet
  module_dir => 'elasticsearch-migration',
```
 to your `elasticsearch::plugin` resource should be enough to fix the problem (you may have to remove the half-configured plugin directory from the home directory if it's still there).

I know this isn't ideal and it'd be better to get the module to automatically find the directory, but there's just not a good mechanism to do that right now. Is that a sufficient solution?

**Comment by mklein201** [comment]
It may be sufficient - I'll have to play around since the real automation is more complicated that the simple class shown above. Does the `module-dir` need to match the `name` from the `plugin-descriptor` to work properly or can it be arbitrary?

**Comment by tylerjl** [comment]
`module_dir` just needs to match the module directory (i.e., `elasticsearch-migration` from `/usr/share/elasticsearch/plugins/elasticsearch-migration`). It's the best way the plugin provider can learn about which directory the `plugin` tool dropped the plugin into.

If this ends up working for you, please go ahead and close the issue (or let me know what isn't working) 👍

**Comment by mklein201** [comment]
It has some issues during an upgrade, but I can address that in other manifests. Thanks.
