### ISSUE TITLE
homedir parameter not found

### ISSUE THREAD

**Issue by StruckRugg67** [elastic/puppet-elasticsearch#786]
* Module version: 5.0.0
* Puppet version: 4.8.2
* OS and version: RHEL 7.2

## Bug description
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'homedir' at /etc/puppetlabs/code/environments/elasticsearch/modules/elasticsearch/manifests/service/systemd.pp:165 on Elasticsearch_service_file[/lib/systemd/system/elasticsearch-staging.service] at /etc/puppetlabs/code/environments/elasticsearch/modules/elasticsearch/manifests/service/systemd.pp:165 on node lx-s014.intern.klaverblad.nl

##Description
I was using version 0.16.0 of the module. When I saw the update supporting x-pack, I tried using version 5.0.0. The first puppet run with version 5.0.0 however breaks with the error above.

I commented the homedir parameter at the mentioned line and then the puppet run completes succesfully. However the WorkingDir in the sysconfig file is blank instead of the actual location.

##Manifest
The profile I use to use this class:

class { '::elasticsearch':
    java_install             => false,
    manage_repo        => false,
    version                  => '5.2.0',
    autoupgrade         => false,
    datadir                  => '/var/lib/elasticsearch',
    restart_on_change => true,
  }

elasticsearch::instance { 'staging':
}

**Comment by tylerjl** [comment]
This is almost certainly due to failing to restart either a puppetmaster or puppet agent somewhere; this problem happens all the time when native types and providers change. Please restart any puppet masters/agents and retry.

**Comment by StruckRugg67** [comment]
Thanks, restarted the puppetserver and that fixed it.

**Comment by gna582** [comment]
In my opinion it should be changed to no longer require restarting the puppetmaster. 
Is this an one-time effort or will it be required in future module upgrades?

In my case restarting the puppetmaster requires cooperation of multiple teams and most likely planning and effort on their side which is difficult to place for the "I would like to try a new puppet module" use-case.

**Comment by tylerjl** [comment]
@gna582 unfortunately this is a limitation of Puppet itself - if native types and providers have any of their parameters changed, Puppet usually needs the master restarted. Since this module has lots of native types for resources that talk to Elasticsearch's REST API, updates usually (though not always) need to see the puppetmaster restarted.

Sorry about the inconvenience - if there was a reasonable way to avoid requiring restarts for module changes, I'd certainly try and do it.
