### ISSUE TITLE
Permissions on elasticsearch.yml breaks facter for normal users

### ISSUE THREAD

**Issue by hkowallik** [elastic/puppet-elasticsearch#788]
* Module version: 0.16.1
* Puppet version: 3.8.7
* OS and version: RHEL7

## Bug description
The facter plugin es_facts.rb tries to parse elasticsearch.yml to detect the http port.
As file is owned by elasticsearch and has permissions 440 this fails for normal users in a way that makes facter unusable for normal users.

```
facter
Permission denied - /etc/elasticsearch/CLUSTERNAME/elasticsearch.yml
```

One possible solution (good enough for us) - check if elasticsearch.yml is readable:

```
-        if File.exists?("#{dir_prefix}/#{dir}/elasticsearch.yml")
+        if File.readable?("#{dir_prefix}/#{dir}/elasticsearch.yml")
```

**Comment by tylerjl** [comment]
Yep, definitely a bug. Thank you for the report and proposed solution @hkowallik, should be a quick fix 👍
