### ISSUE TITLE
Masked instance systemd unit and empty file

### ISSUE THREAD

**Issue by Keysuke** [elastic/puppet-elasticsearch#793]
* Module version: 5.1
* Puppet version: 3.8.7
* OS and version: CentOS 7

## Bug description

I followed the instructions on the README and by running "puppet-agent -t" on the node, I get the following message, stating that the instance unit is masked :
```
Error: Could not start Service[elasticsearch-instance-es-01]: Execution of '/usr/bin/systemctl start elasticsearch-es-01.service' returned 1: Failed to start elasticsearch-es-01.service: Unit is masked.
Error: /Stage[main]/Main/Node[puppet_node1]/Elasticsearch::Instance[es-01]/Elasticsearch::Service[es-01]/Elasticsearch::Service::Systemd[es-01]/Service[elasticsearch-instance-es-01]/ensure: change from stopped to running failed: Could not start Service[elasticsearch-instance-es-01]: Execution of '/usr/bin/systemctl start elasticsearch-es-01.service' returned 1: Failed to start elasticsearch-es-01.service: Unit is masked.
```
Looking deeper, it seems the involved systemd service file :
> /usr/lib/systemd/system/elasticsearch-es-01.service

 created by this Puppet module is empty.

A workaround I found is to copy the package systemd file :
> /usr/lib/systemd/system/elasticsearch.service

to elasticsearch-es-01.service.
The package service is supposed to be masked according to the source code.

**Comment by tylerjl** [comment]
Hi @Keysuke, thanks for the report. That's weird behavior, the systemd unit file should certainly be there. Do you have an example puppet manifest you could provide so I could attempt to reproduce the issue?

**Comment by Keysuke** [comment]
Hi, the following code for the file
> /etc/puppet/manifests/site.pp

is enough for me to get the error on the puppet client when running "puppet agent -t" :
```
node 'puppet_s1' {
	class { 'elasticsearch':
		java_install => true,
		manage_repo  => true,
		repo_version => '5.x',
		restart_on_change => true,
	}
	elasticsearch::instance { 'es-01': }
}
```

Both of the systems are using CentOS 7, and have puppet-3.8.7-1.el7.noarch installed.
The puppet master is using puppetserver-1.2.0-1.el7.noarch.

Puppet does create the file elasticsearch-es-01.service. However it is empty (0 bytes). Maybe it is because the permissions changed before it needed write access (the file is owned by elasticsearch:elasticsearch).
```
Notice: /Stage[main]/Main/Node[puppet_s1]/Elasticsearch::Instance[es-01]/File[/var/lib/elasticsearch/es-01]/owner: owner changed 'root' to 'elasticsearch'
Notice: /File[/var/lib/elasticsearch/es-01]/seluser: seluser changed 'unconfined_u' to 'system_u'
Notice: /Stage[main]/Main/Node[puppet_s1]/Elasticsearch::Instance[es-01]/File[/var/log/elasticsearch/es-01]/owner: owner changed 'root' to 'elasticsearch'
Notice: /File[/var/log/elasticsearch/es-01]/seluser: seluser changed 'unconfined_u' to 'system_u'
```
This part of the logs might be related to the issue.

**Comment by tylerjl** [comment]
Hmm, does the behavior persist if you run the same manifest in a test environment without SELinux enabled? Everything looks correct otherwise to me. The module just takes a file from `files/` in order to write out the unit file, so as long as everything is available to the module, it should be present.

**Comment by Keysuke** [comment]
SELinux was already disabled when I was trying to get the client working. I tried reinstalling everything on new VMs, this issue is still here.

**Comment by tylerjl** [comment]
The CentOS 7 acceptance tests continue to run without errors, so I don't have a reproduced example given the example manifest here.

I see a few options:

1. Provide an example Vagrant setup that can get me to the same state you're describing, or
2. Start from a clean environment and post the complete logs of a puppet run with the `--debug` flag enabled.

**Comment by Keysuke** [comment]
I reinstalled everything from scratch on two CentOS 7 KVMs. I'm still getting the issue.
Here are the [logs](https://github.com/elastic/puppet-elasticsearch/files/855343/agent.txt) I get by running ```puppet agent --debug --test --verbose``` on the agent.

**Comment by tylerjl** [comment]
Hmm, I looked through the logs and didn't see anything that stood out. I may try and have to recreate this on some Virtualbox VMs. Is your setup a master-agent pair? I think I've got the rest of the information I'd need (puppet version, OS version, etc.)

**Comment by Keysuke** [comment]
Yes, my setup is a simple master-agent pair. My KVMs are using up-to-date CentOS 7, with the [packages from Puppet 3 official repository](https://docs.puppet.com/puppet/3.8/install_el.html). SELinux is disabled and iptables are flushed on both machines.

**Comment by tylerjl** [comment]
I setup a master/agent pair with the same versions you noted, and everything looks like it works over here:

```
[root@centos-7-x64 manifests]# # on the master
[root@centos-7-x64 manifests]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.2.1511 (Core)
Release:        7.2.1511
Codename:       Core
[root@centos-7-x64 manifests]# rpm -qv puppet
puppet-3.8.7-1.el7.noarch
[root@centos-7-x64 manifests]# rpm -qv puppetserver
puppetserver-1.2.0-1.el7.noarch
[root@centos-7-x64 manifests]# cat site.pp
node /centos-7-x64-agent[.]/ {
        class { 'elasticsearch':
                java_install => true,
                manage_repo  => true,
                repo_version => '5.x',
                restart_on_change => true,
        }
        elasticsearch::instance { 'es-01': }
}
[root@centos-7-x64 manifests]# getenforce
Disabled
[root@centos-7-x64 manifests]#
```

After a `puppet agent -t` on the agent machine:

```
[root@centos-7-x64-agent ~]# # on the agent
[root@centos-7-x64-agent ~]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.2.1511 (Core)
Release:        7.2.1511
Codename:       Core
[root@centos-7-x64-agent ~]# rpm -qv puppet
puppet-3.8.7-1.el7.noarch
[root@centos-7-x64-agent ~]# systemctl is-active elasticsearch-es-01
active
[root@centos-7-x64-agent ~]# getenforce
Disabled
[root@centos-7-x64-agent ~]# curl localhost:9200
{
  "name" : "centos-7-x64-agent-es-01",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "wh8ANrKISq-4OQ1Ds1KdgQ",
  "version" : {
    "number" : "5.2.2",
    "build_hash" : "f9d9b74",
    "build_date" : "2017-02-24T17:26:45.835Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.1"
  },
  "tagline" : "You Know, for Search"
}
[root@centos-7-x64-agent ~]#
```

Apologies that we seem to be running in circles, but I still can't seem to reproduce the issue.

**Comment by Keysuke** [comment]
Have you enabled the "updates" repository for yum and updated everything you could ?
Here is the output of of `lsb_release -a` in my machines : 
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core) 
Release:        7.3.1611
Codename:       Core
```

**Comment by tylerjl** [comment]
Re-ran the tests after completely upgrading a clean environment and things still work:

```
[root@centos-7-x64-agent ~]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core)
Release:        7.3.1611
Codename:       Core
[root@centos-7-x64-agent ~]#
```

**Comment by Keysuke** [comment]
I tried installing two CentOS 1611 on VirtualBox. I'm still getting the same issue as with KVM.

**Comment by DiegoGallegos4** [comment]
Same to me on CentOS 7, SELinux disabled.

**Comment by tylerjl** [comment]
So I put together a Vagrant + Virtualbox environment to simulate this. The entirety of the environment is a self-contained Vagrantfile, so we should all be on the same page after standing up the VMs.

My environment:
* vagrant 1.9.3
* Vagrant plugins:
  * `vagrant plugin install vagrant-hosts`
  * `vagrant plugin install vagrant-auto_network`

[Vagrantfile here](https://gist.github.com/tylerjl/7effafa0e2cbfc470eb39b966b3d0e64/).

With the Vagrantfile in your current working directory:

```
$ vagrant up
$ vagrant ssh agent
$ sudo puppet agent -t
$ systemctl status elasticsearch-es-01
$ curl localhost:9200
```

Based upon all the criteria mentioned in this issue, things still appear fine in this test environment. If someone can pinpoint a change somewhere that causes the behavior to manifest, I'd be happy to fix, but I'm still not seeing it right now.

**Comment by DiegoGallegos4** [comment]
@tylerjl Hi Tyler,

I wasn't restarting the instance. I am quite new at this elasticsearch instance idea. How can you add a hostname for the the node so it can be accessed by logstach  , for example: 

`curl elasticsearch-es-01:9200`

**Comment by Keysuke** [comment]
I managed to get everything working. It looks like using hostnames without underscores solves the issue.

**Comment by tylerjl** [comment]
@Keysuke glad to hear it. Hopefully this issue helps someone down the road, thanks for reporting back with the solution. 👍 

@DiegoGallegos4 I think you may be looking for something like adding an IP address and hostname pair to `/etc/hosts` in order to reach machines by hostname. Feel free to hop onto the forums at https://discuss.elastic.co if you have any other general questions.
