### ISSUE TITLE
Error: Failed to apply catalog: Section "base" is already defined, cannot redefine in /etc/yum.repos.d/centos.repo

### ISSUE THREAD

**Issue by murarisumit** [elastic/puppet-elasticsearch#796]
* Module version: 5.1.0
* Puppet version: 4.8.1
* OS and version: centos-7

## Bug description

While running running puppet agent getting following error
`Error: Failed to apply catalog: Section "base" is already defined, cannot redefine in /etc/yum.repos.d/centos.repo`

Puppet config file
```
class { 'elasticsearch':
      java_install => true,
      manage_repo  => true,
      repo_version => '2.x',
      version => "2.4.4",
  }
elasticsearch::instance { 'es-01': }
```

**Comment by tylerjl** [comment]
This looks unrelated to this module since it doesn't manage the repo `centos.repo`. Are there any other parts of your manifest that are managing yum repos?
