### ISSUE TITLE
BUG: Elasticsearch Templates

### ISSUE THREAD

**Issue by SOLDIERz** [elastic/puppet-elasticsearch#800]
Module Version: 5.1.0
Puppet Version: 3.7.3
OS and Version: Centos 7.2.1511

Hello everyone,

after back checking basically everything I have to raise an Issue here. I'm using the function elasticsearch::template to import my templates. At the moment I'm still running on elasticsearch 2.3.3 and an older version of the module (which has done the template import differently). So I was planning to upgrade to ES 5.2 and the latest version of the puppet module. I prepared all the stuff and everything is working as expected besides the template import. For two templates which I was using before at every puppet run I get a notice that the content has changed for all other templates I'm using the import works fine. The only thing I can say so far what the difference between the two templates which I'm importing and the other which are working fine is that they are holding more content to be clearer they have more filters defined (structure and format are the same for all templates). It seems that the import at the moment has some Issues with escaping everything right? If it is needed I can share on of template files which are raising this Issue.

**Comment by SOLDIERz** [comment]
What I should say here again. At the first run the template is created successful and also the indices which are using this two templates are pulling everything right (mappings, filter etc. pp).

**Comment by tylerjl** [comment]
Thanks for the report @SOLDIERz. Do you have any example template/puppet manifest/puppet logs you can share that sheds some further light on the issue? Also note that if you want to eliminate any version incompatibilities, currently the module formally requires at least Puppet 3.8.

**Comment by SOLDIERz** [comment]
@tylerjl Here is a gist from one of the templates: https://gist.github.com/SOLDIERz/a5665fc987189e4a3def737526908f62

**Comment by tylerjl** [comment]
It looks like you're defining several JSON values as `true` (without quotes) for mapping settings that Elasticsearch returns as `"true"` (as a string). If you quote those values to match what the Elasticsearch API returns, you should have a template that stays in-sync.

**Comment by SOLDIERz** [comment]
@tylerjl Wow thanks for the quick tipp. Will try that tomorrow and see if it helps.

**Comment by SOLDIERz** [comment]
@tylerjl Your Tipp worked. No everything is working fine and as expected. I will close the Issue by now. 👍
