### ISSUE TITLE
no parameter named 'elasticsearch_package_name'

### ISSUE THREAD

**Issue by ov7a** [elastic/puppet-elasticsearch#801]
* Module version:  0.16.2
* Puppet version: 4.9.4
* OS and version: Debian 8

## Bug description

With this simple entry for plugin 

    elasticsearch::plugin { 'x-pack': #this is new name for marvel
      ensure => present,
      instances => ['es']
    }

I get the following error:

    Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'elasticsearch_package_name' at /etc/puppetlabs/code/environments/production/modules/elasticsearch/manifests/plugin.pp:161 on Elasticsearch_plugin[x-pack] at /etc/puppetlabs/code/environments/production/modules/elasticsearch/manifests/plugin.pp:161 on node

**Comment by tylerjl** [comment]
This is a common problem when updating a module that changes parameters for a native provider (see [the upstream Puppet Labs issue](https://tickets.puppetlabs.com/browse/SERVER-94)). Please try restarting the puppetmaster (and potentially any effected puppet agents) and try re-running puppet again.

**Comment by ov7a** [comment]
Yep, issue is fixed with puppet master restart. Thank you!
