### ISSUE TITLE
Move Approved Status to new Module

### ISSUE THREAD

**Issue by SimonHoenscheid** [elastic/puppet-elasticsearch#808]
The Old Puppet Module is still Approved by Puppetlabs, the new one is not, but has a better quality.  The Approved Status should be moved to the new Module

**Comment by tylerjl** [comment]
I asked Puppet Labs to approve the new module namespace when I migrated the module over but haven't heart back yet. The upstream ticket is [here](https://tickets.puppetlabs.com/browse/MODULES-4401).

**Comment by tylerjl** [comment]
This is done: https://forge.puppet.com/elastic/elasticsearch
