### ISSUE TITLE
no way to update a plugin

### ISSUE THREAD

**Issue by soalhn** [elastic/puppet-elasticsearch#810]
* Module version: 5.1.1
* Puppet version: 3.8.7
* Elasticsearch version: 2.4.1
* OS and version: CentOS

## Bug description
Currently there's no way to update a plugin in a simple manner, eg. by just changing a version number.

For example when we already installed "royrusso/elasticsearch-hq/v2.0.2", then changing it to "royrusso/elasticsearch-hq/v2.0.3" should just update the plugin, but currently it triggers an error:
```
ERROR: plugin directory /usr/share/elasticsearch/plugins/hq already exists. To update the plugin, uninstall it first using 'remove hq' command> at 161:/etc/puppet/modules/elasticsearch/manifests/plugin.pp
Error: Could not set 'present' on ensure: Failed to install plugin. Received error: #<Puppet::ExecutionFailure: Execution of '/usr/share/elasticsearch/bin/plugin install --batch royrusso/elasticsearch-hq/v2.0.3' returned 74: -> Installing royrusso/elasticsearch-hq/v2.0.3...
```

**Comment by tylerjl** [comment]
Thank you for the report, this is definitely a bug with the module. There's a simple fix I've committed [here](https://github.com/tylerjl/puppet-elasticsearch/blob/303347696101cd7d6e2ef493abe8485bde5aa4ab/lib/puppet/provider/elastic_plugin.rb#L143) in a fork and will work into the next release. Thanks again for letting us know about it!

**Comment by soalhn** [comment]
Thanks very much for such a fast fix! I will test it soon.
