### ISSUE TITLE
Instance init_defaults doesn't ensure DATA_DIR before ES_HOME

### ISSUE THREAD

**Issue by faxm0dem** [elastic/puppet-elasticsearch#816]
* Module version: v0.16.0
* Puppet version: v4.3
* OS and version: Centos7

## Bug description

On ES startup:
```
java.nio.file.AccessDeniedException: /$ES_HOME
```

The root cause: the ordering of `/etc/sysconfig/elasticsearch` is obviously wrong:

```
DATA_DIR=$ES_HOME/data
ES_GROUP=elasticsearch
ES_HOME=/usr/share/elasticsearch
ES_USER=elasticsearch
LOG_DIR=/var/log/elasticsearch/prod
```

## Proposed solution

Either:

1. Fix ordering
2. expand `$ES_HOME` in the value of `$DATA_DIR`

**Comment by tylerjl** [comment]
This should actually be solved in the latest version of the module. Taken from the 5.1.1 files: [data dir set here](https://github.com/elastic/puppet-elasticsearch/blob/887f279cad3681dfcc341fc3559060d6376016fb/manifests/instance.pp#L488) defaults to [the traditional `/var/lib/` location](https://github.com/elastic/puppet-elasticsearch/blob/887f279cad3681dfcc341fc3559060d6376016fb/manifests/params.pp#L120) on Linux. Does that resolve the issue for you?

**Comment by faxm0dem** [comment]
It would, I guess.
That being said I just discovered that the root cause isn't the ordering, it's more surprisingly the syntax: when replacing `DATA_DIR=$ES_HOME/data` with `DATA_DIR=${ES_HOME}/data` then it works!

I guess systemd is parsing the file instead of just sourcing it (?!)

**Comment by pysysops** [comment]
I've just bumped into this too. a question I have is why is DATA_DIR different from path.data in the elasticsearch.yml config? 

Souldn't they be the same? (I don't know)
