### ISSUE TITLE
Bump puppetlabs/apt dependency

### ISSUE THREAD

**Issue by aquister** [elastic/puppet-elasticsearch#817]

**Comment by den-is** [comment]
According to the Puppet Style Guide https://docs.puppet.com/puppet/latest/style_guide.html#dependencies , epel and apt are soft dependencies and should be treated as such.

```
Warning: Module 'puppetlabs-apt' (v4.0.0) fails to meet some dependencies:
  'elastic-elasticsearch' (v5.1.0) requires 'puppetlabs-apt' (>= 2.0.0 < 3.0.0)
```

**Comment by tylerjl** [comment]
Hey @den-is, I read that documentation page and it cites the rabbitmq module as an example, [which declares the `apt`  module dependency in the same way this module does](https://github.com/puppetlabs/puppetlabs-rabbitmq/blob/2000ce7fb7983f707b6657eeef690e4c6e04f67d/metadata.json#L51). Is there some documentation around or some official modules that illustrate apt is a soft dependency?

**Comment by alaunay** [comment]
Hello,
I get that you copied from rabbitmq, but what's the rational in having a limit on the maximum version ? I get the minimum one, but the max...

Oh, BTW, rabbitmq module has updated its dependencies:

https://github.com/puppetlabs/puppetlabs-rabbitmq/blob/master/metadata.json

**Comment by tylerjl** [comment]
@alaunay maximum allowed version numbers are included in the `metadata.json` file because 1) it's safer (i.e., any breaking changes with a major version change have to be tested first), and 2) because the forge actively penalizes any module that includes dependencies without one (for the aforementioned reason).

**Comment by alaunay** [comment]
Ok, thanks for the explanation, I get it.

That being said, I just tested with the latest puppetlabs-apt 4.x (and some debian behind), it works just well. Maybe modifying the dep like the rabbitmq module, with a < 5.0.0 as a max  for now ?

**Comment by tylerjl** [comment]
Sure - I can update the tests to test against 4.x and if everything passes, I'll go ahead and update the metadata file.

**Comment by tylerjl** [comment]
Updated in #858, will go out in the next release.
