### ISSUE TITLE
java.lang.IllegalArgumentException: unknown setting [default.path.home] Elasticsearch 5.4.0

### ISSUE THREAD

**Issue by TuningYourCode** [elastic/puppet-elasticsearch#818]
* Module version: 5.1.0 (persists with 5.1.1)
* Puppet version: 3.7.2
* OS and version: Debian Jessie 8.7

## Bug description

Puppet Module does not work together with elasticsearch 5.4.0 as the systemd service file sets default.path.home which will result in an exception at startup:

`
May 05 11:41:41 log-server elasticsearch[26691]: [2017-05-05T11:41:41,164][INFO ][o.e.p.PluginsService     ] [log-server-logstash-01] no plugins loaded
May 05 11:41:42 log-server elasticsearch[26691]: [2017-05-05T11:41:42,593][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [log-server-logstash-01] uncaught exception in thread [main]
May 05 11:41:42 log-server elasticsearch[26691]: org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [default.path.home] did you mean any of [default.path.conf, default.path.logs]?
May 05 11:41:42 log-server elasticsearch[26691]: at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.4.0.jar:5.4.0]
May 05 11:41:42 log-server elasticsearch[26691]: at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.4.0.jar:5.4.0]
May 05 11:41:42 log-server elasticsearch[26691]: at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.4.0.jar:5.4.0]
May 05 11:41:42 log-server elasticsearch[26691]: at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.4.0.jar:5.4.0]
May 05 11:41:42 log-server elasticsearch[26691]: at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.4.0.jar:5.4.0]
May 05 11:41:42 log-server elasticsearch[26691]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.4.0.jar:5.4.0]
May 05 11:41:42 log-server elasticsearch[26691]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.4.0.jar:5.4.0]
May 05 11:41:42 log-server elasticsearch[26691]: Caused by: java.lang.IllegalArgumentException: unknown setting [default.path.home] did you mean any of [default.path.conf, default.path.logs]?
`

**Comment by hamishforbes** [comment]
I've just run into the same problem testing out 5.4.0 this morning too.
With module 5.1.1, puppet 4.9 and Centos 7

I've got a hacky fix that's working for me in a test environment: https://github.com/elastic/puppet-elasticsearch/commit/9610007b5712d933f4c98f8776529f5eae34ddc5

**Comment by TuningYourCode** [comment]
Well, my fix introduces another flag as the problem only occours on 5.4.0 (onwards?)

**Comment by hamishforbes** [comment]
Yeah I thought about doing that but I just wanted it to work enough to test out 5.4 :)

Also all those other default's are apparently deprecated so there's probably a better fix that will remove them entirely?

**Comment by TuningYourCode** [comment]
Well, i don't know how the maintainer threads old versions. I'm also no elasticsearch guru, we are only using it in our elk-stack as simple log-server :)

it's only a quick fix, hopefully someone with more knowledge will review and probably improve the solution ;)

**Comment by tylerjl** [comment]
Yeah, it would appear upstream took the step to introduce a breaking change in a minor release which caught the module by surprise. Fortunately since we write the init files lazily we should be able to handle this without too much hassle; I'll get a branch together with a failing test and fix to resolve it.

**Comment by trevor-vaughan** [comment]
@electrical Can you give us a heads up on how Elastic's versioning works? I couldn't find it on the website so I'm not sure what to expect moving forward but breaking changes on a Y release are rough.

**Comment by eskibars** [comment]
Hi @trevor-vaughan, (@tylerjl gave me a heads-up about this).  I'm the product manager for Elasticsearch and can answer your question on versioning.

If you're interested in reading the sort of maintenance/backport/bug fix/EOL policies in full, you can do so at https://www.elastic.co/support/eol.  The short form policy we have though is to *really try* to avoid breaking backwards compatibility changes in minor releases and reserve them only for majors.  Generally serious bugs are more or less the only case, with 2 key ones we take particularly serious:

1) If we find a bug that causes/can cause a security vulnerability and which requires a breaking change, we may break backwards compatibility to try to mitigate them from propagating
2) If we find a bug that causes/can cause data loss, we may break backwards compatibility to try to mitigate that loss

Fortunately, these are both very rare and becoming increasingly rare as the Elasticsearch code matures.  However, in 5.3.0, we had a very bad bug which could result in data loss and we had several users hit it (e.g. https://github.com/elastic/elasticsearch/issues/23981).  You can read the blog including the details of this data loss scenario at https://www.elastic.co/blog/multi-data-path-bug-in-elasticsearch-5-3-0 .  As part of the RCA, we identified a number of bugs in code and in user expectations around the `default.` settings.  There was some internal debate about how to deal with this (which you can read part of at https://github.com/elastic/elasticsearch/pull/24052#issuecomment-293545767 if you're so inclined) but the ultimate decision was that this required a breaking change.

In the rare event that we have to break backwards compatibility, we always identify deprecations and breaking changes in our docs.  In the case of this one, it was at https://www.elastic.co/guide/en/elasticsearch/reference/5.4/breaking-changes-5.4.html#breaking_54_settings_changes and at the top of the release notes at https://www.elastic.co/guide/en/elasticsearch/reference/5.4/release-notes-5.4.0.html .  We should have done a better job at making sure we had flagged automation tooling for this and we'll look into ways to do so for the future

**Comment by trevor-vaughan** [comment]
@eskibars Thanks for the thorough explanation. Hopefully, having this here will help people understand why this happened, the reference link was great.

**Comment by tylerjl** [comment]
Thanks @eskibars. I've comitted a tests and a fix in e50d793 which will go out shortly in 5.2.0 on the Forge.
