### ISSUE TITLE
Allow datadir to be a symlink

### ISSUE THREAD

**Issue by TravellingGuy** [elastic/puppet-elasticsearch#819]
* Module version: 5.1.1
* Puppet version: 4.10.0
* OS and version: Ubuntu 16.04

## Bug description
(This is a bug, IMHO, but might be a feature request.)

The puppet module enforces the default data directory (/var/lib/elasticsearch/) to be directory and does not allow it to be a symlink.

In our environment, we want to keep the default data directory to be /var/lib/elasticsearch/ on a lot of our infrastructure. However, on larger Elasticsearch instances, we want to have the data directory be on an attached disk (EBS volume), as the root volume has limited space. Previously we just moved the elasticsearch/ directory from /var/lib/ to /mnt/ebs/ and made /var/lib/elasticsearch a symlink to the /mnt/ebs/elasticsearch/. This worked fine with earlier versions of the puppet module (0.16.2 and earlier), but the newest version (5.1.1) of the module doesn't allow that and during a puppet run will change the symlink back to a directory.

I also tried to move the instance directory (/var/lib/elasticsearch/es-01/) to the EBS volume and do a symlink, but the module enforces /var/lib/elasticsearch/es-01/ to be a directory as well.

(We could specify different default data directories for different servers in our hiera data store, but we try to keep things as clean and non-custom as possible, so the symlink method was a great workaround for that.)

**Comment by tylerjl** [comment]
The traditional way to solve this would be to set `datadir` to a different directory in a hiera config file, but as you mentioned, in some cases you may want to control it differently. Is using hiera not a good option here?

In lieu of hiera, another option could be a new parameter on the `elasticsearch` class, perhaps something like this:

```puppet
# [*datadir_target*]
#   Manage the `datadir` as a symlink with the value of this parameter as the target.

class { 'elasticsearch':
  datadir_target => '/mnt/ebs',
}
```

We could then `ensure => link` on the datadir and set the link target if that parameter is set. Thoughts?

**Comment by TravellingGuy** [comment]
@tylerjl, I've been thinking about this and while it's a bit more work for us (more custom hiera config), I'm thinking that setting a different datadir in the hiera config would be the best, and keep the module less complex for everyone else. I don't want to needlessly add complexity to the module that only I would use. :-)

**Comment by tylerjl** [comment]
@TravellingGuy, I 100% agree with you. Thank you immensely for approaching the issue in a way that's best for the module and the rest of the users. ❤️
