### ISSUE TITLE
Plugins should be installable without passing instances

### ISSUE THREAD

**Issue by igalic** [elastic/puppet-elasticsearch#820]
* Module version: 5.2.0
* Puppet version: 4.x
* OS and version: Ubuntu

## Bug description

When trying to install a plugin in elasticsearch we cannot leave out the `instances1` even though we may not know (all) their name.

## Feature Description

Given that all this is used is to shield restarts — which are already conditional! — we can remove the `fail()`

**Comment by tylerjl** [comment]
Makes sense to me; I'll watch the PR for passing tests. The only thing I'm worried about is whether this could catch users by surprise when instances aren't restarted when plugins get installed; but I'd rather lean towards giving people flexibility than limiting what the module lets them do so i'm 👍  here.

**Comment by tylerjl** [comment]
Merged in #821, will be a part of the next release.
