### ISSUE TITLE
Module not working with Elasticsearch 5.4

### ISSUE THREAD

**Issue by SimonHoenscheid** [elastic/puppet-elasticsearch#822]
* Module version: latest release
* Puppet version: latest release
* OS and version: Centos 7

## Bug description

I am using the module with a 3 node cluster with one instance each node. We tried to upgrade to the 5.4 release of ES on our test-cluster and got the following error:

[2017-05-09T15:55:33,920][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [es-01] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [default.path.home] did you mean any of [default.path.conf, default.path.logs]?

which is connected to the breaking change: https://www.elastic.co/guide/en/elasticsearch/reference/5.4/breaking-changes-5.4.html

Is there any option to edit the startup options of the Systemd file created by the selfwritten provider? If there is, I simply need some input, I am stuck here.

**Comment by shoggeh** [comment]
Are you sure you're on the newest version of this module? This commit seems to address issue you mention and I have no problems using 5.4 with it. https://github.com/elastic/puppet-elasticsearch/commit/e50d793956b7214aaf8d550ccfa52beacad3b77f

**Comment by tylerjl** [comment]
5.4.0 is currently passing acceptance tests in Travis, and a manual test I just ran looks good:

```
[root@centos-7-x64 ~]# jq '.version' /etc/puppetlabs/code/modules/elasticsearch/metadata.json
"5.2.0"
[root@centos-7-x64 ~]# puppet --version
4.10.0
[root@centos-7-x64 ~]# cat test.pp
class { 'elasticsearch':
        java_install => true,
        manage_repo => true,
        repo_version => '5.x',
}
elasticsearch::instance { 'es-01' : }
[root@centos-7-x64 ~]# systemctl is-active elasticsearch-es-01
active
[root@centos-7-x64 ~]# curl localhost:9200 | jq '.version'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   338  100   338    0     0  15900      0 --:--:-- --:--:-- --:--:-- 16900
{
  "number": "5.4.0",
  "build_hash": "780f8c4",
  "build_date": "2017-04-28T17:43:27.229Z",
  "build_snapshot": false,
  "lucene_version": "6.5.0"
}
[root@centos-7-x64 ~]#
```

Like @shoggeh mentioned, you'll need to make sure you're on at least module version 5.2.0.

**Comment by SimonHoenscheid** [comment]
It works. Thx!
