### ISSUE TITLE
Cannot start elasticsearch service with systemd on CentOS7

### ISSUE THREAD

**Issue by grantholly** [elastic/puppet-elasticsearch#832]
* Module version: 0.10.1
* Puppet version: 4.3.2
* OS and version: CentOS Release 7.3.1611-201704

## Bug description

I am trying to install multiple instances of elasticsearch 5.4.0-1.  The problem that I am running into is that puppet cannot start the elasticsearch services.  I've double checked the permissions on /var/run/elasticsearch:

`drwxr-xr-x 2 elasticsearch elasticsearch 40 May 25 11:18 /var/run/elasticsearch/`

This previously worked when I used the same puppet code and module version to manage our cluster at elasticsearch version 2.4.0.

here's the error is trying to start elasticsearch:
`Error: Could not start Service[elasticsearch-instance-logstash-1]: Execution of '/usr/bin/systemctl start elasticsearch-logstash-1.service' returned 1: Job for elasticsearch-logstash-1.service failed because a configured resource limit was exceeded. See "systemctl status elasticsearch-logstash-1.service" and "journalctl -xe" for details.
Error: /Stage[main]/Iovation::Role::Elasticsearch::Multi_instance/Elasticsearch::Instance[logstash-1]/Elasticsearch::Service[logstash-1]/Elasticsearch::Service::Systemd[logstash-1]/Service[elasticsearch-instance-logstash-1]/ensure: change from stopped to running failed: Could not start Service[elasticsearch-instance-logstash-1]: Execution of '/usr/bin/systemctl start elasticsearch-logstash-1.service' returned 1: Job for elasticsearch-logstash-1.service failed because a configured resource limit was exceeded. See "systemctl status elasticsearch-logstash-1.service" and "journalctl -xe" for details.`

here's what systemd says about the service:
```● elasticsearch-logstash-1.service - Starts and stops a single elasticsearch instance on this system
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch-logstash-1.service; enabled; vendor preset: disabled)
   Active: failed (Result: resources) since Thu 2017-05-25 11:52:27 PDT; 1min 43s ago
     Docs: http://www.elasticsearch.org
 Main PID: 21804 (code=exited, status=143)

May 25 11:52:25 seanplogets01.iovationnp.com systemd[1]: Starting Starts and stops a single elasticsearch instance on this system...
May 25 11:52:25 seanplogets01.iovationnp.com systemd[1]: PID file /var/run/elasticsearch/elasticsearch-logstash-1.pid not readable (yet?) after start.
May 25 11:52:27 seanplogets01.iovationnp.com systemd[1]: elasticsearch-logstash-1.service never wrote its PID file. Failing.
May 25 11:52:27 seanplogets01.iovationnp.com systemd[1]: Failed to start Starts and stops a single elasticsearch instance on this system.
May 25 11:52:27 seanplogets01.iovationnp.com systemd[1]: Unit elasticsearch-logstash-1.service entered failed state.
May 25 11:52:27 seanplogets01.iovationnp.com systemd[1]: elasticsearch-logstash-1.service failed.
```

here's the relevant puppet code that is configuring my elasticsearch instance:
```
  ### Global elasticsearch configuration ###

  class { 'elasticsearch':
    version       => $elasticsearch_hiera[version],
    datadir       => $elasticsearch_hiera[datadir],
    config => {
      'bootstrap.mlockall'                   => true,
      'cluster.name'                         => $elasticsearch_hiera[cluster_name],
      'cluster.routing.allocation.awareness.attributes' => 'rack',
      'discovery.zen.minimum_master_nodes'   => size($elasticsearch_hiera[node_list]) / 2 + 1,
      'discovery.zen.ping.multicast.enabled' => false,
      'discovery.zen.ping.unicast.hosts'     => $elasticsearch_hiera[node_list],
      'gateway.expected_nodes'               => size($elasticsearch_hiera[node_list]),
      'indices.fielddata.cache.size'         => '40%',
      'indices.memory.index_buffer_size'     => '50%',
      'network.host'                         => $::ipaddress,
      'node.name'                            => $::fqdn,
      'node.rack'                            => $::hostname[-2, -1],
      'path.repo'                            => '["/backup"]',
      'thread_pool.index.size'               => $::processors[count],
      },
    }

    $total_memory_bytes = $::memory[system][total_bytes]
    $half_memory_bytes = $total_memory_bytes / 2

    $es_instances = Integer[1, $elasticsearch_hiera[instances_per_node]]
    $es_service_names = $es_instances.map |Integer $instance| {
      "elasticsearch-logstash-${instance}"
    }

    $es_instance_count = $elasticsearch_hiera[instances_per_node]
    $es_instance_heap_size = floor($half_memory_bytes / $es_instance_count)
    $es_instance_young_gen_size = floor($es_instance_heap_size * 0.5)

    ### Elasticsearch instance configuration ###

    $es_instances.each |Integer $instance| {
      elasticsearch::instance { "logstash-${instance}":
        init_defaults => {
          'ES_JAVA_OPTS'      => "\"-Xms${es_instance_heap_size} -Xmx${es_instance_heap_size} -Xmn${es_instance_young_gen_size} -XX:ParallelGCThreads=${::processors[count]} -XX:+UseCompressedOops -XX:+AggressiveOpts -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/elasticsearch/ -XX:+PrintPromotionFailure -XX:+PrintHeapAtGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:GCLogFileSize=10M -XX:NumberOfGCLogFiles=10 -Xloggc:/var/log/elasticsearch/logstash-${instance}/gc.log\"",
          'MAX_LOCKED_MEMORY' => 'unlimited',
        },
        logging_config => {
          'action' => 'INFO',  # Default is DEBUG.  See: $elasticsearch::params::logging_defaults
        },
      }

      #ES instance services
      elasticsearch::service { "elasticsearch-logstash-${instance}":
        status => 'unmanaged',
      }
    }

    # Elasticsearch template for logstash-* indexes
    elasticsearch::template { 'logstash':
      file => 'puppet:///modules/iovation/role/elasticsearch/logstash/logstash.json',
      host => $::fqdn,
    }
  }
```

**Comment by tylerjl** [comment]
Hey @grantholly! Resource errors like that are usually visible in the logs, is there anything useful in `/var/log/elasticsearch/*`?

Also note that the 0.x series of this module _will not_ work with Elasticsearch 5.4.x. You'll need to use [the latest version of the module on the Forge](https://forge.puppet.com/elastic/elasticsearch/readme) to ensure 5.4 is supported correctly.

**Comment by grantholly** [comment]
Thanks for the quick response @tylerjl!  Looking at `/var/log/elasticsearch/*` I only see the gc log files
```
./logstash-1:
gc.log  gc.log.0.current

./logstash-2:
gc.log  gc.log.0.current

./logstash-3:
gc.log  gc.log.0.current

./logstash-4:
gc.log  gc.log.0.current
...
```
About using the latest version of the puppet module, I'm currently running puppet 4.3.2, and it looks like the latest version has a dependency on [puppet yum](https://forge.puppet.com/puppet/yum/dependencies), that requires puppet >= 4.6.1.  I'm not sure that I can use the most recent version of this module.

**Comment by tylerjl** [comment]
@grantholly note that the yum module is used primarily for versionlocking, so if that's a feature you're not using you can also potentially add `package_pin => false` to your `elasticsearch` class and continue on without the yum module entirely if you need to. There's several changes to the 5.x series that are properly supported with the updated module.

As far as further debugging, I'd look at the systemd journal to see if there's additional Elasticsearch output that's getting captured at startup. Because of the way systemd captures process output, if a service doesn't start up all the way, not all of the stderr/stderr may be captured in the output of `journalctl -u elasticsearch-logstash-1.service`, so you may want to search through `journalctl` without any filters.

**Comment by grantholly** [comment]
`package_pin => false` allows me to dodge the `::yum::versionlock` resource.  Brilliant!  

After updating other resources, looks like I'm almost there...And we're back!  While I can't upgrade puppet in the meantime, looks like using the latest version of this module and updating some of the older settings such as `discovery.zen.ping.multicast.enabled` and `bootstrap.mlockall` as examples, allows me to deploy my multi instance installation.

Thanks for all the great help and prompt replies.  Together we crushed some technical debt (hi five).
