### ISSUE TITLE
ES5 on CentOS 7 fails due to 'max number of threads is too low'

### ISSUE THREAD

**Issue by fatmcgav** [elastic/puppet-elasticsearch#836]
Elasticsearch 5.4 is failing to start on a freshly installed CentOS 7 VM with the following error:

>  max number of threads [1861] for user [elasticsearch] is too low, increase to at least [2048]

It appears that Systemd ignores the values specified in 'limits.conf', so need to add `LimitNPROC` to systemd unit file. 

PR incoming to implement.

**Comment by tylerjl** [comment]
Implemented in #837, will go out with next release.
