### ISSUE TITLE
Invalid parameter homedir

### ISSUE THREAD

**Issue by flysen** [elastic/puppet-elasticsearch#839]
The puppet code is simple, but still not working.
```
class { 'elasticsearch':
        manage_repo  => true,
        repo_version => '5.x',
        }
elasticsearch::instance { 'es-01':
        }
```
Output when running puppet is:
```
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter homedir on Elasticsearch_service_file[/lib/systemd/system/elasticsearch-es-01.service] at /etc/puppet_envs/wwwpuppet/modules/elasticsearch/manifests/service/systemd.pp:178 on node uuc-logdn015-pr.xx.xx.se
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
I've searched the forums without luck...

* Module version: 5.2
* Puppet version: 3.8
* OS and version: RHEL 7.3

**Comment by tylerjl** [comment]
This is a common problem when updating a module that changes parameters for a native provider (see [the upstream Puppet Labs issue](https://tickets.puppetlabs.com/browse/SERVER-94)). Please try restarting the puppetmaster (and potentially any effected puppet agents) and try re-running puppet again.

**Comment by flysen** [comment]
Thanks for prompt and informative update. 
Brgd 
Fredrik
