### ISSUE TITLE
Keystore feature leads to "Could not evaluate" on first run

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/puppet-elasticsearch#842]
* Module version: 5.3.0
* Puppet version: 4.7
* OS and version: CentOS 6.7

## Bug description

Testing on a VM using vagrant and puppet.

First run:

```
==> node1: Notice: /Stage[main]/Elasticsearch/Elasticsearch::Instance[skeptic]/Elasticsearch_keystore[skeptic]/ensure: created
==> node1: Error: /Stage[main]/Elasticsearch/Elasticsearch::Instance[skeptic]/Elasticsearch_keystore[skeptic]: Could not evaluate:

```

Second run:

```
Debug: Prefetching elasticsearch_keystore resources for elasticsearch_keystore
Notice: /Stage[main]/Elasticsearch/Elasticsearch::Instance[skeptic]/Elasticsearch_keystore[skeptic]/ensure: created
Debug: Executing with uid=elasticsearch gid=elasticsearch: '/usr/share/elasticsearch/bin/elasticsearch-keystore create'
Debug: Elasticsearch_keystore[skeptic](provider=elasticsearch_keystore): Created elasticsearch keystore in /etc/elasticsearch/skeptic

Debug: Executing with uid=elasticsearch gid=elasticsearch: '/usr/share/elasticsearch/bin/elasticsearch-keystore add --force --stdin xpack.security.authc.realms.realm_ldap3.bind_password'
Debug: Elasticsearch_keystore[skeptic](provider=elasticsearch_keystore):
Debug: Executing with uid=elasticsearch gid=elasticsearch: '/usr/share/elasticsearch/bin/elasticsearch-keystore list'

```

Probably a priority/dependency issue.

**Comment by tylerjl** [comment]
Hey @lucabelluccini, thanks for trying out the resource. You're right it's probably an ordering issue - it should be running after the package is installed, so I think it may be another resource it depends on. Did your first run example output have anything after that error indicating why it failed?

**Comment by lucabelluccini** [comment]
Hello!
The "Could not evaluate: " doesn't print the actual root cause.
Would you like me to send you the full debug logs of a puppet agent run?

**Comment by tylerjl** [comment]
@lucabelluccini I found the bug - the keystore utility needs the defaults file to be available, but there wasn't any resource ordering for that. I've committed a fix to a branch and will release a bugfix once everything is done and merged.

Thank you for trying out the keystore resource and reporting the bug, it's very appreciated! 👍

**Comment by lucabelluccini** [comment]
Hello @tylerjl !
Well, thank you for tackling all the issues!

I am checking out why the keystore is not working right now for a specific setting about LDAP, but it is not a problem of the puppet module since it occurrs also when setting it up manually.

Thank you again,
Luca

**Comment by tylerjl** [comment]
Merged; I'll release this soon.
