### ISSUE TITLE
Error 500 on SERVER: Server Error: no parameter named 'nproc'

### ISSUE THREAD

**Issue by alex-mesfin** [elastic/puppet-elasticsearch#846]
* Module version: 5.3.1
* Puppet version: PE 2016.4.2
* OS and version: CentOS 7.2

## Bug description
I am running into following error:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'nproc' at /etc/puppetlabs/code/environments/development/modules/elasticsearch/manifests/service/systemd.pp:154 on Elasticsearch_service_file[/lib/systemd/system/elasticsearch-data.service] at /etc/puppetlabs/code/environments/development/modules/elasticsearch/manifests/service/systemd.pp:154 on node server.domain.com
```
With the same setting in Vagrant box I can not replicate the error. I just migrated from Version 5.1.1 because, earlier version (5.1.1) would not start elasticsearch.
In my test in Vagrant environment Elasticsearch starts and all work just fine, with the new version. Any Idea why is this.
I also downgraded to 5.30 and get same error.

**Comment by tylerjl** [comment]
This is a common problem when updating a module that changes parameters for a native provider (see [the upstream Puppet Labs issue](https://tickets.puppetlabs.com/browse/SERVER-94)). Please try restarting the puppetmaster (and potentially any effected puppet agents) and try re-running puppet again.

**Comment by triforce** [comment]
I can confirm that restarting the puppetserver fixes the issue.

**Comment by alex-mesfin** [comment]
I agree, problem fixed as prescribed.
Thanks

**Comment by Vinclame** [comment]
Check this. Looks like an environment bleed situation. Environment isolations seems a permanent fix. 
https://tickets.puppetlabs.com/browse/MODULES-5802?focusedCommentId=500063&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-500063
