### ISSUE TITLE
puppet agent -t command throws error

### ISSUE THREAD

**Issue by kanchan1234** [elastic/puppet-elasticsearch#850]
Master node is installed in RHOS 6.6 . Puppet version is 3.6.2,ruby version -1.8.7
Agent node is installed in RHOS 7 .Agent version is 3.8.4 ,ruby version is 2.0
[root@blackcat puppet]$puppet agent -t --trace
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve local facts: undefined method `to_a' for "ens160":String
/var/lib/puppet/lib/facter/default_gateway.rb:46:in `block (2 levels) in <top (required)>'
/var/lib/puppet/lib/facter/default_gateway.rb:46:in `collect!'
/var/lib/puppet/lib/facter/default_gateway.rb:46:in `block in <top (required)>'
/var/lib/puppet/lib/facter/default_gateway.rb:31:in `each_line'

Is it because agent version is higher than master or due to ruby version

**Comment by tylerjl** [comment]
There's a few things here:

- The error looks like it's coming from `/var/lib/puppet/lib/facter/default_gateway.rb`, which isn't a part of this module.
- This module isn't tested or supported with anything less than Puppet 3.8.x, and the master node is running 3.6.2 and ruby 1.8.

It looks like ruby 1.8 may be having trouble with some of the expected functionality for some facts on the master node; the only suggestion I may have would be to update the master node to at least 3.8.x (and possibly ruby as well) and determine whether that makes a difference.

**Comment by kanchan1234** [comment]
ok thenks for the reply..yes it is the solution but my only concern is with the existing agent server which run on 3.6.2 and ruby version 1.8...?? will they be able to connect to master if i upgrade it to 3.8.4??? also they are some custom facts written in existing master node as per ruby 1.8 so will the old facts will be compatible with new version?

**Comment by kanchan1234** [comment]
if i use a ruby method which is supported in both version ..wil it remove the errro??or i need to upgrade the master..is like agent node can nva pull data with its lower version master node

**Comment by tylerjl** [comment]
@kanchan1234 unfortunately I don't have any definitive answers to those questions; you may want to drop into the [Puppet community Slack channel](https://slack.puppet.com/) to ask general Puppet-related questions.

If you come up with any questions when using the module, feel free to open a thread on [our discussion forums](https://discuss.elastic.co/), and do open an issue if you encounter a bug with this module.
