### ISSUE TITLE
Wrong service file for 1.x

### ISSUE THREAD

**Issue by zxzharmlesszxz** [elastic/puppet-elasticsearch#851]
* Module version: 5.3.1
* Puppet version: 4.10.4
* OS and version: Debian 8

Module contain the wrong service file for version 1.x
ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec - this file not present

**Comment by jarpy** [comment]
Do you mean for Elasticsearch version 1.x? It's very old, and no longer supported. Sorry.

**Comment by tylerjl** [comment]
Hi @zxzharmlesszxz,

@jarpy is correct, this module follows the versioning scheme for the upstream [Elasticsearch support lifecycle](https://www.elastic.co/support/eol), which designates 1.x as end-of-life with the release of 5.x. A note to this effect is in the [5.x version changelog](https://forge.puppet.com/elastic/elasticsearch/changelog#500-february-9-2017).

If you really need to keep using 1.x, the last release of version 0.x for this module should work, but beware that it's also end-of-life and any new features/bugfixes are going into the current release (5.x).

Apologies for the inconvenience, hope this helps!
