### ISSUE TITLE
how to define facts in an intial puppet server setup

### ISSUE THREAD

**Issue by kanchan1234** [elastic/puppet-elasticsearch#852]
installed Puppet master server - 3.6.2,ruby version 1.8 ,RHOS version 6.9
Puppet client 3.8.4,ruby version 2.0,RHOS version 7
connection is working fine 
[root@blackcat lib]$puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Caching catalog for blackcat.host.mobistar.be
Info: Applying configuration version '1499170732'
Notice: Finished catalog run in 0.12 seconds

I now want to define some facts as an intial try ..how to start with?

Shall i write facts in client ?

I understand facter is already installed
[root@sasin manifests]$facter
architecture => x86_64
augeasversion => 1.0.0
bios_release_date => 09/17/2015
bios_vendor => Phoenix Technologies LTD
bios_version => 6.00

**Comment by kanchan1234** [comment]
i tried to create a .rb file inside /var/lib/pauppet/lib/facter/acpi_available.rb in client/agent node
after puppet agent -t inside agent node
 I can see that the file got deleted
What actually happend?
The content of the file was simply  to echo date
require 'facter'
Facter.add("last_run") do
  setcode do
    Facter::Util::Resolution.exec('date')
  end
end

**Comment by tylerjl** [comment]
Hi @kanchan1234,

For general Puppet-related questions, I'd suggest hopping into the [Puppet community Slack channel](https://slack.puppet.com/). Please feel free to create an issue for this module if you encounter any bugs or have a feature request.
