### ISSUE TITLE
Feature: Allow for overriding gem source

### ISSUE THREAD

**Issue by cdenneen** [elastic/puppet-elasticsearch#859]
The package ships with a Gemfile that uses rubygems.
In order to allow to use private repository would either need to allow for gem_source parameter to the `elasticsearch::plugin` type or modify the source string from the packaged Gemfile.

**Comment by tylerjl** [comment]
So, the `Gemfile` at the root of this repository is only ever used for testing and development - it's never consumed by any resources/classes/types in the actual course of the module, including by `elasticsearch::plugin`. Unless there's something that I'm misunderstanding?

**Comment by cdenneen** [comment]
When you install the package for this it resides at the root just like
logstash rpm.
Where does plugin install get its gem source from? I believe from there? If
environment variable that would be fine too.

**Comment by tylerjl** [comment]
> When you install the package for this it resides at the root just like
logstash rpm.

By "package" do you mean the elasticsearch package, or this elasticsearch module? It's not actually necessary for the module to function; I could actually upload new module versions without the Gemfile present without affecting the module.

> Where does plugin install get its gem source from? I believe from there? If
environment variable that would be fine too.

`elasticsearch::plugin` installs Elasticsearch plugins via the `/usr/share/elasticsearch/bin/elasticsearch-plugin` utility, which are java plugins. It's not actually installing any plugins/libraries for rubygems, or using third-party rubygems to fetch those plugins, just plain Puppet provider code.

**Comment by cdenneen** [comment]
Ok so the elasticsearch-plugin binary isn't an embedded ruby gem installer
like logstash?

**Comment by tylerjl** [comment]
Correct; `elasticsearch-plugin` is a shell script wrapper around a Java tool to install plugins into `/usr/share/elasticsearch/plugins`; `Gemfile` is never used by either the module or the plugin tool.

**Comment by cdenneen** [comment]
Thanks
So I guess if not Gemfile is there a way to mirror plugins from git or
wherever and have plugin install using that.
I believe the prefix assumes github.com. Then user/repo?

**Comment by tylerjl** [comment]
The `elasticsearch::plugin` resource translates to the `elasticsearch-plugin` CLI tool pretty simply; you can either use the `proxy_*` parameters if you have an HTTP proxy to go through, or use the `url` parameter to point the source of the plugin to an HTTP endpoint that you mirror at. [The official plugin documentation](https://www.elastic.co/guide/en/elasticsearch/plugins/5.5/plugin-management-custom-url.html) explains how installing from third-party sources work, and the associated `url` parameter [is explained in the module documentation](https://forge.puppet.com/elastic/elasticsearch#plugins). Does that answer your question?

**Comment by cdenneen** [comment]
Yes thanks... I think the "gem" feature will probably still be useful for
the logstash plugin installs but that helps with this one.

**Comment by tylerjl** [comment]
Great, good luck!
