### ISSUE TITLE
Backup & Restore capabilities

### ISSUE THREAD

**Issue by mativillagra** [elastic/puppet-elasticsearch#861]
* Module version: 5.0.0
* Puppet version: 3.8.2
* OS and version: Red Hat Enterprise Linux Server release 6.9

## Feature Description

Reading on elasticsearch setup for backup & restore (https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html), first step is to create a repository @ elasticsearch.yml config file, here is an example, 

path.repo: ["/etc/elasticsearch/backup"]

My question is if this modules support this feature as a param, I was looking into the differents manifests, and I was not able to find it. 

Any suggestion is welcome!

Thanks in advance.

**Comment by tylerjl** [comment]
@mativillagra because this is just a configuration option, all that's required is

```puppet
class { 'elasticsearch':
  config => {
    'path.repo' => [
      '/etc/elasticsearch/backup'
    ]
  }
}
```

In addition to any other settings you might need. Does that answer your question?

**Comment by mativillagra** [comment]
Thanks for this advice, that is what I'm looking for. 

The actual code tell's 

```
class { 'elasticsearch':
    package_url  => 'file:/opt/elasticsearch-5.2.1.rpm',
} ->  

 elasticsearch::instance { 'es-01':
   datadir => '/app/elasticsearch/es-data-es01'
} ->
```

I will try your code to see how it work's. 

Thanks again!!

**Comment by mativillagra** [comment]
It works!! @tylerjl 

The actual puppet code I used, 

```
class { 'elasticsearch':
    package_url  => 'file:/opt/elasticsearch-5.2.1.rpm',
    config => {
    'path.repo' => [
      '/etc/elasticsearch/backup'
    ]
  }
} ->  

 elasticsearch::instance { 'es-01':
   datadir => '/app/elasticsearch/es-data-es01'
} ->
```

The file /etc/elasticsearch/es-01/elasticsearch.yml result as I copied here, 

```
### MANAGED BY PUPPET ###
---
node.name:  vm21-es-01
path.data: /app/elasticsearch/es-data-es01
path.logs: /var/log/elasticsearch/es-01
path.repo:
  - /etc/elasticsearch/backup

```
Thanks for the support.
