### ISSUE TITLE
facter/es_facts.rb is SSL unaware

### ISSUE THREAD

**Issue by mzahorik** [elastic/puppet-elasticsearch#863]
* Module version: 5.3.1
* Puppet version: 4.7.1 (as part of PE 2016.4.3)
* OS and version: RHEL 7.3

## Bug description

While investigating various errors in the logs of a new Elasticsearch cluster, our first with SSL/TLS enabled through the x-pack, we found repeated errors like this:

[2017-08-08T00:00:14,769][WARN ][o.e.x.s.t.n.SecurityNetty4HttpServerTransport] [<hostname redacted>] caught exception while handling client http traffic, closing connection [id: <redacted>, L:0.0.0.0/0.0.0.0:9200 ! R:/127.0.0.1:45646]
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: <rest snipped>

We traced it down to the running of facter where the es_facts.rb custom fact was looking through elasticsearch.yml for a port number, then attempting to GET '/' from localhost:<discovered port>

I am slammed for a number of weeks getting a particular project going and business travel, otherwise I'd make the changes, but I suggest the following fixes, one short term and one long term:

- Change es_facts.rb to look for xpack.security.http.ssl.enabled set to true in elasticsearch.yml, and if so, skip doing any web requests.  This will have the same effect as we have now without generating repeated errors in the ES logs.

- Add true support for x-pack w/ SSL, so when http.ssl.enabled is true:
  - Change URL to https vs http
  - Ignore SSL chain validation, or
  - Fetch CA certificate from Java keystore set in xpack.ssl.keystore.path & keystore.password (the default action for the forge module if ssl => true in instance resource) or via the setting xpack.ssl.certificate_authorities

**Comment by mzahorik** [comment]
I note now this is similar to issue 838

**Comment by tylerjl** [comment]
Given that the presence of X-Pack implies REST authentication will also be necessary to retrieve Elasticsearch API information, I'm inclined to just skip those ports since there's not really a good way to pass authentication credentials to the fact code, unless I'm overlooking some way to do so.

**Comment by tylerjl** [comment]
Closing this since #838 already exists, I have a branch going through CI that should resolve this.
