### ISSUE TITLE
Dependency: puppet-yum version

### ISSUE THREAD

**Issue by clxnetom** [elastic/puppet-elasticsearch#864]
I am not sure but looking through the code and some rudimentary testing suggests that the changes between 1.0.0 and 2.0.0 don't break anything in puppet-elasticsearch.

Would it be possible to raise the version allowed for puppet-yum so that 2.0.0 is included?

**Comment by tylerjl** [comment]
Thanks for the report @clxnetom, I ran the acceptance tests through version 2.x of the module and it looks safe to update (it uses Puppet 4.x features, so I can't add it as a permanent fixture for the acceptance testing matrix, but I'll update the impending 6.x branch to test against it).
