### ISSUE TITLE
Pass --quiet to command-line arguments in systemd service file

### ISSUE THREAD

**Issue by kamusin** [elastic/puppet-elasticsearch#867]
* Module version: 5.3.1
* Puppet version: 4.10
* OS and version: Ubuntu 16.04

## Bug description

We have just upgraded all our stacks from version 0.16 to 5.3.1 recently, and so far so good. In addition to that, we upgraded our base system from Ubuntu 14.04 to 16.04, and this brought us a problem in our client nodes. Since they have just a few gigs of space on their root partition, and if the log activity gets really intense, we are filling up our disk quite quickly. This change is due to systemd configuration, to be more precise it comes from `elasticsearch.systemd.erb` file and those two lines:

```
+StandardOutput=journal
+StandardError=inherit
```

Those two lines are flooding the syslog.conf file with elasticsearch data. Would be possible to add an option to control this behaviour?

Thanks again for keeping this awesome module and the good work,
cheers!

[1]https://discuss.elastic.co/t/prevent-logging-to-var-log-messages/54199

**Comment by jasontedor** [comment]
I think this is a case of the systemd unit file not tracking upstream: `ExecStart` should contain `--quiet` and currently it [does not](https://github.com/elastic/puppet-elasticsearch/blob/5.3.1/files/etc/init.d/elasticsearch.systemd.erb#L17-L19).

**Comment by jasontedor** [comment]
Which means I think that there is a workaround available to you: I think that that `opt_flags` there means that you can work in `--quiet` today, until a fix is available.

**Comment by kamusin** [comment]
sweet,  I will have a go with this in the meantime

**Comment by tylerjl** [comment]
Yep, this just needs to be synced with the upstream unit, I'll revisit the unit file to ensure this and other options are up-to-date (related to elastic/elasticsearch#26246)

**Comment by kamusin** [comment]
thanks a lot!
