### ISSUE TITLE
Switching from elasticsearch-elasticsearch to elastic-elasticsearch

### ISSUE THREAD

**Issue by cristianbalan** [elastic/puppet-elasticsearch#868]
I want to switch from the old
https://forge.puppet.com/elasticsearch/elasticsearch/changelog#0110--may-23-2016-
to
https://forge.puppet.com/elastic/elasticsearch/changelog#0110--may-23-2016-
and then study how to upgrade the whole thing.

But changing the Puppet Forge repo in the Puppetfile throws this error:

> The module release elastic-elasticsearch-0.11.0 does not exist on https://forgeapi.puppetlabs.com/.

What to get from this? The changelog is there but the files are on the old repo?

**Comment by tylerjl** [comment]
The new namespace in the forge only holds versions 5.x onward, the other versions in the changelog under the elastic/elasticsearch namespace are artifacts from the module's history. The old namespace should have every version pre-5.x.
