### ISSUE TITLE
Installing the kibana x-pack plugin can take a long time

### ISSUE THREAD

**Issue by hboetes** [elastic/puppet-elasticsearch#872]
Since installing the kibana x-pack plugin can take a long time and is resource intensive a warning in the documentation would be in order. For example by suggesting to set a higher timeout.

**Comment by tylerjl** [comment]
Does this belong in the [puppet-kibana repo](https://github.com/elastic/puppet-kibana)?

**Comment by hboetes** [comment]
yes it does.
