### ISSUE TITLE
Multiple instances with and without x-pack

### ISSUE THREAD

**Issue by mirkenstein** [elastic/puppet-elasticsearch#876]
* Module version: 5.4.3
* Puppet version: 4.2
* OS and version: Fedora 25 x86_64

## Bug description
I've setup three instances named: `es-01` ,`es-02`,`es-03` respectively.
I have enabled the x-pack plugin for instance number 3 only. However, the x-pack plugin gets loaded for the first 2 instances as well. 
However I would like to have x-pack enabled on `es-03` only.
The relevant section from my manifest file:

```      
elasticsearch::instance  {  'es-01': config => $config_hash_es1 ,init_defaults=>$init_hash_es1  }
elasticsearch::instance  {  'es-02': config => $config_hash_es2 ,init_defaults=>$init_hash_es2  }
elasticsearch::instance  {  'es-03': config => $config_hash_es3 ,init_defaults=>$init_hash_es3  }
elasticsearch::plugin { 'x-pack': instances => 'es-04' }
```

My temporary fix outside of puppet  is to  manually set the service files in `/usr/lib/systemd/system` for `es-01` and `es-02` to another `ES_HOME`  that is at `/usr/local/elasticsearch`  in which there is no x-pack plugin sub-folder.

What would be the proper way to achieve this functionality with the puppet module?

**Comment by cdenneen** [comment]
the `homedir` is unique to the `elasticsearch` resource and not `elasticsearch::instance` so therefore all instances on the same node share `/usr/share/elasticsearch` and then would have the same plugins.
The ES_HOME I believe is the only way to override this setting as you've discovered.
So I would probably have a hiera hash like `es_instances` and do something like this... (forgive any typo's I don't have the ability to test this at the moment so I'm doing this all freehand... @tylerjl might be able to clean this up for you):

```puppet
$es_instances.each do |String $es_instance, Hash $hash| {
  if $es_instance == 'es-03' {
    $instance_defaults = { ... hash with ES_HOME=/usr/local/elasticsearch ... }
  }else{
    $instance_defaults = { ... hash with ES_HOME=/usr/share/elasticsearch ... }
  }
  elasticsearch::instance { 
    $es_instance:  * => $hash;
    default: * => $instance_defaults;     
  }
}
```

**Comment by tylerjl** [comment]
Hi @mirkenstein, @cdenneen is right that there's a way to do this technically if you want, but because this module relies upon the repository packages and doesn't currently support installation from archives like tarballs, there's not really a supported way to do this right now (though there may be workarounds as previously mentioned).

In general, upstream Elasticsearch development has been intentionally removed some settings like `path.plugin` because running multiple nodes with different sets of plugins can be problematic. Since those settings aren't available, completely separate home directories is pretty much the only way to go about it.

**Comment by mirkenstein** [comment]
Hi @tylerjl and @cdenneen,

Setting the `ES_HOME` variable only modifies the `/etc/sysconfig/elasticsearch-es-0*` scripts.
The systemd service files in `/var/lib/systemd/system` are still referring to the original es installation path. I think that this is hard coded in here
https://github.com/elastic/puppet-elasticsearch/blob/master/files/etc/init.d/elasticsearch.systemd.erb#L15
which is picking the `homedir` variable from the  `params.pp` file  
https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/params.pp#L76

I tried to modify per instance the  `homedir` resource but looks like that is not accessible.

>  ...Elasticsearch::Instance[es-01]: has no parameter named 'homedir' ...
My config file
```
     elasticsearch::instance { 'es-01':
          homedir => '/usr/local/elasticsearch',
          config => $config_hash_es1,init_defaults =>$init_hash_es1
        } 
```
My idea was to modify the homedir resource and later modify the relevant entries in `systemd.erb`.
