### ISSUE TITLE
no parameter named 'configdir' at /etc/puppetlabs/code/modules/elasticsearch/manifests/plugin.pp:134

### ISSUE THREAD

**Issue by hboetes** [elastic/puppet-elasticsearch#880]
With the latest git pull I run into: 

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'configdir' at /etc/puppetlabs/code/modules/elasticsearch/manifests/plugin.pp:134 on Elasticsearch_plugin[x-pack] at /etc/puppetlabs/code/modules/elasticsearch/manifests/plugin.pp:134 on node elk01.example.com
```

Which seems to be caused by this commit: 77a8f64..95f919f.

What to do about this?

**Comment by hboetes** [comment]
As a workaround I used: git checkout bd4fed07deccdf9ff2c45932aa3a4ce165f46409
Which checks out the latest release from 2017.09.01

**Comment by tylerjl** [comment]
This is a common problem when updating a module that changes parameters for a native provider (see [the upstream Puppet Labs issue](https://tickets.puppetlabs.com/browse/SERVER-94)). Please try restarting the puppetmaster (and potentially any effected puppet agents) and try re-running puppet again.

**Comment by hboetes** [comment]
Hello @tylerjl,

thanks for your reply. I just restarted the puppetserver and the client and I still get the same error message.

**Comment by hboetes** [comment]
I tried again, 2 hour later and then the issue was gone. The darker mysteries of puppet...
