### ISSUE TITLE
Bad quoting

### ISSUE THREAD

**Issue by hornetmadness** [elastic/puppet-elasticsearch#886]
* Module version: 5.4.3
* Puppet version: 4.10
* OS and version: Centos7

## Bug description
Puppet Class
$cors_url="http://$ox_elasticsearch::params::ka_fronetend_hostname"
elasticsearch::instance { $ox_elasticsearch::params::es_instance_name:
		config => { 
			'network.host' => '0.0.0.0',
			'http.cors.allow-origin' => "\"$cors_url\"",
			'http.cors.enabled' => true
		}
	}

Puppet agent generates this
 ### MANAGED BY PUPPET ###
 ---
-http.cors.allow-origin: http://kibana.ofc.internal
+http.cors.allow-origin: '"http://kibana.ofc.internal"'

The line being removed is w/o the escaped quote which wouldnt work either.

**Comment by tylerjl** [comment]
Hi @hornetmadness,

So, just to be clear, which formatting are you intending to end up with and know to work correctly?

**Comment by hornetmadness** [comment]
http.cors.allow-origin: "http://kibana.domain.com" is what I was expecting.
and currently have working.

-Erik-

**Comment by tylerjl** [comment]
@hornetmadness in my testing, I can get elasticsearch running in the form without quotes, though I haven't tried connecting Kibana to it. Perhaps the config is reading it as a regular expression? Does specifying the trusted origin in regex form [as mentioned in the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html#_settings_2) work?

**Comment by tylerjl** [comment]
Closing after inactivity.
