### ISSUE TITLE
Restart elasticsearch-logstash systemd units automatically

### ISSUE THREAD

**Issue by func0der** [elastic/puppet-elasticsearch#889]
* Module version: 5.4.3
* Puppet version: 3+
* OS and version: Anything with systemd

## Bug description

Elaticsearch is know to crash from time to time.
When this happens the systemd unit enters 'fail state'.
It is not restarted by itself.

## Feature Description

The `Restart=` directive should be added to the systemd Template for elasticsearch instances.
It could be optional to not need a new major version.
It could be configurable, but I think a `Restart=always` would be sufficient.

**Comment by tylerjl** [comment]
This module keeps as close as possible to the upstream systemd unit, and [the upstream position on adding `Restart=` has been to _not_ add it to the service](https://github.com/elastic/elasticsearch/issues/25425). Like that issue mentions, controlling it through a file like `/etc/systemd/service/elasticsearch-es-01.service.d/restart.conf` is a way to configure it specifically in a particular environment. Is that a good solution for you?

**Comment by func0der** [comment]
Still would it optionally.

**Comment by tylerjl** [comment]
@func0der you're looking at the actual configuration options for systemd itself; any valid unit options can be overridden by corresponding `.d` override directories.
