### ISSUE TITLE
puppet agent failed with "undefined method `key?' for #<String:0x00000002cfc810>" error

### ISSUE THREAD

**Issue by jurim76** [elastic/puppet-elasticsearch#893]
* Module version:  5.4.3
* Puppet version: 3.7.2
* OS and version: Debian 8 Jessie

## Bug description

After upgrading Foreman to version 1.15.6 on puppet server, puppet agent failed to run on elasticsearch server.
> puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve local facts: undefined method `key?' for #<String:0x00000002cfc810>
Error: Failed to apply catalog: Could not retrieve local facts: undefined method `key?' for #<String:0x00000002cfc810>

The problematic helper module is /var/lib/puppet/lib/facter/es_facts.rb, string "tls_keys.any? { |key| config.key? key and config[key] == true }"

**Comment by tylerjl** [comment]
Hi @jurim76, unfortunately, Puppet < 3.8 is unsupported. Is there anything else we can help with?

**Comment by jurim76** [comment]
Hi,

I've upgraded puppetmaster on server and puppet-agent on client to version 3.8.7 and problem still exists

**Comment by tylerjl** [comment]
@jurim76 can I see an example of a Puppet manifest that causes the issue?

**Comment by jurim76** [comment]
I've attached hiera and puppet class for ELK hosts.

[elk_hiera.yaml.txt](https://github.com/elastic/puppet-elasticsearch/files/1470246/elk_hiera.yaml.txt)
[elk_log.pp.txt](https://github.com/elastic/puppet-elasticsearch/files/1470247/elk_log.pp.txt)

**Comment by tylerjl** [comment]
Thanks @jurim76 - I didn't see anything obvious in those logs or manifests. Can you provide what the host's `/etc/elasticsearch/es-01/elasticsearch.yml` file contains? That error comes from trying to call `key?` on the `config` variable which comes from using `YAML.load_file` on your Elasticsearch configuration yaml, which should be a Hash but is apparently a string for some reason, which makes me think that the yaml parsing may have failed somehow.

**Comment by jurim76** [comment]
Thank you for your help!
elasticsearch.yml file has been corrupted and contains only one string "To be replaced by datacat_collector[/etc/elasticsearch/es-01/elasticsearch.yml]". I've delete this file and puppet agent recreate file correctly without errors.
