### ISSUE TITLE
Add Snapshot Repository support

### ISSUE THREAD

**Issue by fatmcgav** [elastic/puppet-elasticsearch#896]
Is there any appetite for adding support for managing '[Snapshot Repository](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html)' configuration to this module?

I've added an '[elasticsearch_snapshot_repository](https://github.com/weareact/puppet-elasticsearch/commit/ace1be16ba0dce275f7bdca9c9d109aa880a0cd1)' resource to our fork, albeit on the 0.x branch as that's what we're currently using. 
However I could quite easily re-work against master if it was worth it?

Thoughts?

**Comment by tylerjl** [comment]
Sure, I'd be open to accepting a PR adding the feature. Like you mention, the PR would be need to updated against current master, and it'd likely need to be worked into the existing pattern for REST-based providers (i.e., refactor to use the `elastic_rest.rb` base providers to centralize how API calls are made), but I think it'd be a useful addition if you feel inclined to put in the effort. 👍 Nice work on the addition, by the way!

**Comment by fatmcgav** [comment]
@tylerjl Yeh, I'm game for updating to latest... In-fact it will probably be a much easier implementation... lol...
