### ISSUE TITLE
design with link to shared scripts folder from instance is not compatible with x-pack

### ISSUE THREAD

**Issue by myMarck** [elastic/puppet-elasticsearch#900]
class { 'elasticsearch':
  security_plugin   => 'x-pack',
}
elasticsearch::plugin { 'x-pack':
  instances => 'es-01',
}
elasticsearch::instance { 'es-01':
  config      => {
      'xpack.ssl.keystore.path'       =>  '/etc/elasticsearch/es-01/elasticsearch.jks',
      'xpack.ssl.keystore.password'   => $keystore_password,
      'xpack.ssl.truststore.path'     => '$truststore_path',
      'xpack.ssl.truststore.password' => $keystore_password,
}

* Module version: 6.0.0
* Puppet version: 4.10.4
* OS and version: CentOS 7.4

## Bug description
Elasticsearch will not start because of
java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/elasticsearch/es-01/scripts" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_151]

If I remove the link folder /etc/elasticsearch/es-01/scripts -> /usr/share/elasticsearch/scripts and create a normal folder called scripts Elasticsearch starts.

**Comment by cdenneen** [comment]
If you change permissions on /usr/share/elasticsearch/scripts does it work?
Is selinux enabled and blocking?

**Comment by myMarck** [comment]
SElinux is enable - but I have not seen any errors in the audit log and java.security.AccessControlException normally indicates it is a problem with java security policy and not OS rights.
/usr/share/elasticsearch/scripts is owned by elasticsearch
drwxr-xr-x.  2 elasticsearch elasticsearch      6 Nov 30 07:06 scripts

**Comment by tylerjl** [comment]
I attempted to reproduce this behavior, but did not see the error you're describing:

```
[root@centos-7-x64 ~]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[root@centos-7-x64 ~]# /opt/puppetlabs/bin/puppet help | tail -n1
Puppet v4.10.9
[root@centos-7-x64 ~]# java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
[root@centos-7-x64 ~]# cat test.pp
class { 'elasticsearch':
        security_plugin => 'x-pack',
        secrets => {
                'bootstrap.password' => 'foobar',
        }
}
elasticsearch::instance { 'es-01' : }
elasticsearch::plugin { 'x-pack' :
        instances => 'es-01',
}
[root@centos-7-x64 ~]# curl -u elastic:foobar "localhost:9200?format=yaml"
---
name: "centos-7-x64-es-01"
cluster_name: "elasticsearch"
cluster_uuid: "aD01Ap0aRNOrjEhuIqsEew"
version:
  number: "6.0.0"
  build_hash: "8f0685b"
  build_date: "2017-11-10T18:41:22.859Z"
  build_snapshot: false
  lucene_version: "7.0.1"
  minimum_wire_compatibility_version: "5.6.0"
  minimum_index_compatibility_version: "5.0.0"
tagline: "You Know, for Search"
[root@centos-7-x64 ~]# ls -la /etc/elasticsearch/es-01/scripts
lrwxrwxrwx. 1 elasticsearch elasticsearch 32 Dec  4 21:26 /etc/elasticsearch/es-01/scripts -> /usr/share/elasticsearch/scripts
[root@centos-7-x64 ~]#
```

I'm not sure what may be different in your case, although @cdenneen's suggestion about SELinux does sound like something that may be related (as my test environment doesn't have SELinux). Is there anything else you can provide to help debug your issue? I can't come up with any leads.

**Comment by myMarck** [comment]
It has to be a local se-linux error on my machine. I will disable SE linux and move on
