### ISSUE TITLE
Add elastic_stack::repo

### ISSUE THREAD

**Issue by baurmatt** [elastic/puppet-elasticsearch#901]
* Module version: Master
* Puppet version: 4.10.x
* OS and version: Ubuntu 16.04

## Bug description
elastic_stack::repo should be used consistently throughout all elastic Puppet modules. 

## Feature Description
- Remove elasticsearch::repo in favor of elastic_stack::repo

I will submit a PR.

**Comment by baurmatt** [comment]
https://github.com/elastic/puppet-elastic-stack/issues/2 needs to be fixed first.

**Comment by tylerjl** [comment]
Thanks @baurmatt, as you can probably guess integrating that module into this one was always the intent, but you're ahead of us here 😄 

Thanks for the work you're doing here, I'll keep an eye out for a PR.
