### ISSUE TITLE
Support for Amazon Linux 2

### ISSUE THREAD

**Issue by vchan2002** [elastic/puppet-elasticsearch#908]
Amazon Linux 2 has been announced, and it uses systemd.

https://aws.amazon.com/about-aws/whats-new/2017/12/introducing-amazon-linux-2/

I think it's a relatively simple change depending on some of the facts that it spits out... so I'll take a peek and put in a PR.

* Module version:
* Puppet version:
* OS and version:

**Comment by tylerjl** [comment]
Awesome, thanks for tracking this @vchan2002. Agreed that we should be able to make the decision based upon some basic facts like distro/OS major version.
