### ISSUE TITLE
Templates fail in 6.x

### ISSUE THREAD

**Issue by lwickline** [elastic/puppet-elasticsearch#910]
* Module version: 6.1
* Puppet version: 4.10.9
* OS and version: Centos 7.3.1611

## Bug description

Getting an error trying to install a template in 6.x in a fresh instance (vagrant).

 Error: /Stage[main]/logging::Elasticsearch/Elasticsearch::Template[cef-*]/Elasticsearch_template[cef-*]: Could not evaluate: Elasticsearch API responded with: Failed to parse mapping [_default_]: Enabling [_all] is disabled in 6.0. As a replacement, you can use [copy_to] on mapping fields to create your own catch all field.

code to make it get to the error: 

  ```
 elasticsearch::user { 'template_admin':
      password => $elastic_password,
      roles    => ['superuser'],
      require  => Class['::elasticsearch'],
    }

    elasticsearch::template { 'cef-*':
      api_protocol                      => 'https',
      api_timeout                       => 60,
      validate_tls                        => false,
      api_host                             => $server_host,
      api_port                             => 9200,
      api_basic_auth_password => $elastic_password,
      api_basic_auth_username => 'template_admin',
      source                                => 'puppet:///modules/logging/cef_template.json',
      require                                => Elasticsearch::User['template_admin'],
    }
```

**Comment by tylerjl** [comment]
This sounds like an issue with your index template rather than the module itself - as the error says,

```
Enabling [_all] is disabled in 6.0
```

So perhaps your templates need to be updated to work with Elasticsearch 6.1?

**Comment by lwickline** [comment]
And that was it. Sorry for the distraction.
