### ISSUE TITLE
remove VIM .swp file manifests/.instance.pp.swp from release.

### ISSUE THREAD

**Issue by phaer** [elastic/puppet-elasticsearch#912]
* Module version: 6.1.0
* Puppet version: n/a
* OS and version: n/a

## Bug description

Just a small thing: there's a VIM .swp file `manifests/.instance.pp.swp` packed into the current release and I assume it got there by mistake. Thanks a lot for your module! 👍

**Comment by tylerjl** [comment]
Whoops, thanks for pointing that out! I'll add it to the build tool's ignore file. 👍
