### ISSUE TITLE
Put the elasticsearch instance service file into /etc/systemd/system

### ISSUE THREAD

**Issue by thirdeyenick** [elastic/puppet-elasticsearch#921]
* Module version: 6.2.1
* Puppet version: 5.4.0
* OS and version: Ubuntu 16.04

## Bug description
It looks like elasticsearch service units are installed to /lib/systemd/system by default. That path normally is reserved for systemd unit files of system packages. Is there any reason why those service files are not installed to /etc/systemd/system which is the reserved place for the admin (and also configuration management systems) to create/overwrite systemd unit files?

**Comment by tylerjl** [comment]
I think part of the logic/thinking here is that by dropping these instance-based service units into `/lib/systemd`, we can free up the service paths in `/etc` for overrides if administrators need that level of control. For example, it permits users to define a file like `/etc/systemd/system/elasticsearch-es-01.service.d/override.conf` to change arbitrary options (like `RestartSec=` or something). IIRC, overrides can still happen if the parent units are in `/etc`, but it seems like stock/parent units belong in a path that signifies "here are your defaults" and `/etc` serves as a "make your configuration tweaks" directory for those units.

If, however, this is causing actual problems for a significant portion of the userbase, we can revisit it in the next major release as a breaking change.

**Comment by thirdeyenick** [comment]
Thanks for your answer. If this will end up in a big breaking change, then I think for now there is no need to change that. I was just interested in the particular reason for that decision.
