### ISSUE TITLE
The module deletes main jvm.options file.

### ISSUE THREAD

**Issue by alexizmailov** [elastic/puppet-elasticsearch#928]
* Module version: 6.2.2
* Puppet version: v5.3.2
* OS and version: Centos 7.4
* ES version: v6.2.4

## Bug description

elasticsearch/manifests/config.pp:66 removes **/etc/elasticsearch/jvm.options**
```
'/etc/elasticsearch/jvm.options':
    ensure => 'absent';
```
ES can't start after that:
```
elasticsearch[53952]: Exception in thread "main" java.nio.file.NoSuchFileException: /etc/elasticsearch/jvm.options
.....
systemd[1]: elasticsearch-int-cluster.service: main process exited, code=exited, status=1/FAILURE
```
The file can be empty but it definitely should stay there.

**Comment by tylerjl** [comment]
I ran a test manifest to attempt to reproduce your situation:

```
[root@centos-7-x64 ~]# cat test.pp
class { 'elasticsearch': version => '6.2.4' }
elasticsearch::instance { 'es-01' : }
[root@centos-7-x64 ~]# curl localhost:9200
{
  "name" : "centos-7-x64-es-01",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "o6lDFbNKQ92U8fQehhHXJg",
  "version" : {
    "number" : "6.2.4",
    "build_hash" : "ccec39f",
    "build_date" : "2018-04-12T20:37:28.497551Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
[root@centos-7-x64 ~]# systemctl is-active elasticsearch-es-01
active
[root@centos-7-x64 ~]#
```

Things appear to work fine. Do you have any more information regarding your failure? As far as I can see, things work as expected.

**Comment by alexizmailov** [comment]
I started collecting the data you requested and the problem suddenly disappeared after next puppet run.

I rebuilt the node and created another fresh one but the problem has not reoccured. 

I followed all steps I did yesterday and it just works today. The only difference is my new manager - he was watching me from behind the shoulder yesterday, so it might be his bad aura.

Sorry for bothering.

**Comment by tylerjl** [comment]
No worries, glad it's working!

**Comment by KoenDierckx** [comment]
I've also run into this issue. Any thoughts how to resolve this?
Accept #1041 ?
