### ISSUE TITLE
How can I add dependencies on Elasticsearch being up and running

### ISSUE THREAD

**Issue by nick-george** [elastic/puppet-elasticsearch#935]
## Feature Description
Hi there, 

I am performing a number of actions in Puppet (such as starting services) that rely on Elasticsearch being up and running. I use Elasticsearch::Template to apply a few templates, and I'm currently using that as a source for my relationship ording, e.g require => Elasticsearch::Template['default-settings']. I figured it's a fairly safe way to ensure ES will be up and running, as the templates can't be applied unless ES is up. 

My question is, is there a better way to ensure the ES service is up and running than the approach outlined above? Also, what if I want to get in just before the templates are applied? I'd want to do this to setup authentication (Searchguard), so that the user account I'm using to apply templates will be created before the user (via puppet) attempts to create the template. 

I hope all that makes sense, and many thanks for your time. 

Nick George

**Comment by tylerjl** [comment]
[Internally](https://github.com/tylerjl/puppet-elasticsearch/blob/cb2726a8e8d01b955df96c9c82faff3c5e0ac967/manifests/template.pp#L81), template types just rely on a custom resource called [`es_instance_conn_validator`](https://forge.puppet.com/elastic/elasticsearch/types#es_instance_conn_validator) to resolve before performing actions that interact with the Elasticsearch API. You're free to use those connection validator resources elsewhere in your manifest to create resource ordering logic based upon the API being up and available - it isn't perfect, but it lets you determine whether the API is actually reachable or not.

Does that resolve your issue?

**Comment by nick-george** [comment]
Perfect, thanks for that and apologies for not finding that resource myself. 

Cheers,
Nick
