### ISSUE TITLE
Add support for other OS's / distro's

### ISSUE THREAD

**Issue by electrical** [elastic/puppet-elasticsearch#94]
This issue can work as a wishlist for adding support for other OS's / distro's.
- Slackware
- OSX
- BSD

**Comment by bitzl** [comment]
Please add support for SUSE Enterprise Linux (`$::operatingsystem` is "SLES").

**Comment by electrical** [comment]
Hi @bitzl SLES is on our list to add. currently we are working on making our init scripting work with SLES and also have the packages compatible with the V3 signature for signed rpm's.
