### ISSUE TITLE
repo_version now deprecated and no longer a parameter

### ISSUE THREAD

**Issue by vchan2002** [elastic/puppet-elasticsearch#959]
I see that repo_version as a parameter is no longer a valid one since the latest version, since it uses the elastic_stack module to pull the repo.

Since i've been using that parameter, it now errors out with....

`
Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Elasticsearch]: has no parameter named 'repo_version' at ....
`

However, that was not mentioned in the README anywhere... or am I missing something notifying of its deprecation?

While I probabaly should have read the merged changes between versions before upgrading, it would have been nice to note that parameter's deprecation out so that we can change our code prior, rather than scrambling to fix our afterwards.

**Comment by tylerjl** [comment]
Sorry for the inconvenience here - 6.3 made some pretty significant changes that this module had to adapt for, so there wasn't much leeway for a deprecation notice (as opposed to going to something like Elasticsearch 7, which could have had a more controlled breaking major version change for the module). [There is a note regarding the deprecation of `repo_*` parameters in the changelog](https://github.com/elastic/puppet-elasticsearch/blob/master/CHANGELOG.md#migration-guide), but we'll certainly try and note breaking changes via Puppet notices moving forward whenever possible.
