### ISSUE TITLE
Elasticsearch instance service incorrectly detected as "stopped" when "running"

### ISSUE THREAD

**Issue by alexharv074** [elastic/puppet-elasticsearch#962]
## Version info

* Module version: 6.3.0, master
* Puppet version: 4.10.12
* OS and version: CentOS 7.2.1511

## Bug description

Service is incorrectly reported by introspection as `ensure => 'stopped'` and `enable => 'false'`, breaking idempotence.

Example:

```
[root@centos-72-x64 ~]# puppet resource service elasticsearch-es01 
service { 'elasticsearch-es01':
  ensure => 'running',
  enable => 'true',
}
```

and

```
[root@centos-72-x64 ~]# puppet resource service elasticsearch-instance-es01 
service { 'elasticsearch-instance-es01':
  ensure => 'stopped',
  enable => 'false',
}
```

Then puppet apply:

```
# puppet apply /tmp/apply_manifest.pp.IXyfIR --debug
...
Debug: Prefetching ruby resources for elasticsearch_service_file
Debug: Executing: '/bin/systemctl is-active elasticsearch-es01.service'
Debug: Executing: '/bin/systemctl is-enabled elasticsearch-es01.service'
Debug: Executing: '/bin/systemctl unmask elasticsearch-es01.service'
Debug: Executing: '/bin/systemctl start elasticsearch-es01.service'
Debug: Executing: '/bin/systemctl is-enabled elasticsearch-es01.service'
Notice: /Stage[main]/Profile::Elasticsearch::Data_node/Elasticsearch::Instance[es01]/Elasticsearch::Service[es01]/Elasticsearch::Service::Systemd[es01]/Service[elasticsearch-instance-es01]/ensure: ensure 
changed 'stopped' to 'running'
```

I notice that despite the resource having title `elasticsearch-instance-es01`, the provider is calling the Systemd service named `elasticsearch-es01`.

**Comment by tylerjl** [comment]
Interesting - there are idempotency tests on systemd-based distributions in the test suite, so this is unexpected. Do you have an example manifest that reproduces the behavior?

**Comment by alexharv074** [comment]
Well, you could just run the Beaker tests in here https://github.com/alexharv074/elk following the instructions for Puppet 4 in the testing section of the README. Or, you can leave it with me and I'll see if I can find the root cause when I get around to it.

**Comment by tylerjl** [comment]
Thanks @alexharv074 - there are some other issues that need fixes that I've got in the queue, so I'll leave this open for now. Feel free to add more info as you find it 👍

**Comment by alexharv074** [comment]
I am not seeing this any more, although I don't know what changed. I guess it was something weird in my set up.

**Comment by alexharv074** [comment]
I would close as "can't reproduce".
