### ISSUE TITLE
Error: Could not set 'present' on ensure: Could not find valid artifact package

### ISSUE THREAD

**Issue by NandiniArjun** [elastic/puppet-elasticsearch#974]
I am a newbie. We have a batch file which executes artifactory.pp. When i run the install batch file, I do get the error

"Wrapped exception:
Could not find valid artifact package in Artifactory
Error: /Stage[main]/Devtools::Nodejs/Nodejs::Version[0.10.36]/Remote_file::Artif
actory[nodejs-0.10.36]/Remote_file[nodejs-win-x64-0.10.36-zip]/ensure: change fr
om absent to present failed: Could not set 'present' on ensure: Could not find v
alid artifact package in Artifactory at 37:C:/dev/devtools-installer/agilemarket
s-tools-1.0.0/etc/modules/remote_file/manifests/artifactory.pp"

Could you please provide any pointers?

* Module version:
* Puppet version:
* OS and version:

**Comment by NandiniArjun** [comment]
My artifactory.pp file,

define remote_file::artifactory(
  $ensure           = 'present',
  $classifier       = undef,
  $unpack           = true,
  $creates_dir      = undef,
  $link             = false,
  $group,
  $artifact,
  $version,
  $packaging,
  $destination_dir,
) {

  if $classifier {
    $artifactClassifier = "-${classifier}"
  } else {
    $artifactClassifier = ''
  }
alert("${artifactClassifier}")

$artifactName = "${artifact}${artifactClassifier}-${version}-${packaging}"

  remote_file{ $artifactName :
    ensure            => $ensure,
    group             => $group,
    artifact          => $artifact,
    classifier        => $classifier,
    version           => $version,
    packaging         => $packaging,
    destination_dir   => $destination_dir,

    unpack            => $unpack,
    creates_dir       => $creates_dir,
    link              => $link,

    provider          => 'artifactory',
  }

  # We need this to sort out some of the issues that we have been having on Windows platforms where the extracted
  # files are a bit messed up with permissions missing on them.
  if $::kernel == 'windows' {
    acl{ "${destination_dir}" :
      permissions => [
        {identity => 'Users', rights => ['read', 'execute']},
      ],
    }
  }
}

**Comment by NandiniArjun** [comment]
Attached the .pp file

**Comment by tylerjl** [comment]
Hi @NandiniArjun,

Sorry, but this repository is for bugs and features for the puppet-elasticsearch module. If you have general Puppet help questions, I'd suggest either trying the `#puppet` channel on IRC, or joining the [Puppet community Slack](https://slack.puppet.com/) to get help. Good luck!
