### ISSUE TITLE
Defaults file ignores instance datadir

### ISSUE THREAD

**Issue by mrbanzai** [elastic/puppet-elasticsearch#978]
* Module version: 6.3.1
* Puppet version: 4.8.1
* OS and version: CentOS 7.4.1708

## Bug description

Init defaults files for instances seem to ignore `$elasticsearch::datadir` and `$elasticsearch::datadir_instance_directories`; specifically, they're not using the calculated `$elasticsearch::instance::instance_datadir`.

Perhaps this is unimportant, as `path.data` seems to get set correctly in `elasticsearch.yml`, but it's a concerning change when updating to use the latest version of the Puppet module.  I'm not certain what impact a discrepancy between `DATA_DIR` in the defaults file and `path.data` in `elasticsearch.yml` has.

**Comment by tylerjl** [comment]
@mrbanzai the defaults file is intended to set values for what it sounds like: defaults that get applied in the absence of other values. The module will always set `path.data` to the value calculated from parameters set for instances, so this default value for data directories shouldn't(?) ever be encountered, in either case. Is there a specific bug you're running into, or is this more of a general concern about how that value behaves?

**Comment by mrbanzai** [comment]
It was more of a general concern, as our configs have been managed by this Puppet module since inception and this latest update (from 5.1.0 to 6.3.1) generated a delta in the defaults files for the instances.    As I mentioned, the `path.data` gets set correctly in the configuration so it doesn't seem to have an impact, but the delta definitely concerned us in testing.

**Comment by mrbanzai** [comment]
If this behavior was desired / expected, feel free to close :)

**Comment by tylerjl** [comment]
I think for now, this is probably benign. `DATA_DIR` is mostly kept for consistency with the base package install so it'll be set if the `path.data` setting is never set, but this module sets it pretty rigidly so there's not much chance it'll ever fall through to `DATA_DIR` anyway. I'll close this for now, but if you do run into any problematic behavior, please feel free to raise it in the future. 👍
