### ISSUE TITLE
Getting ssl_error on when switching to from 6.2.2 to 6.3.3

### ISSUE THREAD

**Issue by joernott** [elastic/puppet-elasticsearch#985]
* Module version: 6.3.3
* Puppet version: 4.10.8
* OS and version: RHEL 7.5

## Bug description
We are using a CA and certificates generated with the tools provided by the elasticsearch RPM. These work as intended and cause no problems.

I am getting "Error: Failed to apply catalog: SSL_connect returned=1 errno=0 state=error: certificate verify failed" error messages since I switched the puppet module from the 6.2.2 to 6.3.3. Running "puppet agent -tdv" shows the following last lines before the error
```
Debug: Connected to the ES instance in 0.000759605 seconds.
Debug: Prefetching xpack resources for elasticsearch_license
Debug: Storing state
Debug: Stored state in 0.28 seconds
Error: Failed to apply catalog: SSL_connect returned=1 errno=0 state=error: certificate verify failed
```
My assumption is, that this error might be due to the use of es_instance_conn_validator which has problems with the custom CA/certificates.

api_host is set to the FQDN listed in the certificate and a curl to curl -u $user:$password https://$(hostname -f):9200/_cluster/health works without curl complaining about the certificate, so the CA certificate has been added correctly to the host. Also, openssl s_client shows one of the certificate SNI entries matching the host name (and the api_host entry).

**Comment by joernott** [comment]
It is not the connection validator but trying to use the "license" parameter of the elasticsearch class.

 It would be nice if

a) the license component would use the CA certificates provifded by the OS PKI infrastructure (which contains the CA certificate) 

b) A skip ssl verify would be implemented

**Comment by tylerjl** [comment]
Hey @joernott! Thanks for raising the issue (and doing some debugging).

1. The `license` provider reaches out to the Elasticsearch API using HTTP ruby libraries in Puppet. It sounds like, by default, the Ruby `Net::HTTP` library may not include the OS-level trusted certificates. If you need to instruct the module's API machinery to trusted a set of certificates, you can probably just set `elasticsearch::api_ca_path` to the directory with your trusted certificates.
2. This parameter is available and can be set with either the top-level `elasticsearch::validate_tls` parameter or specifically on `elasticsearch::license::validate_tls`.

The complete documentation for classes and their parameters [are in the generated documentation](https://elastic.github.io/puppet-elasticsearch/puppet_classes/elasticsearch.html). Do those settings help resolve what you need?

**Comment by joernott** [comment]
Hello @tylerjl, I had already set
```
api_ca_file             => "${ssldir}/${cacert}",
``` in my elasticsearch class declaration. I have added 
```
    api_ca_path             => $ssldir,
```
now to see, what is happening. If needed, I will disable the validation.

**Comment by joernott** [comment]
Setting the ca path didn't help either, so I resorted to set validate_tls to false. That solved the problem for me.
