### ISSUE TITLE
metadata.json contains deprecated "data_provider": "hiera"

### ISSUE THREAD

**Issue by Arabus** [elastic/puppet-elasticsearch#987]
* Module version: At least since 6.0.0
* Puppet version: 5  / 6
* OS and version: Ubuntu 16.04 / Ubuntu 18.04

## Bug description
The metadata.json of this module still contains the  "data_provider": "hiera" option, which was deperecated by puppet in 4.8 (https://puppet.com/docs/puppet/4.8/modules_metadata.html#deprecated-keys). Since Puppet 5 this is no longer necessary and in fact throws deprecation warnings in the puppetserver.log

The option was added in commit 0b81d21863b25b094e2ed65f80438fc6d95c4013

If you are willing, I will provide a patch simply removeing this option. (Not that this will probably break compatibility with puppet setups using puppet <5 and the Hiera data provider with this module)

**Comment by tylerjl** [comment]
Hey @Arabus, thanks for the report. Currently this module's Puppet version dependency is set at `>= 4.5.0 < 6.0.0`, and I think we'd certainly like to keep it compatible with a wide range of versions if we can for the sake of user convenience. Would removing the option break the minimal version set in the dependencies? Tests should reflect breakage if it does so, but it's worth asking before putting something together if it'll just outright break >= 4.5 of Puppet.

**Comment by Arabus** [comment]
Hmm afaik this will break in puppet < 5 so I guess removing it is not an option until this module drops puppet 4 support. Since currently this is only a deprecation and not an error I'd recommend to wait tis out.

**Comment by tylerjl** [comment]
Thanks @Arabus - for now I think we'll keep supporting Puppet 4.x, but we can revisit this once Puppet 4.x reaches end-of-life in the future.

**Comment by Zamiell** [comment]
@tylerjl If I'm not mistaken, Puppet 4.x is now end-of-life as per December 2018:
https://puppet.com/misc/puppet-enterprise-lifecycle
So we may want to reopen this issue?

**Comment by tylerjl** [comment]
@Zamiell I believe this is already resolved? https://github.com/elastic/puppet-elasticsearch/pull/1010

**Comment by Zamiell** [comment]
Oh! My apologies then.
