### ISSUE TITLE
systemd service created as a symbolic link to /dev/null

### ISSUE THREAD

**Issue by madelaney** [elastic/puppet-elasticsearch#989]
* Module version: 6.3.1
* Puppet version: 4.10.12
* OS and version: Ubuntu 16.04 LTS (amd64)

## Bug description

After applying the `elasticsearch` class, the systemd service `elasticsearch.service` is as a symbolic link to `/dev/null`

```bash
file /etc/systemd/system/elasticsearch.service 
/etc/systemd/system/elasticsearch.service: symbolic link to /dev/null
```

**Comment by tylerjl** [comment]
Hi @madelaney, this is expected, as the module controls Elasticsearch services through the creation of `elasticsearch::instance` resources in Puppet which creates dedicated services for your Elasticsearch service. Can you describe what you're trying to achieve, an example manifest, and what you would expect to see?

**Comment by madelaney** [comment]
@tylerjl , I'm a elastic search virgin and I'm trying to setup elastic search.

The catalog I'm using is as follows:
```puppet
node {
  class {
    'elasticsearch':
      plugindir        => '/usr/share/elasticsearch/plugins',
  }
}
```

```yaml
---
elasticsearch::restart_on_change: true
elasticsearch::api_protocol: https
elasticsearch::api_host: '0.0.0.0'
elasticsearch::api_timeout: 60
elasticsearch::api_basic_auth_username: admin
elasticsearch::api_basic_auth_password: 12345
elasticsearch::api_ca_file: /etc/ssl/certs
elasticsearch::api_ca_path: /etc/pki/certs
elasticsearch::validate_tls: true
elasticsearch::jvm_options:
  - '-Xms1g'
  - '-Xmx2g'
```

**Comment by madelaney** [comment]
@tylerjl Thanks! I followed your example and the original issue seems to be resolved but I'm hitting a new issue (which I think warrants a new bug) in that the catalog fails with the error message 
`no such file to load -- puppet/provider/elastic_user_command`
